#!/usr/bin/env python3
"""Regenerate THEOREM_INDEX.md from the Lean sources.

Usage:  python3 make_theorem_index.py

Walks RequestProject/*.lean, collects every top-level `theorem`/`lemma`/`def`
(with its `namespace` prefix and the first line of its doc-comment, if any) and
writes a Markdown index.  No dependencies beyond the standard library.
"""

import os
import re

SRC = "RequestProject"
OUT = "THEOREM_INDEX.md"

# Order the files so the index reads in the order the work was built.
ORDER = [
    "GolaySemantics.lean",
    "GolayHexTiles.lean",
    "CubeSurfaceMOG.lean",
    "CubeStabiliser.lean",
    "CubeTax.lean",
    "MeasuredWords.lean",
    "MeasuredSentences.lean",
    "IntegerCube.lean",
    "ThreeCube.lean",
    "Semantics.lean",
    "Grounding.lean",
    "SentenceCode.lean",
    "Chat.lean",
    "Discourse.lean",
    "WideDiscourse.lean",
    "Dialogue.lean",
    "Zipf.lean",
    "Narrative.lean",
]

DECL = re.compile(
    r"^(?P<kind>theorem|lemma|def|noncomputable def|abbrev|structure|instance)\s+"
    r"(?P<name>[^\s({\[:]+)"
)
NS = re.compile(r"^namespace\s+(\S+)")
END = re.compile(r"^end\s+(\S+)")


def module_doc(lines):
    """First paragraph of the file's leading `/-! ... -/` or `/- ... -/` block."""
    if not lines or not lines[0].startswith("/-"):
        return ""
    out = []
    for line in lines[1:]:
        if line.strip().startswith("-/"):
            break
        s = line.rstrip()
        if s.startswith("#"):
            out.append(s.lstrip("# ").strip())
    return out[0] if out else ""


def scan(path):
    with open(path, encoding="utf-8") as f:
        lines = f.read().splitlines()
    doc = module_doc(lines)
    stack, decls = [], []
    pending_doc = None
    in_doc = False
    for line in lines:
        if in_doc:
            if pending_doc is None and line.strip() and not line.strip().startswith("-/"):
                pending_doc = line.strip()
            if line.rstrip().endswith("-/"):
                in_doc = False
            continue
        if line.startswith("/-- "):
            body = line[4:]
            if body.rstrip().endswith("-/"):
                pending_doc = body.rstrip()[:-2].strip()
            else:
                pending_doc, in_doc = body.strip(), True
            continue
        m = NS.match(line)
        if m:
            stack.append(m.group(1))
            pending_doc = None
            continue
        m = END.match(line)
        if m and stack and stack[-1] == m.group(1):
            stack.pop()
            pending_doc = None
            continue
        m = DECL.match(line)
        if m:
            full = ".".join(stack + [m.group("name")])
            decls.append((m.group("kind"), full, pending_doc or ""))
        if line.strip():
            pending_doc = None if not line.startswith("/-") else pending_doc
    return doc, decls


def main():
    files = [f for f in ORDER if os.path.exists(os.path.join(SRC, f))]
    files += sorted(
        f for f in os.listdir(SRC) if f.endswith(".lean") and f not in ORDER
    )
    total_thm = total_def = 0
    body = []
    for fname in files:
        doc, decls = scan(os.path.join(SRC, fname))
        if not decls:
            continue
        thms = [d for d in decls if d[0] in ("theorem", "lemma")]
        defs = [d for d in decls if d[0] not in ("theorem", "lemma")]
        total_thm += len(thms)
        total_def += len(defs)
        body.append(f"## `{SRC}/{fname}`\n")
        if doc:
            body.append(f"*{doc}*\n")
        body.append(f"{len(defs)} definitions, {len(thms)} theorems.\n")
        body.append("| kind | name | summary |")
        body.append("|---|---|---|")
        for kind, name, d in decls:
            d = d.replace("|", "\\|")
            body.append(f"| {kind} | `{name}` | {d} |")
        body.append("")
    header = [
        "# Theorem index",
        "",
        "Every top-level declaration in the Lean development, in build order.",
        "Generated by `make_theorem_index.py`; do not edit by hand.",
        "",
        f"**Totals: {total_def} definitions, {total_thm} theorems / lemmas, "
        "0 `sorry`.**",
        "",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(header + body) + "\n")
    print(f"wrote {OUT}: {total_def} definitions, {total_thm} theorems")


if __name__ == "__main__":
    main()
