"""
hexacode.py — the MOG as six GF(4) faces.

The substrate in `substrate.py` builds the Golay code from the systematic
generator G = [I | B].  That is correct but it is *coordinate-blind*: it has no
column structure, so nothing in it can be read as a 4x6 grid, and therefore
nothing in it can be read as the faces of a cube.

This module builds the same code the other way round, from Curtis's MOG, so
that the six columns are first-class objects:

    a 4x6 binary array is a Golay codeword
        iff  every column has the same parity as the top row
        and  the six column *scores* form a word of the hexacode.

The score of a column b = (b_0, b_1, b_2, b_3) is

        score(b) = b_1 . 1 + b_2 . w + b_3 . w2        in GF(4),

i.e. the rows are labelled (0, 1, w, w2) and the score is the GF(4) sum of the
labels of the set cells.  The hexacode is the [6, 3, 4] GF(4) code generated by

        (1 0 0 1 w  w2)
        (0 1 0 1 w2 w )
        (0 0 1 1 1  1 )

Nothing here is asserted: `verify()` checks that the resulting code has 4096
words, minimum distance 8 and the Golay weight enumerator, that it is self-dual
and doubly even, and that every one of its 4096 words decomposes into a
hexacode word and a parity with no failures.

GF(4) is represented by the integers 0, 1, 2, 3 = 0, 1, w, w2, with addition
XOR and multiplication by the table below.
"""

from __future__ import annotations

from itertools import product
from typing import Dict, List, Sequence, Tuple

# ── GF(4) ────────────────────────────────────────────────────────────────────

MUL = [[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 3, 1],
       [0, 3, 1, 2]]
NAMES = {0: "0", 1: "1", 2: "w", 3: "w2"}


def gf_add(a: int, b: int) -> int:
    return a ^ b


def gf_mul(a: int, b: int) -> int:
    return MUL[a][b]


HEX_GEN: Tuple[Tuple[int, ...], ...] = (
    (1, 0, 0, 1, 2, 3),
    (0, 1, 0, 1, 3, 2),
    (0, 0, 1, 1, 1, 1),
)

ROW_LABEL = (0, 1, 2, 3)      # rows 0..3 carry GF(4) labels 0, 1, w, w2


def hexacode() -> List[Tuple[int, ...]]:
    """All 64 words of the [6, 3, 4] hexacode."""
    out = []
    for coeffs in product(range(4), repeat=3):
        w = [0] * 6
        for c, g in zip(coeffs, HEX_GEN):
            for j in range(6):
                w[j] = gf_add(w[j], gf_mul(c, g[j]))
        out.append(tuple(w))
    return out


# ── the MOG grid ─────────────────────────────────────────────────────────────
#
# Cell (row r, column c) of the 4x6 grid is bit index  4*c + r  of a 24-bit
# integer.  Column c therefore occupies bits 4c .. 4c+3, which is exactly what
# makes a column a single object -- a face.

def cell(r: int, c: int) -> int:
    return 4 * c + r


def column_bits(v: int, c: int) -> int:
    return (v >> (4 * c)) & 0xF


def column_score(col: int) -> int:
    s = 0
    for r in range(4):
        if (col >> r) & 1:
            s = gf_add(s, ROW_LABEL[r])
    return s


def column_parity(col: int) -> int:
    return bin(col).count("1") & 1


def top_row_parity(v: int) -> int:
    return sum((v >> (4 * c)) & 1 for c in range(6)) & 1


def decompose(v: int) -> Dict[str, object]:
    """Read a 24-cell object as six faces: score, parity, and legality."""
    cols = [column_bits(v, c) for c in range(6)]
    return {
        "scores": tuple(column_score(x) for x in cols),
        "parities": tuple(column_parity(x) for x in cols),
        "top_parity": top_row_parity(v),
        "columns": tuple(cols),
    }


# ── the code itself ──────────────────────────────────────────────────────────

def _f2_nullspace(rows: Sequence[int], n: int) -> List[int]:
    """Basis of {x in F2^n : <r, x> = 0 for all r}, vectors as ints.

    Reduced row echelon form, then the usual free-variable construction.
    """
    mat = [r for r in rows if r]
    piv_of_row: List[int] = []
    red: List[int] = []
    for r in mat:
        cur = r
        for p, rr in zip(piv_of_row, red):
            if (cur >> p) & 1:
                cur ^= rr
        if cur:
            p = cur.bit_length() - 1
            # clear this pivot from the rows already stored
            red = [rr ^ cur if (rr >> p) & 1 else rr for rr in red]
            piv_of_row.append(p)
            red.append(cur)
    pivots = set(piv_of_row)
    basis = []
    for f in range(n):
        if f in pivots:
            continue
        x = 1 << f
        for p, rr in zip(piv_of_row, red):
            if (rr >> f) & 1:
                x |= 1 << p
        basis.append(x)
    # sanity: every basis vector annihilates every row
    for x in basis:
        for r in rows:
            assert bin(r & x).count("1") % 2 == 0
    return basis


def _score_bit_map(labels: Sequence[int] = ROW_LABEL) -> List[int]:
    """The F2-linear map cells -> score bits: 12 forms over the 24 cells."""
    rows = [0] * 12
    for c in range(6):
        for r in range(4):
            lab = labels[r]
            for bit in (0, 1):
                if (lab >> bit) & 1:
                    rows[2 * c + bit] |= 1 << cell(r, c)
    return rows


def _hexacode_f2_basis() -> List[int]:
    """The hexacode as an F2-subspace of F2^12 (bit 2c+b = bit b of digit c)."""
    out = []
    for g in HEX_GEN:
        for mult in (1, 2):        # the GF(4)-span needs g and w*g over F2
            x = 0
            for c in range(6):
                d = gf_mul(mult, g[c])
                for bit in (0, 1):
                    if (d >> bit) & 1:
                        x |= 1 << (2 * c + bit)
            out.append(x)
    return out


def _constraint_rows(labels: Sequence[int] = ROW_LABEL,
                     parity_rule: bool = True) -> List[int]:
    """The F2 linear forms that a codeword must annihilate."""
    rows: List[int] = []
    if parity_rule:
        top = 0
        for c in range(6):
            top |= 1 << cell(0, c)
        for c in range(6):
            colmask = 0
            for r in range(4):
                colmask |= 1 << cell(r, c)
            rows.append(colmask ^ top)
    smap = _score_bit_map(labels)
    for f in _f2_nullspace(_hexacode_f2_basis(), 12):
        row = 0
        for k in range(12):
            if (f >> k) & 1:
                row ^= smap[k]
        rows.append(row)
    return rows


class MogCode:
    """The Golay code presented on the 4x6 grid."""

    def __init__(self, labels: Sequence[int] = ROW_LABEL,
                 parity_rule: bool = True) -> None:
        self.labels = tuple(labels)
        self.basis = _f2_nullspace(_constraint_rows(labels, parity_rule), 24)
        self.words = self._span()
        self.wordset = set(self.words)

    def _span(self) -> List[int]:
        out = [0]
        for b in self.basis:
            out += [x ^ b for x in out]
        return out

    def contains(self, v: int) -> bool:
        return v in self.wordset

    def weight_enumerator(self) -> Dict[int, int]:
        d: Dict[int, int] = {}
        for w in self.words:
            k = bin(w).count("1")
            d[k] = d.get(k, 0) + 1
        return dict(sorted(d.items()))

    def octads(self) -> List[int]:
        return [w for w in self.words if bin(w).count("1") == 8]


MOG_CODE = MogCode()


# ── verification ─────────────────────────────────────────────────────────────

def verify() -> Dict[str, object]:
    code = MOG_CODE
    rep: Dict[str, object] = {}
    rep["dimension"] = len(code.basis)
    rep["n_words"] = len(set(code.words))
    we = code.weight_enumerator()
    rep["weight_enumerator"] = we
    rep["is_golay_enumerator"] = we == {0: 1, 8: 759, 12: 2576, 16: 759, 24: 1}
    rep["min_distance"] = min(bin(w).count("1") for w in code.words if w)
    rep["doubly_even"] = all(bin(w).count("1") % 4 == 0 for w in code.words)
    rep["self_dual"] = all(bin(a & b).count("1") % 2 == 0
                           for a in code.basis for b in code.basis)
    # every word decomposes: hexacode word + uniform parity
    H = set(hexacode())
    rep["n_hexacode"] = len(H)
    fails = 0
    for w in code.words:
        d = decompose(w)
        if d["scores"] not in H:
            fails += 1
        elif len(set(d["parities"])) != 1 or d["parities"][0] != d["top_parity"]:
            fails += 1
    rep["decompose_failures"] = fails
    rep["decompose_checked"] = len(code.words)
    # the map word -> (hexacode word, parity) is 4096 -> 64 x 2, 32 words each
    counts: Dict[Tuple[object, int], int] = {}
    for w in code.words:
        d = decompose(w)
        key = (d["scores"], d["top_parity"])
        counts[key] = counts.get(key, 0) + 1
    rep["fibre_sizes"] = sorted(set(counts.values()))
    rep["n_fibres"] = len(counts)
    return rep


if __name__ == "__main__":
    import json
    print(json.dumps(verify(), indent=2, default=str))
