"""``glm_universal.reasoning.escalation`` -- the layer stack at register scale.

What this module is
-------------------
:mod:`~glm_universal.reasoning.information_loss` measures the five-layer stack
on **seven** hand-picked carriers, each chosen to exhibit one boundary.  That
answers *does each boundary exist*.  It does not answer the question the layer
work left open: *what does escalation look like when the carrier set is the
machine's own data* -- a thousand real carriers that nobody chose to make a
point.

This module answers that one.  It draws one carrier per named object from every
register the package ships and runs the same audit over the lot.

Why it can afford to
--------------------
The audit in ``information_loss`` compares carriers **pairwise**: its
``classes`` is quadratic and its ``congruence_witness`` quartic, and each
comparison may run a Leech nearest-point decode.  At 1,040 carriers that is not
a slow computation, it is an impossible one.

The way out is not an approximation.  Each layer's ``measure`` is a sum of
non-negative exact terms, and it is zero exactly when a small, cheap *reading*
of the two carriers agrees -- that reading is the layer's **class key**:

===============  ==========================================================
layer            zero-measure key, and why it is the key
===============  ==========================================================
``substrate``    the 24 parity bits.  ``_substrate_measure`` is the Hamming
                 distance between them, zero iff they are equal.
``integer``      the seven SI7 exponents **and** the parity bits.
                 ``_integer_measure`` is an L1 term plus a Hamming term,
                 both non-negative, so the sum is zero iff each is.
``rational``     the exact carrier.  ``_rational_measure`` is
                 ``metric.distance2``, which is positive definite over ℚ.
``griess``       the exact carrier again: the measure is the algebraic
                 distance *plus* ``distance2``, both non-negative, and equal
                 carriers force equal algebra elements.
``universal``    likewise the exact carrier.
``integer_raw``  the seven SI7 exponents alone -- the rejected reading, kept
                 so its cost can be measured at scale too.
===============  ==========================================================

Keys are hashable, so every quantity the study needs -- resolution, loss,
boundary sizes, refinement violations -- is computed by grouping rather than by
comparing, in time linear in the carrier count.

That the keys really are the zero sets is not asserted: :func:`key_agreement`
re-runs the layers' own ``perceive`` and ``measure`` over every pair of a
deterministic subsample and fails if ``measure == 0`` and ``key equality`` ever
disagree, and the report carries the result.  The same identification is what
``RequestProject/GLM/LayerChain.lean`` already models -- a layer there *is* its
view map -- and ``RequestProject/GLM/Escalation.lean`` proves the two facts this
study turns on: that resolution can only rise as the stack is climbed, whatever
the carrier set, and that two register entries carrying the same 24 coordinates
are separated by no layer of the stack at all.

Everything is exact.  No float is constructed anywhere in this module.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from typing import (Callable, Dict, Hashable, List, Optional, Sequence, Tuple)

from ..derived import memo
from . import dimension_layers as DL
from . import information_loss as IL

__all__ = [
    "REGISTERS", "VERIFY_PER_REGISTER", "KEYED_LAYERS", "KEY_JUSTIFICATION",
    "RegisterCarrier",
    "class_key", "keyed_classes", "keyed_resolution", "keyed_loss",
    "pair_counts", "boundary_at_scale", "refines_at_scale",
    "congruence_witness_at_scale", "resolution_ceiling",
    "register_carriers", "register_sizes", "by_register",
    "verification_sample", "key_agreement",
    "escalation_report", "default_escalation_report",
]

#: The registers the study draws from, in a fixed order.  ``spatial`` is not
#: here: it is generated by the runtime rather than shipped as data, and this
#: module stays inside the reasoning layer.
REGISTERS: Tuple[str, ...] = (
    "physics", "chemistry", "molecules", "mathematics", "harmonics", "lexicon",
)

#: How many carriers per register the key-agreement check re-derives the slow
#: way.  Every pair of the sample is checked at every layer.
VERIFY_PER_REGISTER: int = 3

#: The layers this module keys, lowest first, with the rejected reading last.
KEYED_LAYERS: Tuple[str, ...] = (
    "substrate", "integer", "rational", "griess", "universal", "integer_raw",
)

#: Why each key is exactly the layer's zero-measure reading.  Quoted by the
#: report so the justification travels with the numbers.
KEY_JUSTIFICATION: Dict[str, str] = {
    "substrate":
        "Hamming distance between the 24 parity bits; zero iff the bits are "
        "equal.",
    "integer":
        "an L1 term on the seven SI7 exponents plus a Hamming term on the "
        "parity bits, both non-negative, so zero iff both readings agree.",
    "rational":
        "metric.distance2 on the exact carriers, positive definite over the "
        "rationals, so zero iff the carriers are equal.",
    "griess":
        "the algebraic distance plus distance2 on the carriers, both "
        "non-negative; equal carriers also force equal algebra elements.",
    "universal":
        "the same measure as the Griess layer, so the same key.",
    "integer_raw":
        "an L1 term on the seven SI7 exponents alone; zero iff they agree.",
}


@dataclass(frozen=True)
class RegisterCarrier:
    """One named object of one register, as an exact 24-coordinate carrier."""

    register: str
    name: str
    carrier: Tuple[Fraction, ...]


# ===========================================================================
# 1.  THE KEYS
# ===========================================================================

def _si7(carrier: Sequence) -> Tuple[int, ...]:
    """The seven SI7 exponents, read exactly as ``_integer_perceive`` reads them.

    Only the first seven coordinates are converted: the reading does not look
    at the other seventeen, and this function is called a few hundred thousand
    times by the congruence search.
    """
    return (int(carrier[0]), int(carrier[1]), int(carrier[2]),
            int(carrier[3]), int(carrier[4]), int(carrier[5]),
            int(carrier[6]))


def class_key(layer_name: str, carrier: Sequence) -> Hashable:
    """The reading whose equality is the layer's ``measure == 0``.

    See the module docstring for the argument, and :func:`key_agreement` for
    the check that re-derives it from the layers themselves.
    """
    if layer_name == "substrate":
        return DL.parity_bits(carrier)
    if layer_name == "integer":
        return (_si7(carrier), DL.parity_bits(carrier))
    if layer_name == "integer_raw":
        return _si7(carrier)
    if layer_name in ("rational", "griess", "universal"):
        return tuple(Fraction(x) for x in carrier)
    raise KeyError(f"escalation: no class key for layer {layer_name!r}")


def keyed_classes(layer_name: str,
                  carriers: Sequence[Sequence]) -> Tuple[Tuple[int, ...], ...]:
    """Partition indices into the classes the layer resolves, by key.

    Classes come out in first-appearance order, so the result is a
    deterministic function of the carrier order -- exactly like
    :func:`glm_universal.reasoning.information_loss.classes`, which it agrees
    with wherever both can be run.
    """
    order: List[Hashable] = []
    buckets: Dict[Hashable, List[int]] = {}
    for i, carrier in enumerate(carriers):
        k = class_key(layer_name, carrier)
        if k not in buckets:
            buckets[k] = []
            order.append(k)
        buckets[k].append(i)
    return tuple(tuple(buckets[k]) for k in order)


def keyed_resolution(layer_name: str, carriers: Sequence[Sequence]) -> int:
    """How many distinct things the layer resolves among these carriers."""
    return len(keyed_classes(layer_name, carriers))


def keyed_loss(layer_name: str, carriers: Sequence[Sequence]) -> int:
    """How many carriers the layer loses: the count minus what it resolves."""
    return len(carriers) - keyed_resolution(layer_name, carriers)


# ===========================================================================
# 2.  BOUNDARIES, COUNTED RATHER THAN LISTED
# ===========================================================================

def _pairs(n: int) -> int:
    """``n`` choose 2, the number of unordered pairs inside a class."""
    return n * (n - 1) // 2


def pair_counts(lower: str, higher: str,
                carriers: Sequence[Sequence]) -> Dict[str, int]:
    """Conflated-pair counts for two layers and for both at once.

    Every quantity the boundary needs follows from three numbers -- the pairs
    the lower layer conflates, the pairs the higher one conflates, and the
    pairs *both* conflate -- and each is a sum over the classes of one
    partition, so none of them costs a pair-by-pair scan.
    """
    low = sum(_pairs(len(c)) for c in keyed_classes(lower, carriers))
    high = sum(_pairs(len(c)) for c in keyed_classes(higher, carriers))
    joint: Dict[Tuple[Hashable, Hashable], int] = {}
    for carrier in carriers:
        k = (class_key(lower, carrier), class_key(higher, carrier))
        joint[k] = joint.get(k, 0) + 1
    both = sum(_pairs(n) for n in joint.values())
    return {"lower": low, "higher": high, "both": both}


def boundary_at_scale(lower: str, higher: str,
                      carriers: Sequence[Sequence]) -> Dict[str, object]:
    """What the step from ``lower`` to ``higher`` gains, and what it costs.

    ``gained`` is the size of the boundary -- pairs the lower layer conflates
    and the higher one splits.  ``violations`` is its mirror image: pairs the
    lower layer splits and the higher one conflates, which is the escalation
    ladder losing something it already had.  A step is a refinement exactly
    when ``violations`` is zero.
    """
    counts = pair_counts(lower, higher, carriers)
    gained = counts["lower"] - counts["both"]
    violations = counts["higher"] - counts["both"]
    example = None
    if violations:
        example = _first_violating_pair(lower, higher, carriers)
    return {
        "lower": lower,
        "higher": higher,
        "lower_conflated": counts["lower"],
        "higher_conflated": counts["higher"],
        "gained": gained,
        "violations": violations,
        "refines": violations == 0,
        "example_violation": example,
    }


def _first_violating_pair(lower: str, higher: str,
                          carriers: Sequence[Sequence]
                          ) -> Optional[Tuple[int, int]]:
    """The first pair, in index order, the higher layer conflates and the lower splits."""
    seen: Dict[Hashable, List[int]] = {}
    for j, carrier in enumerate(carriers):
        hk = class_key(higher, carrier)
        lk = class_key(lower, carrier)
        for i in seen.get(hk, ()):
            if class_key(lower, carriers[i]) != lk:
                return (i, j)
        seen.setdefault(hk, []).append(j)
    return None


def refines_at_scale(lower: str, higher: str,
                     carriers: Sequence[Sequence]) -> bool:
    """Whether the higher layer sees at least as much as the lower one here."""
    return boundary_at_scale(lower, higher, carriers)["violations"] == 0


# ===========================================================================
# 3.  DOES ADDITION STILL DESCEND AT SCALE?
# ===========================================================================

#: The layers whose class key *is* the carrier.  Their kernel is equality, so
#: every operation descends to them and no search can find a witness -- see
#: ``GLM.Info.glmRationalLayer_congruentOn`` in
#: ``RequestProject/GLM/Escalation.lean``.  The search is still available for
#: them through ``exhaustive=True``, and a test runs it.
CARRIER_KEYED: Tuple[str, ...] = ("rational", "griess", "universal")


def congruence_witness_at_scale(layer_name: str,
                                carriers: Sequence[Sequence],
                                exhaustive: bool = False
                                ) -> Optional[Dict[str, object]]:
    """Three indices showing that coordinatewise addition escapes the layer.

    ``a`` and ``a2`` are indistinguishable at the layer, yet ``a + b`` and
    ``a2 + b`` are not, so the layer cannot compute the sum from what it sees.
    The witness returned is the first in ``(b, class, member)`` order, so it
    is a deterministic function of the carrier set; the search itself is
    exhaustive over every such triple.
    Taking ``b`` on both sides is no loss of generality: if some quadruple
    ``a ~ a2``, ``b ~ b2`` has ``op(a, b) !~ op(a2, b2)``, then one of the two
    steps ``op(a, b) -> op(a2, b) -> op(a2, b2)`` already differs, and each of
    those is a witness of this shape.

    ``None`` means no witness exists among these carriers.  For the three
    upper layers that is a theorem rather than a search result -- their key is
    the carrier itself, so indistinguishable carriers are *equal* and have
    equal sums -- and the search is skipped unless ``exhaustive`` asks for it.
    """
    if layer_name in CARRIER_KEYED and not exhaustive:
        return None
    pairs = [(cls[0], idx)
             for cls in keyed_classes(layer_name, carriers)
             for idx in cls[1:]]
    for j, b in enumerate(carriers):
        for i, k in pairs:
            left = class_key(layer_name, IL.carrier_sum(carriers[i], b))
            right = class_key(layer_name, IL.carrier_sum(carriers[k], b))
            if left != right:
                return {"layer": layer_name, "a": i, "a2": k, "b": j}
    return None


# ===========================================================================
# 4.  THE CEILING
# ===========================================================================

def resolution_ceiling(entries: Sequence[RegisterCarrier]) -> Dict[str, object]:
    """The named objects no layer of the stack can tell apart, and why.

    Every layer's view is a function of the carrier, so two entries carrying
    the same 24 coordinates are indistinguishable at *every* layer -- the top
    of the stack included.  The number of distinct carriers is therefore a
    hard ceiling on what escalation can ever resolve, and this function
    measures how far the registers sit below it.
    """
    groups: Dict[Tuple[Fraction, ...], List[int]] = {}
    for i, entry in enumerate(entries):
        groups.setdefault(entry.carrier, []).append(i)
    collisions = [g for g in groups.values() if len(g) > 1]
    collisions.sort(key=lambda g: (-len(g), g[0]))
    within = sum(1 for g in collisions
                 if len({entries[i].register for i in g}) == 1)
    largest = collisions[0] if collisions else []
    return {
        "entries": len(entries),
        "distinct_carriers": len(groups),
        "unreachable": len(entries) - len(groups),
        "collision_classes": len(collisions),
        "within_register": within,
        "cross_register": len(collisions) - within,
        "largest_class_size": len(largest),
        "largest_class_register": entries[largest[0]].register if largest
                                   else None,
        "largest_class_examples": [entries[i].name for i in largest[:6]],
        "examples": [
            {
                "size": len(g),
                "register": entries[g[0]].register,
                "names": [entries[i].name for i in g[:4]],
            }
            for g in collisions[:4]
        ],
    }


# ===========================================================================
# 5.  THE CARRIERS THE MACHINE ACTUALLY HOLDS
# ===========================================================================

def _register_loader(register: str) -> Callable[[], Sequence]:
    from ..data_objects import (element_objects, harmonic_objects,
                                mathematics_objects, molecule_objects,
                                physics_objects, semantic_lexicon_objects)
    if register == "physics":
        return physics_objects
    if register == "chemistry":
        return element_objects
    if register == "molecules":
        return molecule_objects
    if register == "mathematics":
        return mathematics_objects
    if register == "harmonics":
        return harmonic_objects
    if register == "lexicon":
        return lambda: semantic_lexicon_objects()[0]
    raise KeyError(f"escalation: no loader for register {register!r}")


#: Register carrier sets already built, keyed by the registers asked for.
#: Loading the six registers parses several data files; the study asks for
#: them repeatedly and they never change within a process.
_CARRIER_CACHE: Dict[Tuple[str, ...], Tuple["RegisterCarrier", ...]] = {}


def register_carriers(registers: Sequence[str] = REGISTERS
                      ) -> Tuple[RegisterCarrier, ...]:
    """One carrier per named object of each register, in register order.

    This is the carrier set the study runs on: not chosen, not sampled, and
    not made up -- it is simply everything the machine holds.
    """
    cached = _CARRIER_CACHE.get(tuple(registers))
    if cached is not None:
        return cached
    out: List[RegisterCarrier] = []
    for register in registers:
        for obj in _register_loader(register)():
            out.append(RegisterCarrier(
                register=register, name=obj.name,
                carrier=tuple(Fraction(x) for x in obj.carrier)))
    _CARRIER_CACHE[tuple(registers)] = tuple(out)
    return _CARRIER_CACHE[tuple(registers)]


def by_register(entries: Sequence[RegisterCarrier]) -> List[Dict[str, object]]:
    """The same audit register by register, so the ceiling can be attributed.

    The whole-corpus figures say how far escalation reaches; these say where
    what it does not reach comes from.  Each row is computed on that
    register's entries alone, so the rows need not sum to the whole -- two
    registers could in principle share a carrier, and ``cross_register`` in
    the ceiling is what says whether any do.
    """
    groups: Dict[str, List[RegisterCarrier]] = {}
    for entry in entries:
        groups.setdefault(entry.register, []).append(entry)
    out: List[Dict[str, object]] = []
    for register in REGISTERS:
        group = groups.get(register)
        if not group:
            continue
        carriers = [e.carrier for e in group]
        distinct = len(set(carriers))
        out.append({
            "register": register,
            "entries": len(group),
            "substrate": keyed_resolution("substrate", carriers),
            "integer": keyed_resolution("integer", carriers),
            "distinct_carriers": distinct,
            "unreachable": len(group) - distinct,
        })
    return out


def register_sizes(entries: Sequence[RegisterCarrier]) -> Dict[str, int]:
    """How many entries each register contributed."""
    sizes: Dict[str, int] = {}
    for entry in entries:
        sizes[entry.register] = sizes.get(entry.register, 0) + 1
    return sizes


def verification_sample(entries: Sequence[RegisterCarrier],
                        per_register: int = VERIFY_PER_REGISTER
                        ) -> Tuple[RegisterCarrier, ...]:
    """A small, evenly spread, deterministic slice of the registers.

    Evenly spread rather than the first few, so the sample is not all of one
    domain, and index-based rather than random, so it is the same sample in
    every interpreter.
    """
    by_register: Dict[str, List[RegisterCarrier]] = {}
    for entry in entries:
        by_register.setdefault(entry.register, []).append(entry)
    out: List[RegisterCarrier] = []
    for register in REGISTERS:
        group = by_register.get(register, [])
        if not group:
            continue
        take = min(per_register, len(group))
        for k in range(take):
            out.append(group[(k * len(group)) // take])
    return tuple(out)


def key_agreement(entries: Sequence[RegisterCarrier]) -> Dict[str, object]:
    """Re-derive the keys from the layers themselves, the slow way.

    For every pair of the sample and every layer, the layer's own ``perceive``
    and ``measure`` are run and their verdict compared with the keys'.  A
    single disagreement makes ``agrees`` false and names the pair, and the
    report carries that field, so the fast path can never be quietly wrong.
    """
    carriers = [e.carrier for e in entries]
    layers = list(DL.LAYERS) + [DL.LAYER_INTEGER_RAW]
    checked = 0
    disagreements: List[Dict[str, object]] = []
    for layer in layers:
        for i in range(len(carriers)):
            for j in range(i + 1, len(carriers)):
                by_measure = IL.indistinguishable(layer, carriers[i],
                                                  carriers[j])
                by_key = (class_key(layer.name, carriers[i])
                          == class_key(layer.name, carriers[j]))
                checked += 1
                if by_measure != by_key:
                    disagreements.append({
                        "layer": layer.name,
                        "a": entries[i].name, "b": entries[j].name,
                        "by_measure": by_measure, "by_key": by_key})
    return {
        "sample_size": len(entries),
        "sample_names": [e.name for e in entries],
        "layers": [layer.name for layer in layers],
        "pairs_checked": checked,
        "agrees": not disagreements,
        "disagreements": disagreements,
    }


# ===========================================================================
# 6.  THE REPORT
# ===========================================================================

def escalation_report(entries: Optional[Sequence[RegisterCarrier]] = None
                      ) -> Dict[str, object]:
    """The whole study, recomputed.  Every number here is computed.

    Nothing in it is quoted from a document, and nothing is sampled except the
    key-agreement check, whose sample is fixed by index.

    Over the default carrier set the report is a derivation of frozen
    registers, so it is computed once per process and reused;
    ``default_escalation_report.__wrapped__()`` recomputes it from scratch,
    which is what a test that wants to prove the reuse changes nothing calls.
    Passing ``entries`` always recomputes.
    """
    if entries is None:
        return default_escalation_report()
    return _escalation_report(entries)


@memo
def default_escalation_report() -> Dict[str, object]:
    """The study over every carrier the machine holds."""
    return _escalation_report(register_carriers())


def _escalation_report(entries: Sequence[RegisterCarrier]
                       ) -> Dict[str, object]:
    """Do the work :func:`escalation_report` describes, reusing nothing."""
    carriers = [e.carrier for e in entries]
    stack = ("substrate", "integer", "rational", "griess", "universal")

    layers = []
    for name in KEYED_LAYERS:
        witness = congruence_witness_at_scale(name, carriers)
        if witness is not None:
            witness = dict(witness)
            witness["names"] = [entries[witness[k]].name
                                for k in ("a", "a2", "b")]
        layers.append({
            "name": name,
            "resolution": keyed_resolution(name, carriers),
            "loss_count": keyed_loss(name, carriers),
            "largest_class": max(
                (len(c) for c in keyed_classes(name, carriers)), default=0),
            "addition_descends": witness is None,
            "congruence_witness": witness,
            "key": KEY_JUSTIFICATION[name],
        })

    boundaries = [boundary_at_scale(lo, hi, carriers)
                  for lo, hi in zip(stack, stack[1:])]

    raw = boundary_at_scale("substrate", "integer_raw", carriers)
    fixed = boundary_at_scale("substrate", "integer", carriers)

    return {
        "registers": list(REGISTERS),
        "register_sizes": register_sizes(entries),
        "by_register": by_register(entries),
        "carrier_count": len(entries),
        "layers": layers,
        "boundaries": boundaries,
        "refinement_chain_intact": all(b["refines"] for b in boundaries),
        "ceiling": resolution_ceiling(entries),
        "non_cumulative": {
            "layer": "integer_raw",
            "resolution": keyed_resolution("integer_raw", carriers),
            "loss_count": keyed_loss("integer_raw", carriers),
            "refines_substrate": raw["refines"],
            "violations": raw["violations"],
            "example_violation": raw["example_violation"],
            "example_violation_names":
                [entries[i].name for i in raw["example_violation"]]
                if raw["example_violation"] else None,
            "cumulative_refines_substrate": fixed["refines"],
            "cumulative_resolution": keyed_resolution("integer", carriers),
        },
        "key_agreement": key_agreement(verification_sample(entries)),
    }
