"""``glm_universal.runtime.reports.lattice_geometry``
-- the subjects the lattice and algebra modules compute.

Reports read off the geometric half of :mod:`glm_universal.reasoning`.

The ``2A`` algebra and its fusion spectrum, the six-facet partition, the
2-adic Monster stack, the multiresolution fibration, the deep-hole walk,
the ``24 -> 32 -> 48`` ladder, the large-alphabet sigma loop over a Leech
shell, and the Walsh--Hadamard decoder.

Every method here is a solver for one ``report <subject>`` query.  They are
mixed into :class:`glm_universal.runtime.session.GeometricSession`,
which is where ``self`` comes from: the loaded registers, the concept index
and the shared helpers.  Splitting them out of the session keeps each family
beside a docstring that says which sub-package computes it, and keeps the
dispatcher readable as a dispatcher.
"""
from __future__ import annotations

from ...reasoning import deep_holes as dhl
from ...reasoning import facets as fa
from ...reasoning import fwht_decode as fdc
from ...reasoning import higher_lattices as hlt
from ...reasoning import llvq_table as llt
from ...reasoning import monster_stack as msk
from ...reasoning import multires as mrs
from ...reasoning import product as pr
from ...reasoning import shell_sigma as shs

from ..payload import noise_payload
from ..parser import Query
from ..solution import Solution, Step, q


class LatticeGeometryReports:
    """The subjects the lattice and algebra modules compute.

    A mixin of :class:`~glm_universal.runtime.session.GeometricSession`;
    it holds no state of its own.
    """

    def _report_subalgebra(self, query: Query) -> Solution:
        """Wires pr.two_a_closure_report — 2A subalgebra closure facts."""
        report = pr.two_a_closure_report()
        steps = [
            Step("two_a_closure_report",
                 f"The 2A subalgebra generated by a sampled 2A pair is "
                 f"checked for: closure in three dimensions, "
                 f"commutativity, non-associativity (with an explicit "
                 f"witness), and the Gram matrix (1 on the diagonal, "
                 f"1/8 off it).",
                 f"two_a_closure_report = {report}"),
        ]
        expected = {k: str(v) for k, v in report.items()}
        return Solution(
            query=query, kind="report",
            answer=f"report subalgebra: {report}",
            steps=tuple(steps), expected=expected,
            script_spec={"template": "report_subalgebra", "args": {}},
            payload={"report": report})

    def _report_fusion(self, query: Query) -> Solution:
        """Wires pr.fusion_report -- the Ising fusion layer of the algebra.

        The adjoint action of an axis, its eigenspaces at the four Ising
        eigenvalues, and the two Miyamoto involutions built from them were
        implemented but unreachable from a query.  This subject recomputes
        all of it and states what the numbers mean.
        """
        report = pr.fusion_report()
        dims = report["expected_eigenspace_dimensions"]
        first = report["records"][0]["axes"][0]

        steps = [
            Step("adjoint action",
                 f"An axis acts on its own subalgebra by multiplication: "
                 f"x -> a . x.  In the three axes as a basis that is a "
                 f"3x3 rational matrix, and its trace is the sum of the "
                 f"eigenvalues.  Across {report['axes_checked']} axes of "
                 f"{report['pairs_checked']} subalgebras the trace is "
                 f"always 5/4 = 1 + 0 + 1/4.",
                 f"adjoint(a_{first['label']}) = {first['adjoint']}, "
                 f"trace = {first['adjoint_trace']}, "
                 f"always 5/4: "
                 f"{report['all_adjoint_traces_five_quarters']}"),
            Step("fusion spectrum",
                 f"The Ising fusion rules allow an axis the eigenvalues "
                 f"{', '.join(report['ising_eigenvalues'])}.  The "
                 f"eigenspaces are searched for, not assumed: each is the "
                 f"exact kernel of ad_a - lambda, computed over the "
                 f"rationals.  Here 1, 0 and 1/4 each contribute one "
                 f"dimension and 1/32 contributes none, so the four "
                 f"eigenspaces span all three dimensions -- the algebra is "
                 f"of Majorana type with no twisted part.",
                 f"dimensions = {dims}, span: "
                 f"{report['all_eigenspaces_span']}, as predicted "
                 f"everywhere: {report['all_dimensions_as_predicted']}"),
            Step("Miyamoto involutions",
                 f"tau_a negates the 1/32-eigenspace and sigma_a the "
                 f"1/4-eigenspace.  Because the 1/32-part is zero here, "
                 f"tau_a comes out as the identity -- a derived fact, not "
                 f"an assumption -- and the nontrivial symmetry is carried "
                 f"by sigma_a, which fixes its own axis and exchanges the "
                 f"other two.  The permutation is read off the computed "
                 f"matrix.",
                 f"tau always identity: {report['tau_always_identity']}, "
                 f"sigma fixes a and swaps the others: "
                 f"{report['sigma_always_swaps']}, "
                 f"sigma(a_{first['label']}) permutation = "
                 f"{first['sigma_permutation']}"),
            Step("symmetry check",
                 f"Both maps are checked against the structure they are "
                 f"supposed to preserve: every product and every Griess "
                 f"inner product on the basis, and squaring back to the "
                 f"identity.",
                 f"automorphisms: {report['all_automorphisms']}, "
                 f"isometries: {report['all_isometries']}, "
                 f"involutions: {report['all_involutions']}"),
        ]

        expected = {
            "pairs_checked": str(report["pairs_checked"]),
            "axes_checked": str(report["axes_checked"]),
            "all_eigenspaces_span": str(report["all_eigenspaces_span"]),
            "all_dimensions_as_predicted": str(
                report["all_dimensions_as_predicted"]),
            "all_adjoint_traces_five_quarters": str(
                report["all_adjoint_traces_five_quarters"]),
            "tau_always_identity": str(report["tau_always_identity"]),
            "sigma_always_swaps": str(report["sigma_always_swaps"]),
            "all_automorphisms": str(report["all_automorphisms"]),
            "all_isometries": str(report["all_isometries"]),
            "all_involutions": str(report["all_involutions"]),
        }

        return Solution(
            query=query, kind="report",
            answer=f"report fusion: {report['axes_checked']} axes over "
                   f"{report['pairs_checked']} 2A subalgebras; eigenspace "
                   f"dimensions {dims} everywhere "
                   f"({report['all_dimensions_as_predicted']}); "
                   f"tau = identity {report['tau_always_identity']}, "
                   f"sigma swaps the other two axes "
                   f"{report['sigma_always_swaps']}; all automorphisms "
                   f"{report['all_automorphisms']}",
            steps=tuple(steps), expected=expected,
            script_spec={"template": "report_fusion", "args": {}},
            payload={"report": report})

    def _report_facets(self, query: Query) -> Solution:
        """Wires fa.facets_report -- the six-facet linear decomposition."""
        report = fa.facets_report()
        partition = report["partition"]
        linearity = report["linearity"]
        pythagoras = report["pythagoras"]
        index = report["index_by_facet"]

        steps = [
            Step("partition",
                 f"The 24 coordinates are cut into {partition['facets']} "
                 f"named facets -- {', '.join(report['order'])} -- which "
                 f"cover all 24 and overlap nowhere.",
                 f"sizes = {partition['sizes']}, "
                 f"is_partition = {partition['is_partition']}"),
            Step("strict linearity",
                 f"Each facet projection was checked on "
                 f"{linearity['checked_carriers']} carriers to be additive, "
                 f"homogeneous, idempotent, mutually orthogonal and complete "
                 f"-- so the decomposition is an orthogonal direct sum, not "
                 f"a heuristic tagging.",
                 f"strictly_linear = {linearity['strictly_linear']}"),
            Step("pythagoras",
                 f"Because the projections are orthogonal, squared distance "
                 f"splits exactly across the facets; this was checked on "
                 f"{pythagoras['checked_pairs']} pairs.",
                 f"additive = {pythagoras['additive']}, "
                 f"failures = {pythagoras['failures']}"),
            Step("lattice index per facet",
                 f"No facet is lattice-autonomous: the index of the "
                 f"intersection in the projection is "
                 f"{index['dimension']} for dimension, {index['context']} "
                 f"for context and 8 for each one-dimensional facet, so a "
                 f"facet reading always loses lattice information.",
                 f"index = {index}, "
                 f"autonomous = {report['autonomous_facets']}"),
        ]
        expected = {
            "facets": str(partition["facets"]),
            "total": str(partition["total"]),
            "is_partition": str(partition["is_partition"]),
            "strictly_linear": str(linearity["strictly_linear"]),
            "pythagoras_additive": str(pythagoras["additive"]),
            "autonomous_facets": str(list(report["autonomous_facets"])),
        }
        for name in report["order"]:
            expected[f"size_{name}"] = str(partition["sizes"][name])
            expected[f"index_{name}"] = str(index[name])
        return Solution(
            query=query, kind="report",
            answer=f"report facets: {partition['facets']} facets partition "
                   f"the 24 coordinates, the projections are strictly linear "
                   f"and orthogonal, and no facet is lattice-autonomous "
                   f"(indices {index})",
            steps=tuple(steps), expected=expected,
            script_spec={"template": "report_facets", "args": {}},
            payload={"report": report})

    def _report_monster_stack(self, query: Query) -> Solution:
        """Wires msk.monster_stack_report -- ten planes and the 2A product."""
        report = msk.monster_stack_report()
        census = report["position_census"]
        repaired = report["position_census_pair_repaired"]
        loss = report["shortcut_loss"]
        assoc = report["associativity"]

        steps = [
            Step("ten planes",
                 f"A carrier is written as a stack of {report['depth']} "
                 f"2-adic digit planes, each read as a class of "
                 f"Lambda / 2 Lambda and repaired to the nearest type-2 "
                 f"class, with exact lattice distance breaking Hamming ties.",
                 f"depth = {report['depth']}, basis = {report['basis']}"),
            Step("the exact Sakuma product",
                 f"Where both planes carry a 2A axis the product is the "
                 f"Norton-Sakuma relation a . b = (1/8)(a + b - a_rho), not "
                 f"an XOR of labels.  {census['defined']} of "
                 f"{census['planes']} planes compose strictly, and "
                 f"{repaired['defined']} with pair-aware repair.",
                 f"positions = {census['by_position']}, "
                 f"pair-repaired = {repaired['by_position']}"),
            Step("what the XOR shortcut discarded",
                 f"The shortcut kept only the third-axis label: it dropped "
                 f"{loss['terms_discarded_by_xor']} of the product's "
                 f"{loss['sakuma_term_count']} terms and the coefficient "
                 f"{loss['coefficient_on_xor_term']} on the one it kept, "
                 f"changing the norm from {loss['sakuma_norm2']} to "
                 f"{loss['shortcut_norm2']}.",
                 f"u = {loss['u']}, v = {loss['v']}, "
                 f"difference norm^2 = {loss['difference_norm2']}"),
            Step("non-associativity is the point",
                 f"On classes {assoc['classes']} the algebra gives "
                 f"(a.b).c = {assoc['left_terms']} and "
                 f"a.(b.c) = {assoc['right_terms']}, which differ, while the "
                 f"XOR shortcut is associative.  A pipeline that composed "
                 f"addresses by XOR was working in a quotient where the "
                 f"Monster's product does not live.",
                 f"associative = {assoc['associative']}, "
                 f"xor_associative = {assoc['xor_associative']}, "
                 f"difference norm^2 = {assoc['difference_norm2']}"),
        ]
        expected = {
            "depth": str(report["depth"]),
            "planes": str(census["planes"]),
            "defined_strict": str(census["defined"]),
            "defined_pair_repaired": str(repaired["defined"]),
            "sakuma_term_count": str(loss["sakuma_term_count"]),
            "terms_discarded_by_xor": str(loss["terms_discarded_by_xor"]),
            "xor_is_the_third_axis_label":
                str(loss["xor_is_the_third_axis_label"]),
            "sakuma_norm2": str(loss["sakuma_norm2"]),
            "shortcut_norm2": str(loss["shortcut_norm2"]),
            "associative": str(assoc["associative"]),
            "xor_associative": str(assoc["xor_associative"]),
            "commutative": str(assoc["commutative"]),
            "associativity_difference_norm2": str(assoc["difference_norm2"]),
        }
        return Solution(
            query=query, kind="report",
            answer=f"report monster stack: depth {report['depth']}, "
                   f"{census['defined']} planes compose strictly and "
                   f"{repaired['defined']} with pair repair; the Sakuma "
                   f"product is non-associative where the retired XOR "
                   f"shortcut was associative",
            steps=tuple(steps), expected=expected,
            script_spec={"template": "report_monster_stack", "args": {}},
            payload={"report": report})

    def _report_multiresolution(self, query: Query) -> Solution:
        """Wires mrs.multires_report -- bit-level and grid-level addressing."""
        report = mrs.multires_report()
        fib = report["fibration"]
        columns = report["columns"]
        invariance = report["scale_invariance"]["rows"]
        collision = report["census_collision"]
        indices = sorted({col["index"] for col in columns})
        sig_invariant = all(row["signature_invariant"] for row in invariance)
        addr_invariant = any(row["address_invariant"] for row in invariance)

        steps = [
            Step("bit-level micro-addressing",
                 f"Each of the {fib['columns']} values a MOG column can take "
                 f"is mapped to a GF(4) x Z_4 fibre coordinate.  The map is "
                 f"a bijection with round trip, and its kernel "
                 f"{fib['kernel']} is elementary abelian rather than cyclic "
                 f"of order 4, so the Z_4 coordinate indexes a fibre as a "
                 f"set of residues.",
                 f"bijective = {fib['bijective']}, "
                 f"round_trip = {fib['round_trip']}, "
                 f"kernel = {fib['kernel']}"),
            Step("local sub-lattices",
                 f"Each column carries a rank-4 local Leech sub-lattice.  "
                 f"The index of the supported sub-lattice in the projection "
                 f"is {indices} for every column, so a bit-level reading is "
                 f"a strictly coarser view of the lattice.",
                 f"columns = {len(columns)}, indices = {indices}"),
            Step("grid-level macro-addressing",
                 f"A whole 2D grid is carried into the 24 coordinates and "
                 f"read as a ten-plane Monster address, so a configuration "
                 f"and a single bit are addressed in the same space at two "
                 f"resolutions.",
                 f"grid = {report['grid']}, "
                 f"census = {list(report['grid_census'])}"),
            Step("scale invariance",
                 f"Across the sampled grids and scale factors the signature "
                 f"is invariant ({sig_invariant}) while the Monster address "
                 f"is not ({addr_invariant}) -- the coarse reading survives "
                 f"rescaling and the fine one does not, which is the loss "
                 f"the two levels are there to measure.  A census collision "
                 f"exhibits it directly: {collision['first']} and "
                 f"{collision['second']} share a census.",
                 f"signature invariant = {sig_invariant}, "
                 f"address invariant = {addr_invariant}, "
                 f"collision found = {collision['found']}"),
        ]
        expected = {
            "fibre_columns": str(fib["columns"]),
            "fibre_bijective": str(fib["bijective"]),
            "fibre_round_trip": str(fib["round_trip"]),
            "fibre_kernel": str(list(fib["kernel"])),
            "fibre_kernel_is_cyclic_of_order_4":
                str(fib["kernel_is_cyclic_of_order_4"]),
            "column_indices": str(indices),
            "signature_invariant_everywhere": str(sig_invariant),
            "address_invariant_anywhere": str(addr_invariant),
            "census_collision_found": str(collision["found"]),
            "census_collision_carriers_equal":
                str(collision["carriers_equal"]),
        }
        return Solution(
            query=query, kind="report",
            answer=f"report multiresolution: the F_2^4 -> GF(4) x Z_4 fibre "
                   f"map is a bijection with kernel {list(fib['kernel'])}, "
                   f"every column sub-lattice has index {indices}, and the "
                   f"grid signature is scale-invariant where the ten-plane "
                   f"address is not",
            steps=tuple(steps), expected=expected,
            script_spec={"template": "report_multiresolution", "args": {}},
            payload={"report": report})

    def _report_deep_holes(self, query: Query) -> Solution:
        """Wires deep_holes.deep_holes_report -- Niemeier types, no table.

        The classification of a carrier by its nearest Niemeier type is
        normally a Voronoi-cell problem with 196,560 facets.  Here it is a
        process: walk to a hole, climb to the covering radius, read the
        vertices off the modulator's trajectory, and certify the reading.
        Nothing about the 23 types is stored except the catalogue, which is
        itself derived.
        """
        report = dhl.deep_holes_report(walks=3)
        census = report["census"]
        catalogue = report["catalogue_size"]
        exhibited = census["types_exhibited"]

        steps = [
            Step("the catalogue is derived, not listed",
                 f"The {catalogue} Niemeier root systems are enumerated as "
                 f"the unions of ADE components that share one Coxeter "
                 f"number and total rank 24, from the component formulas "
                 f"alone.  They are what a hole's diagram is checked "
                 f"against.",
                 f"catalogue size = {catalogue}"),
            Step("a hole is reached by running, not looked up",
                 report["method"],
                 f"walks run = {census['walks_run']}, reaching the covering "
                 f"radius = {census['walks_reaching_a_deep_hole']}, "
                 f"stalling at a shallow hole = "
                 f"{census['walks_stalling_at_a_shallow_hole']}"),
            Step("the reading is certified",
                 report["certificate"],
                 f"types named = {len(exhibited)}, all certified = "
                 f"{census['every_named_type_certified']}"),
            Step("what it settles",
                 f"This run exhibited "
                 f"{census['types_exhibited_count']} of the {catalogue} "
                 f"types: {', '.join(exhibited) if exhibited else 'none'}.  "
                 f"Each was certified complete by the marked-barycentre "
                 f"identity.",
                 f"exhibited = {census['types_exhibited_count']}/"
                 f"{catalogue}"),
            Step("what it leaves undetermined",
                 report["limits"] + "  " + census["honest_statement"],
                 f"shortfall = {census['shortfall']} of {catalogue}, "
                 f"census complete = {census['census_complete']}"),
        ]
        expected = {
            "catalogue_size": str(catalogue),
            "covering_radius2": str(report["covering_radius2"]),
            "walks_run": str(census["walks_run"]),
            "every_named_type_certified":
                str(census["every_named_type_certified"]),
            "census_complete": str(census["census_complete"]),
        }
        return Solution(
            query=query, kind="report",
            answer=f"report deep holes: a carrier is classified by walking "
                   f"to the hole it sits in and certifying what the walk "
                   f"found, never by enumerating the 196,560 facets or "
                   f"storing the {catalogue} hole centres; this run reached "
                   f"the covering radius on "
                   f"{census['walks_reaching_a_deep_hole']} of "
                   f"{census['walks_run']} walks and exhibited "
                   f"{census['types_exhibited_count']} of the {catalogue} "
                   f"Niemeier types, every one certified complete, with a "
                   f"shortfall of {census['shortfall']} that is reported "
                   f"as a shortfall",
            steps=tuple(steps), expected=expected,
            script_spec={"template": "report_deep_holes", "args": {}},
            payload={"report": report})

    def _report_lattices(self, query: Query) -> Solution:
        """Wires hlt.higher_lattices_report -- the 24 -> 32 -> 48 ladder.

        The spatial layer stops at 24 dimensions.  This is the next two rungs:
        the 32-dimensional Barnes-Wall lattice, built by Construction D over a
        nested pair of Reed-Muller codes and carrying a genuine three-
        resolution address, and the 48-dimensional extremal lattice, built
        over the ternary Pless symmetry code and reached by a neighbour step
        whose two candidates are separated by a parity census.
        """
        report = hlt.higher_lattices_report()
        ladder = report["ladder"]
        rows = ladder["rows"]
        leech = next(r for r in rows if r["dimension"] == 24)
        bw = next(r for r in rows if r["dimension"] == 32)
        top = next(r for r in rows if r["dimension"] == 48)
        d32 = report["dimension_32"]
        codes = d32["codes"]
        det = d32["determinant"]
        kissing = d32["kissing"]
        address = d32["address"]
        trip = d32["round_trip"]
        d48 = report["dimension_48"]

        steps = [
            Step("the ladder, and what each rung is worth",
                 f"An even unimodular lattice in dimension n cannot have "
                 f"minimum above 2 + 2*floor(n/24), and the ones that reach "
                 f"it are the extremal ones.  Centre density is "
                 f"(minimum/4)^(n/2) for a unimodular lattice, so the climb "
                 f"from 24 to 48 is not incremental: the 48-dimensional rung "
                 f"packs {q(ladder['density_gain_over_leech'][48])} times as "
                 f"densely per unit cell as the Leech lattice does.",
                 f"24: minimum {leech['minimum']}, density "
                 f"{q(leech['centre_density'])}; 32: minimum "
                 f"{bw['minimum']}, density {q(bw['centre_density'])}; 48: "
                 f"minimum {top['minimum']}, density "
                 f"{q(top['centre_density'])}; all extremal "
                 f"{ladder['all_extremal']}"),
            Step("32 dimensions: two codes, three cases",
                 f"Construction A over a binary code always keeps 2 e_i and "
                 f"so stops at minimum 2.  Construction D over a *nested* "
                 f"pair does not: the outer code makes a vector visible at "
                 f"the coarse resolution long, the inner code makes one "
                 f"visible at the middle resolution long, and a vector "
                 f"visible at neither is a multiple of 4.  Both code "
                 f"parameters are recomputed here, and the duality of the "
                 f"pair is what makes the lattice even.",
                 f"outer [{codes['outer']['length']}, "
                 f"{codes['outer']['dimension']}, "
                 f"{codes['outer']['minimum_weight']}], inner "
                 f"[{codes['inner']['length']}, "
                 f"{codes['inner']['dimension']}, "
                 f"{codes['inner']['minimum_weight']}], dual pair "
                 f"{address['dual_pair']}, even {det['even']}, Gram "
                 f"determinant 2^64 {det['gram_determinant_is_2_to_64']}"),
            Step("the kissing census",
                 f"The 146,880 minimal vectors split into exactly three "
                 f"shapes, one contributed by each level of the "
                 f"construction, and the three counts are generated rather "
                 f"than quoted.",
                 "; ".join(f"{shape} {count}"
                           for shape, count in kissing["counts"].items())
                 + f"; total {kissing['total']}"),
            Step("what the 32 buys: an address at three resolutions",
                 f"This is the thing the 24-dimensional layer does not have. "
                 f"A Leech address is flat -- the mod 2 / mod 4 / mod 8 "
                 f"sieve is a membership test, not a decomposition.  "
                 f"Construction D's three levels are nested lattices, so the "
                 f"coarse part of an address is usable on its own and "
                 f"refinable later: truncating an address lands in the "
                 f"coarser lattice, exactly.",
                 f"levels {list(address['levels'])}, indices "
                 f"{list(address['step_indices'])} (total "
                 f"{address['total_index']}); round trip "
                 f"{trip['all_round_trip']} on {trip['probes']} points, "
                 f"truncations still in the lattice "
                 f"{trip['all_levels_usable']}"),
            Step("48 dimensions: the binary route runs out",
                 f"There is a binary [48, 24, 12] code -- the extended "
                 f"quadratic residue code -- and it is not enough: "
                 f"Construction A over any binary code contains 2 e_i, of "
                 f"norm {d48['binary_route_stops_at']}.  Over F_3 the "
                 f"shortest such vector is 3 e_i, of norm 3, and the "
                 f"construction has room.  The code is the Pless symmetry "
                 f"code, self-dual with minimum weight "
                 f"{d48['ternary_code']['minimum_weight']}.",
                 f"{d48['ternary_code']['name']}: self-dual "
                 f"{d48['ternary_code']['self_dual']}, minimum weight "
                 f"{d48['ternary_code']['minimum_weight']}; Construction A "
                 f"minimum {q(d48['construction_a_minimum'])} (odd), even "
                 f"sublattice minimum "
                 f"{q(d48['even_sublattice_minimum'])}"),
            Step("the neighbour step, and the census that decides it",
                 f"The even sublattice has determinant 4, so it has two even "
                 f"unimodular neighbours.  Both glue on a coset of "
                 f"half-odd-integer vectors, whose norm is at least 4 with "
                 f"equality exactly at the full-weight codewords of the "
                 f"right parity.  There are 96 full-weight codewords -- "
                 f"cross-checked against A_48 of the extremal weight "
                 f"enumerator -- and every one of them has an even number of "
                 f"2s.  So they all land in the first neighbour and none in "
                 f"the second, which is therefore extremal.",
                 f"full-weight codewords "
                 f"{d48['full_weight_census']['total']} (even parity "
                 f"{d48['full_weight_census']['even_number_of_twos']}, odd "
                 f"{d48['full_weight_census']['odd_number_of_twos']}); N1 "
                 f"minimum {q(d48['N1_minimum'])}, N2 minimum "
                 f"{q(d48['N2_minimum'])}, extremal {d48['extremal']}"),
        ]

        expected = {
            "all_extremal": str(ladder["all_extremal"]),
            "density_24": q(leech["centre_density"]),
            "density_32": q(bw["centre_density"]),
            "density_48": q(top["centre_density"]),
            "minimum_32": str(bw["minimum"]),
            "minimum_48": str(top["minimum"]),
            "outer_minimum_weight": str(codes["outer"]["minimum_weight"]),
            "inner_minimum_weight": str(codes["inner"]["minimum_weight"]),
            "dual_pair": str(address["dual_pair"]),
            "even_32": str(det["even"]),
            "gram_is_2_to_64": str(det["gram_determinant_is_2_to_64"]),
            "kissing_32": str(kissing["total"]),
            "address_total_index": str(address["total_index"]),
            "round_trip": str(trip["all_round_trip"]),
            "levels_usable": str(trip["all_levels_usable"]),
            "binary_route_minimum": str(d48["binary_route_stops_at"]),
            "ternary_self_dual": str(d48["ternary_code"]["self_dual"]),
            "ternary_minimum_weight":
                str(d48["ternary_code"]["minimum_weight"]),
            "even_sublattice_minimum": q(d48["even_sublattice_minimum"]),
            "full_weight_total": str(d48["full_weight_census"]["total"]),
            "full_weight_even":
                str(d48["full_weight_census"]["even_number_of_twos"]),
            "full_weight_odd":
                str(d48["full_weight_census"]["odd_number_of_twos"]),
            "N1_minimum": q(d48["N1_minimum"]),
            "N2_minimum": q(d48["N2_minimum"]),
            "N2_extremal": str(d48["extremal"]),
        }
        for shape, count in kissing["counts"].items():
            expected["kissing_" + shape] = str(count)

        return Solution(
            query=query, kind="report",
            answer=f"report lattices: the ladder past the Leech lattice runs "
                   f"24 -> 32 -> 48 with minima {leech['minimum']}, "
                   f"{bw['minimum']}, {top['minimum']} and centre densities "
                   f"{q(leech['centre_density'])}, "
                   f"{q(bw['centre_density'])}, "
                   f"{q(top['centre_density'])}; the 32-dimensional rung is "
                   f"Construction D over a dual pair of Reed-Muller codes "
                   f"with {kissing['total']} minimal vectors and a genuine "
                   f"three-resolution address (indices "
                   f"{list(address['step_indices'])}); the 48-dimensional "
                   f"rung needs F_3, because a binary code stops at minimum "
                   f"{d48['binary_route_stops_at']}, and the extremal one of "
                   f"the two neighbours is picked out by the fact that all "
                   f"{d48['full_weight_census']['total']} full-weight "
                   f"codewords have an even number of 2s",
            steps=tuple(steps), expected=expected,
            script_spec={"template": "report_lattices", "args": {}},
            payload={"report": noise_payload(report)})

    def _report_shells(self, query: Query) -> Solution:
        """Wires shs.shell_sigma_report -- delta-sigma on the Leech shells.

        The delta-sigma family in ``noise_lab`` emits from a small alphabet.
        This is the same loop with the alphabet enlarged to a shell of the
        Leech lattice, and then to the whole lattice, plus the Gibbs-style
        rule that replaces the hard snap by a temperature-weighted choice.
        """
        report = shs.shell_sigma_report()
        shell = report["shell"]
        ball = report["inner_ball"]
        inside = report["inside"]
        run = inside["run"]
        outside = report["outside"]
        lattice = report["lattice"]
        gibbs = report["gibbs"]
        uniform = gibbs["rows"][0]
        cold = gibbs["rows"][-1]

        steps = [
            Step("the support function of a shell, in closed form",
                 f"The matched rule needs max <x, v> over the "
                 f"{shell['size']} minimal vectors, exactly, at every tick. "
                 f"Enumerating them is possible and wasteful: the shell is "
                 f"three shapes, and each one is maximised in closed form -- "
                 f"a sort for the pairs, 759 octads with a sign-parity "
                 f"repair, and one Walsh-Hadamard transform for the 4,096 "
                 f"Golay cosets.  The shortcut is checked against a full "
                 f"sweep of the shell.",
                 f"shapes {list(shell['support_shapes'])}, shell size "
                 f"{shell['size']}, norm^2 {shell['norm2']}"),
            Step("inside the hull: the accumulator stays put",
                 f"A shell covers nothing, so the usual argument -- the "
                 f"accumulator never leaves the quantiser's covering ball -- "
                 f"is unavailable.  What replaces it is a margin: if the "
                 f"target sits strictly inside the hull of the shell, the "
                 f"accumulator stays in a ball of radius D^2/(2mu) + D and "
                 f"the mean tracks at B/N.  The run bears it out: doubling "
                 f"the tick count quartered the squared error, which is "
                 f"exactly 1/N on the error itself.",
                 f"ticks {run['ticks']}, max |state|^2 "
                 f"{q(run['max_state_norm2'])}, error^2 "
                 f"{q(run['error_norm2'])} against "
                 f"{q(inside['half_run_error_norm2'])} at half the ticks "
                 f"(fell {inside['error_fell']}); margin hypothesis held "
                 f"{inside['margin_hypothesis_held']}, all emissions on the "
                 f"shell {run['all_on_shell']}"),
            Step("a ball that is certified, not searched",
                 f"The pair shape alone gives h(x) >= 4 max|x_i| >= "
                 f"4|x|/sqrt(24), so every target with 3|t|^2 < 2 is "
                 f"strictly inside the hull with a computable margin.  The "
                 f"bound uses one of three shapes and the crudest coordinate "
                 f"estimate, so it is exact and deliberately not tight.",
                 f"radius^2 {q(ball['radius_squared'])}, criterion "
                 f"{ball['criterion']}, tight {ball['tight']}"),
            Step("outside the hull: a one-line certificate",
                 f"The largest first coordinate anywhere on the shell is 4, "
                 f"so h(e_0) = {q(outside['support_in_direction'])} and a "
                 f"target with first coordinate "
                 f"{q(outside['target_in_direction'])} is separated from the "
                 f"hull by that functional.  No rule emitting shell points "
                 f"can approach it, and the run shows the accumulator "
                 f"growing at exactly the gap per tick.",
                 f"h(e_0) = {q(outside['support_in_direction'])}, target "
                 f"{q(outside['target_in_direction'])}, separated "
                 f"{outside['separated']}, gap {q(outside['gap'])}; final "
                 f"|state|^2 {q(outside['run']['final_state_norm2'])} after "
                 f"{outside['run']['ticks']} ticks"),
            Step("the whole lattice: the wall comes down",
                 f"The same unreachable target, with the alphabet widened "
                 f"from the shell to the whole Leech lattice and the "
                 f"quantiser the exact nearest-point decoder.  A lattice "
                 f"covers space, so the accumulator is trapped inside the "
                 f"covering ball whatever the target is, and the mean tracks "
                 f"at rho/N.",
                 f"max |state|^2 {q(lattice['max_state_norm2'])} <= "
                 f"{lattice['covering_radius2']} "
                 f"({lattice['within_covering_radius']}); error^2 "
                 f"{q(lattice['error_norm2'])} <= "
                 f"{q(lattice['error_bound_norm2'])} "
                 f"({lattice['within_bound']})"),
            Step("the Gibbs-style rule, realised without randomness",
                 f"The hard snap is replaced by a temperature-weighted "
                 f"choice among the {gibbs['candidate_count']} shell points "
                 f"nearest a query, with energies the exact squared "
                 f"distances.  A machine that constructs no floats and draws "
                 f"no samples cannot sample an ensemble, so the ensemble is "
                 f"realised by the same greedy error feedback the modulators "
                 f"use: the visit frequencies converge to the Gibbs weights "
                 f"at (m-1)/N.  At t = 1 the ensemble is uniform; as t rises "
                 f"it collapses onto the nearest point.",
                 f"energies {list(gibbs['energies'])}; t = {uniform['t']} "
                 f"weights all {q(uniform['weights'][0])}, frequency error "
                 f"{q(uniform['max_frequency_error'])}; t = {cold['t']} "
                 f"weight on the nearest {q(cold['weights'][0])}, frequency "
                 f"error {q(cold['max_frequency_error'])} <= "
                 f"{q(cold['bound'])} ({cold['within_bound']})"),
        ]

        expected = {
            "shell_size": str(shell["size"]),
            "shell_norm2": str(shell["norm2"]),
            "inner_ball_radius2": q(ball["radius_squared"]),
            "inside_ticks": str(run["ticks"]),
            "inside_error2": q(run["error_norm2"]),
            "inside_half_error2": q(inside["half_run_error_norm2"]),
            "inside_error_fell": str(inside["error_fell"]),
            "inside_max_state2": q(run["max_state_norm2"]),
            "inside_margin_held": str(inside["margin_hypothesis_held"]),
            "inside_on_shell": str(run["all_on_shell"]),
            "outside_support": q(outside["support_in_direction"]),
            "outside_target": q(outside["target_in_direction"]),
            "outside_separated": str(outside["separated"]),
            "outside_gap": q(outside["gap"]),
            "outside_final_state2": q(outside["run"]["final_state_norm2"]),
            "lattice_max_state2": q(lattice["max_state_norm2"]),
            "lattice_within_covering": str(lattice["within_covering_radius"]),
            "lattice_error2": q(lattice["error_norm2"]),
            "lattice_bound2": q(lattice["error_bound_norm2"]),
            "lattice_within_bound": str(lattice["within_bound"]),
            "gibbs_candidates": str(gibbs["candidate_count"]),
            "gibbs_energies": ",".join(str(e) for e in gibbs["energies"]),
            "gibbs_uniform_error": q(uniform["max_frequency_error"]),
            "gibbs_cold_weight": q(cold["weights"][0]),
            "gibbs_cold_error": q(cold["max_frequency_error"]),
            "gibbs_bound": q(cold["bound"]),
            "gibbs_within_bound": str(cold["within_bound"]),
        }

        return Solution(
            query=query, kind="report",
            answer=f"report shells: the shell's support function is computed "
                   f"in closed form over three shapes rather than by "
                   f"enumerating {shell['size']} vectors; a target inside "
                   f"the hull is tracked with the accumulator bounded by "
                   f"|state|^2 <= {q(run['max_state_norm2'])} and the "
                   f"squared error falling from "
                   f"{q(inside['half_run_error_norm2'])} to "
                   f"{q(run['error_norm2'])} when the ticks double; a target "
                   f"with first coordinate "
                   f"{q(outside['target_in_direction'])} is separated from "
                   f"the hull by h(e_0) = "
                   f"{q(outside['support_in_direction'])} and is "
                   f"unreachable; widening the alphabet to the whole lattice "
                   f"reaches it with |state|^2 <= "
                   f"{lattice['covering_radius2']}; and the Gibbs rule is "
                   f"realised deterministically to within "
                   f"{q(cold['max_frequency_error'])} of its weights, "
                   f"against the proved bound {q(cold['bound'])}",
            steps=tuple(steps), expected=expected,
            script_spec={"template": "report_shells", "args": {}},
            payload={"report": noise_payload(report)})

    def _report_llvq(self, query: Query) -> Solution:
        """Wires llvq_table -- the LLVQ class table on the quantiser's path.

        Three claims, each measured here: that the 128 MOG classes *are* the
        Golay code, that a class minimum is a six-term min-sum with one
        parity repair, and that decoding through the table returns exactly
        what the 4,096-word scan returns while opening a couple of classes.
        """
        report = llt.llvq_table_report()
        shape = report["characterisation"]
        cost = report["cost"]
        agree = report["agreement"]
        corpus = llt.corpus_report(limit=150)

        steps = [
            Step("the code, as a table",
                 f"Under the MOG alignment a Golay codeword is exactly a "
                 f"word whose six GF(4) column labels form a hexacode word, "
                 f"whose six column parities agree, and whose top row "
                 f"carries that same parity.  All three were checked over "
                 f"all {shape['codewords']} codewords, and the classes were "
                 f"counted: {report['hexacode_words']} hexacode words times "
                 f"2 parities is {shape['classes']} classes of "
                 f"{report['class_size']}, which is "
                 f"{shape['classes_times_size']} with nothing left over -- "
                 f"so the conditions characterise the code rather than "
                 f"merely holding on it.  Inside a column "
                 f"(label, parity, top bit) fixes the pattern, which is the "
                 f"whole of the lookup table: {report['table_entries']} "
                 f"entries.",
                 f"shadow failures {shape['shadow_failures']}, column "
                 f"parity failures {shape['column_parity_failures']}, top "
                 f"row failures {shape['top_row_parity_failures']}, rebuild "
                 f"failures {shape['rebuild_failures']}, accounts for the "
                 f"code {shape['accounts_for_the_code']}"),
            Step("a class minimum is six comparisons",
                 f"Within a class the only freedom is one top bit per "
                 f"column under a parity constraint, so the least cost is "
                 f"the cheaper pattern in every column, repaired -- when "
                 f"the parity comes out wrong -- by the smallest of the six "
                 f"differences.  That is `RequestProject/GLM/LLVQTable.lean`"
                 f"'s `isLeast_cost_of_parity_eq` and "
                 f"`isLeast_cost_of_parity_ne`, and `card_parity_class` is "
                 f"why a class holds {report['class_size']} words.",
                 f"classes {shape['classes']}, class size "
                 f"{report['class_size']}, table entries "
                 f"{report['table_entries']}"),
            Step("the scan, replaced and still agreed with",
                 f"The decoder visits classes in increasing minimum and "
                 f"opens one only while its minimum does not exceed the "
                 f"best total so far; the repair the reference applies is "
                 f"nonnegative, so an unopened class holds nothing better "
                 f"(`isLeast_of_bounded_search`).  Against the "
                 f"{cost['reference_words_per_call']} words the scan forms "
                 f"a cost for on every call, the table formed "
                 f"{q(cost['table_words_per_call'])} on average over "
                 f"{cost['calls']} deterministic vectors, opening "
                 f"{q(cost['table_classes_per_call'])} of "
                 f"{cost['classes_available_per_call']} classes, and its "
                 f"worst call formed {cost['worst_words_in_a_call']}.",
                 f"words ratio {q(cost['words_ratio'])}, additions "
                 f"{q(cost['table_additions_per_call'])} against "
                 f"{cost['reference_additions_per_call']} (ratio "
                 f"{q(cost['additions_ratio'])})"),
            Step("the same answers, on the hot path it was built for",
                 f"Agreement is point for point -- point, squared distance, "
                 f"Leech class, norm and both flags -- over the "
                 f"deterministic sweep, the register carriers and the "
                 f"boundary cases: {agree['checked']} vectors, "
                 f"{agree['mismatches']} mismatches.  The address book is "
                 f"what the quantiser is the hot path of, so the first "
                 f"{corpus['declarations']} declarations of the Lean "
                 f"corpus were decoded both ways as well.",
                 f"agreement {agree['checked']} checked, "
                 f"{agree['mismatches']} mismatched; corpus "
                 f"{corpus['addresses_unchanged']}/"
                 f"{corpus['declarations']} unchanged "
                 f"({corpus['all_unchanged']}), of "
                 f"{corpus['corpus_declarations']} declarations"),
        ]

        expected = {
            "codewords": str(shape["codewords"]),
            "classes": str(shape["classes"]),
            "class_size": str(report["class_size"]),
            "table_entries": str(report["table_entries"]),
            "hexacode_words": str(report["hexacode_words"]),
            "accounts_for_the_code": str(shape["accounts_for_the_code"]),
            "shadow_failures": str(shape["shadow_failures"]),
            "rebuild_failures": str(shape["rebuild_failures"]),
            "reference_words_per_call": str(cost["reference_words_per_call"]),
            "reference_additions_per_call":
                str(cost["reference_additions_per_call"]),
            "agreement_checked": str(agree["checked"]),
            "agreement_mismatches": str(agree["mismatches"]),
            "corpus_declarations": str(corpus["declarations"]),
            "corpus_unchanged": str(corpus["addresses_unchanged"]),
            "corpus_all_unchanged": str(corpus["all_unchanged"]),
        }

        return Solution(
            query=query, kind="report",
            answer=f"report llvq: the {shape['codewords']} Golay codewords "
                   f"are {shape['classes']} classes of "
                   f"{report['class_size']} -- a hexacode word and a parity "
                   f"-- read out of a {report['table_entries']}-entry column "
                   f"table, so the Leech quantiser's search becomes 128 "
                   f"six-term min-sums and a bound: "
                   f"{q(cost['table_words_per_call'])} codeword costs per "
                   f"call against the scan's "
                   f"{cost['reference_words_per_call']}, with "
                   f"{agree['mismatches']} mismatches over "
                   f"{agree['checked']} vectors and "
                   f"{corpus['addresses_unchanged']} of "
                   f"{corpus['declarations']} Lean addresses unchanged",
            steps=tuple(steps), expected=expected,
            script_spec={"template": "report_llvq", "args": {}},
            payload={"report": noise_payload(report)})

    def _report_transform_decoder(self, query: Query) -> Solution:
        """Wires fwht_decode.fwht_decode_report -- the transform and the tier.

        Two claims, both measured here rather than quoted: that the 4,096
        Golay coset costs are one Walsh-Hadamard transform, and that the
        constant-time lookup can prove its own answer -- sometimes.
        """
        report = fdc.fwht_decode_report()
        counts = report["operation_counts"]
        rates = report["certificate_rates"]
        agree = report["agreement"]
        ties = report["tie_sets"]
        flat = rates["regimes"][0]
        widest = rates["regimes"][-1]

        steps = [
            Step("the search is one transform",
                 f"Coordinate k of the codeword of message m is the parity "
                 f"of m against a fixed 12-bit generator column, so the "
                 f"{counts['codeword_count']} support sums the decoder "
                 f"minimises are the Walsh-Hadamard transform of a "
                 f"length-{counts['codeword_count']} array with only "
                 f"{counts['n']} nonzero entries.  The identity was checked "
                 f"on {agree['support_sums_checked']} sums and on "
                 f"{agree['column_identity_checks']} column parities.",
                 f"support-sum mismatches = {agree['support_sums_failures']}, "
                 f"column mismatches = {agree['column_identity_failures']}"),
            Step("what the transform costs, and what it buys",
                 f"Direct summation costs {counts['direct_adds']} additions "
                 f"(n * 2^(k-1)); the transform costs {counts['fwht_ops']} "
                 f"add/subtracts (2^k * k).  These are equal exactly when "
                 f"n = 2k, and for this code n = {counts['n']}, "
                 f"k = {counts['k']}.  The transform is therefore not a "
                 f"speed-up here; what it buys is the whole cost spectrum in "
                 f"one pass.",
                 f"direct = {counts['direct_adds']}, "
                 f"fwht = {counts['fwht_ops']}, "
                 f"ratio = {counts['ratio_direct_over_fwht']}, "
                 f"equal because n = 2k: "
                 f"{counts['equal_because_n_equals_2k']}"),
            Step("the exact decoder is reproduced, ties included",
                 f"The transform-driven nearest-Leech-point decoder was run "
                 f"against the existing complete decoder on "
                 f"{agree['lattice_points_checked']} rational targets -- "
                 f"point, distance, Leech class and 2A flag all compared -- "
                 f"and the argmin *set* was compared on "
                 f"{ties['cases']} soft-decision profiles, one of them "
                 f"engineered to be the six-fold covering-radius tie.",
                 f"lattice-point disagreements = "
                 f"{agree['lattice_point_failures']}, "
                 f"tie-set disagreements = {ties['failures']}, "
                 f"largest tie set = {ties['largest_tie_set']}, "
                 f"sextet case six-fold = {ties['sextet_case_is_sixfold']}"),
            Step("the O(1) lookup, with a certificate instead of a guess",
                 f"The constant-time route hard-decides the 24 signs, takes "
                 f"one syndrome, reads the coset leaders from the table, and "
                 f"then tries to *prove* its answer using the code's minimum "
                 f"distance {fdc.MIN_DISTANCE}: any other coset member "
                 f"differs by a codeword of weight at least 8, so it must pay "
                 f"for at least 8 - j coordinates outside the leader while "
                 f"recovering at most the j largest inside it.  When that "
                 f"inequality holds the fast answer is optimal, with proof.",
                 f"leaders per coset <= 6, magnitudes sorted once, "
                 f"nothing scales with the "
                 f"{counts['codeword_count']} codewords"),
            Step("how often it fires -- measured, per regime",
                 f"The rate is a statement about reliability spread, not "
                 f"about the code.  On a flat profile it fires "
                 f"{flat['certified']} times in {flat['samples']}; on "
                 f"magnitudes spread over a hundredfold band it fires "
                 f"{widest['certified']} in {widest['samples']}.  Every "
                 f"certified answer was re-checked against the exact "
                 f"transform, and "
                 f"{rates['certified_but_wrong']} were wrong.  Where the "
                 f"certificate declines, the exact transform is entered: the "
                 f"decoder is never wrong, only sometimes slow.",
                 " | ".join(f"{r['regime']}: {r['certified']}/{r['samples']}"
                            for r in rates["regimes"])),
        ]
        expected = {
            "direct_adds": str(counts["direct_adds"]),
            "fwht_ops": str(counts["fwht_ops"]),
            "equal_because_n_equals_2k":
                str(counts["equal_because_n_equals_2k"]),
            "column_identity_failures": str(agree["column_identity_failures"]),
            "support_sums_failures": str(agree["support_sums_failures"]),
            "lattice_point_failures": str(agree["lattice_point_failures"]),
            "all_agree": str(agree["all_agree"]),
            "tie_set_failures": str(ties["failures"]),
            "sextet_case_is_sixfold": str(ties["sextet_case_is_sixfold"]),
            "flat_profile_always_certifies":
                str(rates["flat_profile_always_certifies"]),
            "certified_but_wrong": str(rates["certified_but_wrong"]),
            "overall_certified_fraction":
                str(rates["overall_certified_fraction"]),
        }
        return Solution(
            query=query, kind="report",
            answer=f"report transform decoder: the "
                   f"{counts['codeword_count']} Golay coset costs are one "
                   f"Walsh-Hadamard transform, which costs "
                   f"{counts['fwht_ops']} add/subtracts against the direct "
                   f"{counts['direct_adds']} -- equal, because n = 2k, so "
                   f"the transform is not a speed-up for this code; the "
                   f"transform-driven decoder reproduces the existing one "
                   f"exactly, tie sets included; and the constant-time "
                   f"lookup certifies its own optimality on "
                   f"{rates['total_certified']} of "
                   f"{rates['total_samples']} sampled profiles -- always on "
                   f"a flat profile, rarely on a very wide one -- with "
                   f"{rates['certified_but_wrong']} certified answers wrong",
            steps=tuple(steps), expected=expected,
            script_spec={"template": "report_transform_decoder", "args": {}},
            payload={"report": report})
