import Mathlib

set_option autoImplicit false

/-!
# Stage 0 — the logical beginning: distinction

The UBP framework announces itself as a *binary* principle: reality is a field
of cells each of which is in one of two states, and the only dynamics is
toggling.  This file starts from that and nothing else, and asks what is
*forced*.

The findings proved here (FP-1 … FP-7 of `FINDINGS.md`):

* **FP-1** A carrier with no distinction carries no information: every function
  out of a subsingleton is constant (`no_information_without_distinction`).
* **FP-2** Two states is the minimal non-degenerate carrier, and every carrier
  with at least two states maps onto it (`bool_card`, `surjects_onto_bool`).
* **FP-3** A field of `n` two-state cells has exactly `2 ^ n` states — the
  substrate's information content is `n` bits and nothing more
  (`bitfield_card`).
* **FP-4** The reversible operations on one cell form a group of order two,
  generated by the toggle; so "toggle" is not a modelling choice but the only
  non-trivial reversible unary operation (`perm_bool_card`, `toggle_involutive`,
  `perm_bool_eq`).
* **FP-5** Any ring structure on a two-element carrier is `ZMod 2`; binary
  arithmetic on the substrate is therefore forced, not chosen
  (`two_element_ring_is_zmod_two`, `bit_field_card`, `boolEquivZMod2`).
* **FP-6** Cellwise toggling makes the state space the elementary abelian group
  `(ZMod 2) ^ n`: every state is its own inverse and every state is reachable
  from the empty state by a single toggle pattern
  (`self_inverse`, `reachable`).
* **FP-7** Commutativity of the substrate is *derived*, not assumed: any group
  in which every element is self-inverse is abelian
  (`self_inverse_forces_comm`).

Nothing beyond "there is a distinction, and it can be flipped reversibly" is
used.
-/

namespace UBPFirstPrinciples

/-! ## FP-1  No distinction, no information -/

/-- If a carrier has at most one state, every observable defined on it is
constant: a substrate with no distinction carries no information. -/
theorem no_information_without_distinction {α β : Type*} [Subsingleton α]
    (f : α → β) (a b : α) : f a = f b := by
  rw [Subsingleton.elim a b]

/-! ## FP-2  Two states is the minimum -/

theorem bool_card : Fintype.card Bool = 2 := rfl

/-- Any carrier with two distinguishable states maps onto the two-state
carrier: `Bool` is the universal minimal distinction. -/
theorem surjects_onto_bool {α : Type*} {a b : α} (hab : a ≠ b) :
    ∃ f : α → Bool, Function.Surjective f := by
  classical
  refine ⟨fun x => decide (x = a), fun t => ?_⟩
  cases t with
  | true => exact ⟨a, by simp⟩
  | false => exact ⟨b, by simp [Ne.symm hab]⟩

/-! ## The substrate: `n` binary cells -/

/-- A bitfield of `n` cells.  We use `ZMod 2` rather than `Bool` for the state
of a cell: by FP-5 the two carriers are the same object, and `ZMod 2` carries
the (forced) arithmetic. -/
abbrev Bits (n : ℕ) := Fin n → ZMod 2

/-! ## FP-3  Counting the states -/

theorem bitfield_card (n : ℕ) : Fintype.card (Bits n) = 2 ^ n := by
  simp [Bits]

theorem bitfield_card_bool (n : ℕ) : Fintype.card (Fin n → Bool) = 2 ^ n := by
  simp

/-! ## FP-4  The toggle is the only non-trivial reversible unary operation -/

/-- There are exactly two reversible operations on a single cell. -/
theorem perm_bool_card : Fintype.card (Equiv.Perm Bool) = 2 := by
  rw [Fintype.card_perm]; decide

theorem toggle_involutive : ∀ b : Bool, !(!b) = b := by decide

/-- Every reversible operation on one cell is either the identity or the
toggle. -/
theorem perm_bool_eq (σ : Equiv.Perm Bool) :
    (∀ b, σ b = b) ∨ (∀ b, σ b = !b) := by
  revert σ; decide

/-! ## FP-5  The two-element carrier is a field, uniquely -/

theorem bit_field_card : Fintype.card (ZMod 2) = 2 := by simp

/-- Every ring with two elements is the two-element field `ZMod 2`: the
substrate's arithmetic is forced by its carrier. -/
theorem two_element_ring_is_zmod_two (R : Type) [Ring R] [Fintype R]
    (h : Fintype.card R = 2) : Nonempty (ZMod 2 ≃+* R) :=
  ⟨ZMod.ringEquivOfPrime R (by norm_num) h⟩

/-- The two-state carrier and the two-element field are the same object. -/
def boolEquivZMod2 : Bool ≃ ZMod 2 where
  toFun b := if b then 1 else 0
  invFun x := x ≠ 0
  left_inv := by decide
  right_inv := by decide

/-! ## FP-6  Toggling generates the state space -/

/-- Toggling twice restores the state: every state is its own inverse. -/
theorem self_inverse {n : ℕ} (x : Bits n) : x + x = 0 := by
  funext i
  have : (2 : ZMod 2) = 0 := rfl
  simpa [two_mul] using congrArg (fun c : ZMod 2 => c * x i) this

/-- Every state is reachable from the zero state by exactly one toggle
pattern. -/
theorem reachable {n : ℕ} (x y : Bits n) : ∃! t : Bits n, x + t = y :=
  ⟨y - x, by ring, fun t ht => by rw [← ht]; ring⟩

/-! ## FP-7  Reversibility forces commutativity -/

/-- A group in which every element is its own inverse is abelian.  Applied to
the substrate: the commutativity of toggle composition is a theorem, not a
postulate. -/
theorem self_inverse_forces_comm {G : Type*} [Group G] (h : ∀ x : G, x * x = 1)
    (a b : G) : a * b = b * a := by
  have hinv : ∀ x : G, x⁻¹ = x := fun x => by
    rw [eq_comm, ← mul_eq_one_iff_eq_inv]; exact h x
  calc a * b = (a * b)⁻¹ := (hinv _).symm
    _ = b⁻¹ * a⁻¹ := mul_inv_rev a b
    _ = b * a := by rw [hinv, hinv]

end UBPFirstPrinciples
