import Mathlib
import UBP.SeedClasses

set_option autoImplicit false

/-!
# Module 2 — the three one-parameter motions, and which seed each one produces

The framework's picture is that a bare number carries no structure: you need
several copies of the object *and you must move them*.  The mathematical content
of that picture is that a number is a **projection of a group action**, and the
information lost is the **fibre** of the projection.

The cleanest instance, and the one that matches the three seeds exactly, is the
group of motions of a plane lattice.  In `SL(2,ℝ)` a one-parameter motion is of
exactly one of three types, and this module builds the three explicitly:

| motion | matrix | invariant number | fibre |
|---|---|---|---|
| rotation (elliptic) | `rot t` | the period, `2π` | winding number, `ℤ` |
| shear (parabolic) | `shear t` | eigenvalue `1` | shear axis |
| stretch (hyperbolic) | `fibMat` | eigenvalue `φ` | Galois conjugate `1−φ = −1/φ` (finite, 2) |
| the flow joining them | `exp` | `e = ` time-1 value | the whole time axis `ℝ` |

Results proved here (P2-1 … P2-14):

* `rot_mul`, `rot_pow` — the rotations form a one-parameter group;
* `rot_eq_one_iff`, `period_lattice_eq`, `two_pi_least_period` — **`π` is the
  generator of the period lattice**: `rot t = 1 ↔ t ∈ 2πℤ`, and `2π` is the
  least positive period.  This is the positive characterisation of `π` that the
  parent study was missing (it had only the negative result that `Y` at `Π = π`
  is not extremal);
* `period_fibre_infinite` — the fibre over "the rotation closed up" is infinite;
* `shear_mul`, `shear_pow_mulVec`, `shear_eigenvalue_eq_one` — a shear is
  unipotent, has `1` as its only eigenvalue, and its orbits grow **linearly**;
* `fibMat_eigenvector`, `fibMat_pow_mulVec`, `phi_pow_beats_linear` — the
  Fibonacci matrix is a *stretch*: eigenvalue `φ > 1`, orbits grow
  **exponentially**.  So the framework's "φ shears" is right in spirit and wrong
  in detail: `φ`'s motion is a stretch, and the difference is a theorem;
* `quadratic_eigenvalue_fibre` — the fibre of `φ` as an eigenvalue is exactly
  `{φ, 1−φ}`: **finite, of size 2**;
* `sl2_real_eigenvalue_iff`, `sl2_trichotomy` — the elliptic/parabolic/hyperbolic
  trichotomy on the trace;
* `flow_time_one`, `e_flow_fibre` — `e` is the time-1 value of the flow generated
  by the identity vector field, and the fibre (which base, which time) is `ℝ`.
-/

namespace UBPProjection

open Matrix Real

/-! ## 1. The rotation (elliptic) motion, and `π` as period generator -/

/-- The rotation by angle `t` in the plane. -/
noncomputable def rot (t : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  !![Real.cos t, -Real.sin t; Real.sin t, Real.cos t]

/-- **P2-1.**  The rotations form a one-parameter group. -/
theorem rot_mul (a b : ℝ) : rot a * rot b = rot (a + b) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rot, Matrix.mul_apply, Fin.sum_univ_two, Real.cos_add, Real.sin_add] <;> ring

theorem rot_zero : rot 0 = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [rot]

theorem rot_pow (t : ℝ) (n : ℕ) : rot t ^ n = rot (n * t) := by
  induction n with
  | zero => simpa using rot_zero.symm
  | succ n ih => rw [pow_succ, ih, rot_mul]; push_cast; ring_nf

theorem rot_trace (t : ℝ) : (rot t).trace = 2 * Real.cos t := by
  simp [rot, Matrix.trace_fin_two]; ring

theorem rot_det (t : ℝ) : (rot t).det = 1 := by
  simp only [rot, Matrix.det_fin_two_of]
  nlinarith [Real.sin_sq_add_cos_sq t]

/-- **P2-2.**  `rot t` is the identity exactly when `t` is an integer multiple of
`2π`: the period lattice of the rotation flow is `2πℤ`, generated by `π`. -/
theorem rot_eq_one_iff (t : ℝ) : rot t = 1 ↔ ∃ k : ℤ, t = k * (2 * Real.pi) := by
  constructor
  · intro h
    have h00 : Real.cos t = 1 := by
      have := congrArg (fun M : Matrix (Fin 2) (Fin 2) ℝ => M 0 0) h
      simpa [rot, Matrix.one_apply] using this
    obtain ⟨k, hk⟩ := (Real.cos_eq_one_iff t).1 h00
    exact ⟨k, hk.symm⟩
  · rintro ⟨k, rfl⟩
    have hc : Real.cos ((k : ℝ) * (2 * Real.pi)) = 1 := Real.cos_int_mul_two_pi k
    have hs : Real.sin ((k : ℝ) * (2 * Real.pi)) = 0 := by
      have h2 : ((k : ℝ) * (2 * Real.pi)) = ((2 * k : ℤ) : ℝ) * Real.pi := by push_cast; ring
      rw [h2]; exact Real.sin_int_mul_pi (2 * k)
    ext i j
    fin_cases i <;> fin_cases j <;> simp [rot, hc, hs]

/-- The period lattice, as a set. -/
theorem period_lattice_eq :
    {t : ℝ | rot t = 1} = {t : ℝ | ∃ k : ℤ, t = k * (2 * Real.pi)} := by
  ext t; exact rot_eq_one_iff t

/-- **P2-3.**  `2π` is the least positive period: `π` is not an arbitrary
normalisation but the generator of the period lattice. -/
theorem two_pi_least_period :
    rot (2 * Real.pi) = 1 ∧ ∀ t : ℝ, 0 < t → t < 2 * Real.pi → rot t ≠ 1 := by
  refine ⟨(rot_eq_one_iff _).2 ⟨1, by push_cast; ring⟩, ?_⟩
  intro t ht htlt h
  obtain ⟨k, rfl⟩ := (rot_eq_one_iff t).1 h
  have hpi : 0 < 2 * Real.pi := by positivity
  have hk0 : (0 : ℝ) < k := by
    by_contra hc
    push_neg at hc
    nlinarith
  have hk1 : (k : ℝ) < 1 := by
    by_contra hc
    push_neg at hc
    nlinarith
  have hk0' : (0 : ℤ) < k := by exact_mod_cast hk0
  have hk1' : (k : ℤ) < 1 := by exact_mod_cast hk1
  omega

/-- **P2-4.**  The fibre over "the rotation has closed up" is infinite: the
number `2π` remembers the period but forgets the winding number. -/
theorem period_fibre_infinite : {t : ℝ | rot t = 1}.Infinite := by
  have hpi : (2 * Real.pi) ≠ 0 := by positivity
  have hinj : Function.Injective (fun k : ℤ => (k : ℝ) * (2 * Real.pi)) := by
    intro a b hab
    simp only at hab
    have : (a : ℝ) = b := mul_right_cancel₀ hpi hab
    exact_mod_cast this
  have hsub : Set.range (fun k : ℤ => (k : ℝ) * (2 * Real.pi)) ⊆ {t : ℝ | rot t = 1} := by
    rintro _ ⟨k, rfl⟩
    exact (rot_eq_one_iff _).2 ⟨k, rfl⟩
  exact Set.Infinite.mono hsub (Set.infinite_range_of_injective hinj)

/-! ## 2. The shear (parabolic) motion -/

/-- The shear with parameter `t`. -/
def shear (t : ℝ) : Matrix (Fin 2) (Fin 2) ℝ := !![1, t; 0, 1]

theorem shear_mul (a b : ℝ) : shear a * shear b = shear (a + b) := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [shear, Matrix.mul_apply, Fin.sum_univ_two, add_comm]

theorem shear_trace (t : ℝ) : (shear t).trace = 2 := by
  simp [shear, Matrix.trace_fin_two]; norm_num

theorem shear_det (t : ℝ) : (shear t).det = 1 := by simp [shear, Matrix.det_fin_two]

/-- A shear is unipotent: `(shear t − 1)² = 0`. -/
theorem shear_unipotent (t : ℝ) : (shear t - 1) ^ 2 = 0 := by
  have h : shear t - 1 = !![0, t; 0, 0] := by
    ext i j; fin_cases i <;> fin_cases j <;> simp [shear]
  rw [h, pow_two]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two]

theorem shear_pow (t : ℝ) (n : ℕ) : shear t ^ n = shear (n * t) := by
  induction n with
  | zero =>
      ext i j
      fin_cases i <;> fin_cases j <;> simp [shear]
  | succ n ih => rw [pow_succ, ih, shear_mul]; push_cast; ring_nf

/-- **P2-5.**  A shear moves every vector *linearly* in the number of steps. -/
theorem shear_pow_mulVec (a b : ℝ) (n : ℕ) :
    (shear 1 ^ n).mulVec ![a, b] = ![a + n * b, b] := by
  rw [shear_pow]
  ext i
  fin_cases i <;> simp [shear, Matrix.mulVec, dotProduct, Fin.sum_univ_two]

/-- **P2-6.**  The only eigenvalue of a shear is `1`; in particular no shear has
`φ` as an eigenvalue.  A shear is *not* the motion behind the golden ratio. -/
theorem shear_eigenvalue_eq_one (t lam : ℝ) (v : Fin 2 → ℝ) (hv : v ≠ 0)
    (h : (shear t).mulVec v = lam • v) : lam = 1 := by
  have h1 : v 1 = lam * v 1 := by
    have := congrFun h 1
    simpa [shear, Matrix.mulVec, dotProduct, Fin.sum_univ_two] using this
  have h0 : v 0 + t * v 1 = lam * v 0 := by
    have := congrFun h 0
    simpa [shear, Matrix.mulVec, dotProduct, Fin.sum_univ_two] using this
  by_cases hb : v 1 = 0
  · have hv0 : v 0 ≠ 0 := by
      intro h00
      refine hv ?_
      funext i
      fin_cases i <;> simp [h00, hb]
    rw [hb] at h0
    have : (lam - 1) * v 0 = 0 := by linarith
    rcases mul_eq_zero.mp this with h | h
    · linarith
    · exact absurd h hv0
  · have h2 : (lam - 1) * v 1 = 0 := by linarith
    rcases mul_eq_zero.mp h2 with h | h
    · linarith
    · exact absurd h hb

/-! ## 3. The stretch (hyperbolic) motion, and `φ` -/

/-- The Fibonacci matrix `[[1,1],[1,0]]`: the cheapest non-trivial motion of a
rank-2 integer lattice. -/
def fibMat : Matrix (Fin 2) (Fin 2) ℝ := !![1, 1; 1, 0]

theorem fibMat_trace : fibMat.trace = 1 := by simp [fibMat, Matrix.trace_fin_two]

theorem fibMat_det : fibMat.det = -1 := by simp [fibMat, Matrix.det_fin_two]

/-- **P2-7.**  `φ` is an eigenvalue of the Fibonacci matrix. -/
theorem fibMat_eigenvector : fibMat.mulVec ![UBP.phi, 1] = UBP.phi • ![UBP.phi, 1] := by
  have hsq : UBP.phi ^ 2 = UBP.phi + 1 := UBP.phi_sq
  funext i
  fin_cases i
  all_goals simp [fibMat, Matrix.mulVec, dotProduct, Fin.sum_univ_two]
  all_goals nlinarith [hsq]

/-- **P2-8.**  The Galois conjugate `1 − φ = −1/φ` is the second eigenvalue. -/
theorem fibMat_conj_eigenvector :
    fibMat.mulVec ![1 - UBP.phi, 1] = (1 - UBP.phi) • ![1 - UBP.phi, 1] := by
  have hsq : UBP.phi ^ 2 = UBP.phi + 1 := UBP.phi_sq
  funext i
  fin_cases i
  all_goals simp [fibMat, Matrix.mulVec, dotProduct, Fin.sum_univ_two]
  all_goals nlinarith [hsq]

theorem phi_conj_eq : 1 - UBP.phi = -(1 / UBP.phi) := by
  have hsq : UBP.phi ^ 2 = UBP.phi + 1 := UBP.phi_sq
  have hpos : 0 < UBP.phi := UBP.phi_enc.pos (by norm_num)
  field_simp
  nlinarith [hsq]

/-- **P2-9.**  The fibre of the eigenvalue equation is **finite, of size two**:
`{x : x² = x + 1} = {φ, 1 − φ}`.  This is the precise sense in which `φ` needs
no limit and no topology — only a rank-2 integer lattice and one integer matrix.
-/
theorem quadratic_eigenvalue_fibre :
    {x : ℝ | x ^ 2 = x + 1} = {UBP.phi, 1 - UBP.phi} := by
  have hsq : UBP.phi ^ 2 = UBP.phi + 1 := UBP.phi_sq
  ext x
  simp only [Set.mem_setOf_eq, Set.mem_insert_iff, Set.mem_singleton_iff]
  constructor
  · intro hx
    have key : (x - UBP.phi) * (x - (1 - UBP.phi)) = 0 := by nlinarith [hx, hsq]
    rcases mul_eq_zero.mp key with h | h
    · left; linarith
    · right; linarith
  · rintro (rfl | rfl) <;> nlinarith [hsq]

theorem fibMat_pow_mulVec (n : ℕ) :
    (fibMat ^ n).mulVec ![UBP.phi, 1] = (UBP.phi ^ n) • ![UBP.phi, 1] := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ, ← Matrix.mulVec_mulVec, fibMat_eigenvector, Matrix.mulVec_smul, ih,
        smul_smul, pow_succ]
      congr 1
      ring

/-- **P2-10.**  Exponential beats linear: the stretch really is a different kind
of motion from the shear. -/
theorem phi_pow_beats_linear (C : ℝ) : ∃ n : ℕ, C * (1 + n) < UBP.phi ^ n := by
  obtain ⟨m, hm⟩ := exists_nat_gt (10 * |C| + 20)
  refine ⟨2 * m, ?_⟩
  have hphi : (1.6 : ℝ) < UBP.phi := by have := UBP.phi_enc.1; norm_num at this ⊢; linarith
  have hCabs : (0:ℝ) ≤ |C| := abs_nonneg C
  have hm0 : (20 : ℝ) < m := by linarith
  have hlin : (1 : ℝ) + (0.6 : ℝ) * m ≤ UBP.phi ^ m := by
    calc (1 : ℝ) + (0.6 : ℝ) * m ≤ (1 + 0.6) ^ m := by
          have h := one_add_mul_le_pow (a := (0.6 : ℝ)) (by norm_num) m
          linarith
      _ ≤ UBP.phi ^ m := pow_le_pow_left₀ (by norm_num) (by linarith) m
  have hpos : (0 : ℝ) < 1 + 0.6 * m := by linarith
  have hsq : (1 + (0.6 : ℝ) * m) ^ 2 ≤ UBP.phi ^ (2 * m) := by
    have h2 : UBP.phi ^ (2 * m) = (UBP.phi ^ m) ^ 2 := by rw [← pow_mul, Nat.mul_comm]
    rw [h2]
    exact pow_le_pow_left₀ (le_of_lt hpos) hlin 2
  have hC : C ≤ |C| := le_abs_self C
  have hfin : C * (1 + ((2 * m : ℕ) : ℝ)) < (1 + 0.6 * m) ^ 2 := by
    push_cast
    nlinarith [hm, hm0, hC, hCabs]
  calc C * (1 + ((2 * m : ℕ) : ℝ)) < (1 + 0.6 * m) ^ 2 := hfin
    _ ≤ UBP.phi ^ (2 * m) := hsq

/-! ## 4. The trichotomy of motions -/

/-- **P2-11.**  For a motion of determinant `1`, a real eigenvalue exists exactly
when the trace has absolute value at least `2`.  This is the
elliptic / parabolic / hyperbolic split. -/
theorem sl2_real_eigenvalue_iff (t : ℝ) :
    (∃ lam : ℝ, lam ^ 2 - t * lam + 1 = 0) ↔ 4 ≤ t ^ 2 := by
  constructor
  · rintro ⟨lam, hlam⟩
    nlinarith [sq_nonneg (2 * lam - t), sq_nonneg lam, sq_nonneg (lam - 1), sq_nonneg (lam + 1)]
  · intro ht
    refine ⟨(t + Real.sqrt (t ^ 2 - 4)) / 2, ?_⟩
    have hs : Real.sqrt (t ^ 2 - 4) ^ 2 = t ^ 2 - 4 := Real.sq_sqrt (by linarith)
    field_simp
    nlinarith [hs]

/-- **P2-12.**  The three types, named: elliptic (no real eigenvalue), parabolic (a repeated
real eigenvalue), hyperbolic (two distinct real eigenvalues). -/
theorem sl2_trichotomy (t : ℝ) :
    (t ^ 2 < 4 ∧ ¬ ∃ lam : ℝ, lam ^ 2 - t * lam + 1 = 0) ∨
    (t ^ 2 = 4 ∧ ∃! lam : ℝ, lam ^ 2 - t * lam + 1 = 0) ∨
    (4 < t ^ 2 ∧ ∃ lam mu : ℝ, lam ≠ mu ∧ lam ^ 2 - t * lam + 1 = 0 ∧
      mu ^ 2 - t * mu + 1 = 0) := by
  rcases lt_trichotomy (t ^ 2) 4 with h | h | h
  · left
    refine ⟨h, ?_⟩
    intro hex
    have := (sl2_real_eigenvalue_iff t).1 hex
    linarith
  · right; left
    refine ⟨h, ⟨t / 2, by nlinarith, ?_⟩⟩
    intro y hy
    nlinarith [sq_nonneg (2 * y - t)]
  · right; right
    have hs : Real.sqrt (t ^ 2 - 4) ^ 2 = t ^ 2 - 4 := Real.sq_sqrt (by linarith)
    have hspos : 0 < Real.sqrt (t ^ 2 - 4) := Real.sqrt_pos.mpr (by linarith)
    refine ⟨h, (t + Real.sqrt (t ^ 2 - 4)) / 2, (t - Real.sqrt (t ^ 2 - 4)) / 2, ?_, ?_, ?_⟩
    · intro hcon
      have : Real.sqrt (t ^ 2 - 4) = 0 := by
        have := hcon
        field_simp at this
        linarith
      linarith
    · field_simp; nlinarith [hs]
    · field_simp; nlinarith [hs]

/-! ## 5. The flow, and `e` -/

/-- **P2-13.**  `e` is the time-1 value of the flow generated by the identity
vector field: if a motion's rate equals its state and it starts at `1`, then at
time `1` it is at `e`.  Nothing weaker than a flow produces `e`. -/
theorem flow_time_one (f : ℝ → ℝ) (hf : ∀ x, HasDerivAt f (f x) x) (h0 : f 0 = 1) :
    f 1 = UBP.eSeed := by
  have hg : ∀ x : ℝ, HasDerivAt (fun y => f y * Real.exp (-y)) 0 x := by
    intro x
    have h1 : HasDerivAt (fun y : ℝ => Real.exp (-y)) (-Real.exp (-x)) x := by
      simpa using (Real.hasDerivAt_exp (-x)).comp x ((hasDerivAt_id x).neg)
    have h2 := (hf x).mul h1
    have h3 : f x * -Real.exp (-x) + f x * Real.exp (-x) = 0 := by ring
    simpa [h3] using h2
  have hconst : ∀ x : ℝ, f x * Real.exp (-x) = f 0 * Real.exp (-0) := by
    intro x
    exact is_const_of_deriv_eq_zero (fun y => (hg y).differentiableAt)
      (fun y => (hg y).deriv) x 0
  have h1 := hconst 1
  rw [h0] at h1
  simp only [neg_zero, Real.exp_zero, one_mul] at h1
  have hx : Real.exp (-1 : ℝ) ≠ 0 := Real.exp_ne_zero _
  rw [UBP.eSeed]
  have : f 1 = 1 / Real.exp (-1 : ℝ) := by
    field_simp at h1 ⊢
    linarith [h1]
  rw [this, Real.exp_neg]
  field_simp

/-- **P2-14.**  The fibre of `e` as a flow value is the whole time axis: for
every non-zero time `t` there is a base whose flow reaches `e` at time `t`.
The number `e` remembers the value and forgets the clock. -/
theorem e_flow_fibre (t : ℝ) (ht : t ≠ 0) :
    ∃ a : ℝ, 0 < a ∧ a ^ t = UBP.eSeed := by
  refine ⟨Real.exp (1 / t), Real.exp_pos _, ?_⟩
  rw [Real.rpow_def_of_pos (Real.exp_pos _), Real.log_exp, UBP.eSeed]
  congr 1
  field_simp

end UBPProjection
