/-
# The dynamical half: does a perturbed carrier *settle* at the critical weight?

`Golay/Census.lean` answers the static half of the self-organised-criticality
question: averaged over the `4096` cosets the distance to the code is
`3433 / 1024`, strictly between the packing radius `3` and the covering radius
`4`.  That is a statement about a *distribution*.  The dynamical claim is a
statement about a *process*: that a carrier which is repeatedly perturbed and
corrected drifts to the critical boundary and stays there.

This file makes the process explicit and settles what is and is not true of it.

The chain.  A carrier's position relative to the code is its syndrome, and a
one-bit perturbation of coordinate `k` adds the parity-check column `col k` to
it.  So "flip a uniformly chosen coordinate" is the random walk on the
syndrome group generated by the `24` columns, and a distribution over cosets
is pushed forward by `step` below.

What is proved:

* `step_unif` — the uniform law is stationary.
* `stationary_unique` — and it is the *only* stationary law: a non-negative
  invariant `μ` summing to `1` is uniform.  (Maximum principle plus the fact
  that the columns generate every syndrome, which is `exists_word_syn`.)
* `expect_unif_cosetWt` — under it the expected distance to the code is
  exactly the census figure `3433 / 1024`, and
  `prob_unif_critical_band` — the carrier is at distance `3` or `4` with
  probability `3795 / 4096`.
* `prob_unif_subcritical_pos` — but it is at distance `≤ 2` with probability
  `301 / 4096 > 0`: the weight keeps fluctuating, it does not lock on.
* `step_parity` and `iterate_dirac_ne_unif` — worse, the chain is **periodic**:
  every column has odd parity, so the law after `n` steps lives entirely on one
  of the two parity classes and is *never* uniform, from any starting point.
  Convergence in distribution is therefore false as stated; only the
  time-averaged (Cesàro) reading can hold.
* `perturb_correct_returns` and `corrected_orbit_isCodeword` — and if the
  perturbation is followed by a *correction*, criticality disappears
  altogether: a one-bit error on a codeword is corrected back to that same
  codeword, uniquely, so the corrected carrier sits on the code for ever at
  distance `0`.

Read together: "the carrier settles near the critical weight" is false in the
two strong senses (a limiting law, or a concentrating weight) and false again
for the corrected dynamics; what survives is the averaged statement, and it is
exactly the census.  The one thing this file leaves open — Cesàro convergence
of the perturb-only chain to the uniform law — is proved in
`Golay/Cesaro.lean`, with an explicit rate; see the closing section here for
the statement and where it went.
-/
import RequestProject.GLM.Golay.Census

namespace GLM.Golay24

open Finset

/-! ## The perturbation chain on cosets -/

/-- A law on cosets: a weight for each syndrome. -/
abbrev Law : Type := Syn → ℚ

/-- One tick of the process: flip a uniformly chosen one of the `24`
coordinates.  In characteristic two subtracting and adding a column agree, so
the mass arriving at `f` is the mass that sat at `f + col k`. -/
def step (μ : Law) : Law := fun f => (∑ k : Fin 24, μ (f + col k)) / 24

/-- The uniform law on the `4096` cosets. -/
def unif : Law := fun _ => 1 / 4096

/-- A law is a probability distribution when it is non-negative and sums to
one. -/
structure IsProb (μ : Law) : Prop where
  nonneg : ∀ f, 0 ≤ μ f
  total : ∑ f : Syn, μ f = 1

theorem card_syn : Fintype.card Syn = 4096 := by simp

theorem isProb_unif : IsProb unif where
  nonneg := by intro f; norm_num [unif]
  total := by
    simp only [unif, Finset.sum_const, Finset.card_univ, nsmul_eq_mul]
    rw [card_syn]; norm_num

/-- **The uniform law is stationary.** -/
theorem step_unif : step unif = unif := by
  funext f
  simp [step, unif]

/-! ## …and it is the only stationary law -/

/-- In characteristic two a syndrome is its own negative, so shifting twice by
the same syndrome cancels. -/
theorem syn_add_cancel (a b : Syn) : a + (b + a) = b := by
  funext i
  have h : ∀ x y : ZMod 2, x + (y + x) = y := by decide
  exact h (a i) (b i)

/-- Adding a column to a maximiser gives a maximiser. -/
theorem max_shift {μ : Law} (hμ : step μ = μ) {M : ℚ} (hM : ∀ g, μ g ≤ M)
    {f : Syn} (hf : μ f = M) (k : Fin 24) : μ (f + col k) = M := by
  have hsum : ∑ j : Fin 24, μ (f + col j) = 24 * M := by
    have := congrFun hμ f
    simp only [step] at this
    field_simp at this
    linarith [this, hf]
  by_contra hne
  have hlt : μ (f + col k) < M := lt_of_le_of_ne (hM _) hne
  have : ∑ j : Fin 24, μ (f + col j) < ∑ _j : Fin 24, M :=
    Finset.sum_lt_sum (fun j _ => hM _) ⟨k, Finset.mem_univ k, hlt⟩
  simp only [Finset.sum_const, Finset.card_univ, Fintype.card_fin,
    nsmul_eq_mul] at this
  rw [hsum] at this
  norm_num at this

/-- Adding the syndrome of any word to a maximiser gives a maximiser. -/
theorem max_shift_syn {μ : Law} (hμ : step μ = μ) {M : ℚ} (hM : ∀ g, μ g ≤ M)
    {f : Syn} (hf : μ f = M) (s : Word) : μ (f + syn s) = M := by
  classical
  induction s using Finset.induction with
  | empty => simpa [syn_empty] using hf
  | insert k s hk ih =>
      have hstep : syn (insert k s) = col k + syn s := by
        simp [syn, Finset.sum_insert hk]
      have : μ ((f + syn s) + col k) = M := max_shift hμ hM ih k
      rw [hstep]
      rw [show f + (col k + syn s) = (f + syn s) + col k by ring]
      exact this

/-- **Uniqueness of the stationary law.**  A stationary probability
distribution on the cosets is the uniform one. -/
theorem stationary_unique {μ : Law} (hp : IsProb μ) (hμ : step μ = μ) :
    μ = unif := by
  classical
  obtain ⟨f₀, -, hmax⟩ :=
    Finset.exists_max_image (univ : Finset Syn) μ ⟨0, Finset.mem_univ 0⟩
  have hM : ∀ g, μ g ≤ μ f₀ := fun g => hmax g (Finset.mem_univ g)
  have hconst : ∀ g : Syn, μ g = μ f₀ := by
    intro g
    obtain ⟨u, -, hu⟩ := exists_word_syn (g + f₀)
    have := max_shift_syn hμ hM rfl u
    rw [hu, syn_add_cancel] at this
    exact this
  have hsum : (4096 : ℚ) * μ f₀ = 1 := by
    have := hp.total
    rw [Finset.sum_congr rfl (fun g _ => hconst g)] at this
    simpa [Finset.card_univ, card_syn] using this
  funext g
  rw [hconst g, unif]
  linarith

/-! ## What the stationary law says about the distance to the code -/

/-- The expected value of a function of the coset under a law. -/
def expect (μ : Law) (F : Syn → ℚ) : ℚ := ∑ f : Syn, μ f * F f

/-- **The long-run mean distance to the code is the census figure.** -/
theorem expect_unif_cosetWt : expect unif (fun f => (cosetWt f : ℚ))
    = 3433 / 1024 := by
  simp only [expect, unif]
  rw [← Finset.mul_sum, sum_cosetWt]
  norm_num

/-- The probability the stationary carrier is at distance `3` or `4`. -/
theorem prob_unif_critical_band :
    ∑ f ∈ univ.filter (fun f : Syn => 3 ≤ cosetWt f), unif f = 3795 / 4096 := by
  classical
  have hsplit : (univ.filter fun f : Syn => 3 ≤ cosetWt f)
      = (univ.filter fun f : Syn => cosetWt f = 3) ∪
        (univ.filter fun f : Syn => cosetWt f = 4) := by
    ext f
    simp only [Finset.mem_filter, Finset.mem_univ, true_and, Finset.mem_union]
    have := cosetWt_le_four f
    omega
  have hdisj : Disjoint (univ.filter fun f : Syn => cosetWt f = 3)
      (univ.filter fun f : Syn => cosetWt f = 4) := by
    simp only [Finset.disjoint_left, Finset.mem_filter]
    omega
  obtain ⟨-, -, -, h3, h4⟩ := coset_census
  simp only [unif, Finset.sum_const, nsmul_eq_mul]
  rw [hsplit, Finset.card_union_of_disjoint hdisj, h3, h4]
  norm_num

/-- …and the probability it is *below* the packing radius is positive: the
weight fluctuates, it does not lock on to the critical band. -/
theorem prob_unif_subcritical :
    ∑ f ∈ univ.filter (fun f : Syn => cosetWt f ≤ 2), unif f = 301 / 4096 := by
  classical
  have hsplit : (univ.filter fun f : Syn => cosetWt f ≤ 2)
      = (univ.filter fun f : Syn => cosetWt f = 0) ∪
        ((univ.filter fun f : Syn => cosetWt f = 1) ∪
          (univ.filter fun f : Syn => cosetWt f = 2)) := by
    ext f
    simp only [Finset.mem_filter, Finset.mem_univ, true_and, Finset.mem_union]
    omega
  obtain ⟨h0, h1, h2, -, -⟩ := coset_census
  simp only [unif, Finset.sum_const, nsmul_eq_mul]
  rw [hsplit, Finset.card_union_of_disjoint, Finset.card_union_of_disjoint,
    h0, h1, h2]
  · norm_num
  · simp only [Finset.disjoint_left, Finset.mem_filter]
    omega
  · simp only [Finset.disjoint_left, Finset.mem_filter, Finset.mem_union]
    omega

theorem prob_unif_subcritical_pos :
    0 < ∑ f ∈ univ.filter (fun f : Syn => cosetWt f ≤ 2), unif f := by
  rw [prob_unif_subcritical]; norm_num

/-! ## The chain is periodic, so it has no limiting law -/

theorem zmod2_add_one_cancel (x : ZMod 2) : x + 1 + 1 = x := by revert x; decide

/-- The parity of a syndrome: the sum of its twelve bits. -/
def par (f : Syn) : ZMod 2 := ∑ i : Fin 12, f i

/-- Every parity-check column has odd parity — the `B` block has odd column
sums and the identity block contributes a single one. -/
theorem par_col (k : Fin 24) : par (col k) = 1 := by
  revert k; decide

theorem par_add (f g : Syn) : par (f + g) = par f + par g := by
  simp [par, Finset.sum_add_distrib]

theorem par_add_col (f : Syn) (k : Fin 24) : par (f + col k) = par f + 1 := by
  rw [par_add, par_col]

/-- A law supported on one parity class is pushed to the other one. -/
theorem step_parity {μ : Law} {p : ZMod 2} (h : ∀ f, μ f ≠ 0 → par f = p)
    {f : Syn} (hf : step μ f ≠ 0) : par f = p + 1 := by
  classical
  by_contra hne
  apply hf
  have hzero : ∀ k : Fin 24, μ (f + col k) = 0 := by
    intro k
    by_contra hk
    have hpk := h _ hk
    rw [par_add_col] at hpk
    exact hne (by rw [← hpk, zmod2_add_one_cancel])
  simp [step, hzero]

/-- The point mass at a syndrome. -/
noncomputable def dirac (g : Syn) : Law := fun f => if f = g then 1 else 0

theorem dirac_parity (g : Syn) : ∀ f, dirac g f ≠ 0 → par f = par g := by
  intro f hf
  by_cases h : f = g
  · rw [h]
  · simp [dirac, h] at hf

/-- After `n` steps the law from a point mass still lives on a single parity
class. -/
theorem iterate_parity (g : Syn) :
    ∀ n : ℕ, ∀ f, (step^[n] (dirac g)) f ≠ 0 → par f = par g + n := by
  intro n
  induction n with
  | zero => simpa using dirac_parity g
  | succ n ih =>
      intro f hf
      rw [Function.iterate_succ_apply'] at hf
      have := step_parity (p := par g + n) ih hf
      rw [this]
      push_cast
      ring

/-- **The chain has no limiting law.**  Started from any point mass, the law
after `n` steps vanishes on a whole parity class, while the uniform law does
not: it is never uniform, for any `n`. -/
theorem iterate_dirac_ne_unif (g : Syn) (n : ℕ) : step^[n] (dirac g) ≠ unif := by
  intro hcontra
  -- pick a syndrome of the wrong parity: `g` and `g + col 0` differ in parity
  by_cases hg : par g + (n : ZMod 2) = par g
  · have hne : par (g + col 0) ≠ par g + n := by
      rw [par_add_col, hg]
      intro h
      have : (1 : ZMod 2) = 0 := by
        have := h
        simpa using congrArg (fun x => x - par g) this
      exact absurd this (by decide)
    have hzero := iterate_parity g n (g + col 0)
    have : (step^[n] (dirac g)) (g + col 0) = 0 := by
      by_contra hnz
      exact hne (hzero hnz)
    rw [hcontra] at this
    simp [unif] at this
  · have hne : par g ≠ par g + n := fun h => hg h.symm
    have hzero := iterate_parity g n g
    have : (step^[n] (dirac g)) g = 0 := by
      by_contra hnz
      exact hne (hzero hnz)
    rw [hcontra] at this
    simp [unif] at this

/-! ## With correction, criticality disappears -/

/-- A one-bit perturbation of a codeword sits at distance exactly `1` from the
code. -/
theorem cosetWt_perturbed_codeword {c : Word} (hc : IsCodeword c)
    (k : Fin 24) : cosetWt (syn (symmDiff c ({k} : Word))) = 1 := by
  have hsyn : syn (symmDiff c ({k} : Word)) = syn ({k} : Word) := by
    rw [syn_symmDiff, hc]
    simp
  rw [hsyn]
  have hwt : wt ({k} : Word) = 1 := by simp [wt]
  rw [cosetWt_of_wt_le_three (by omega), hwt]

/-- **Correction undoes the perturbation, uniquely.**  The nearest codeword to
a one-bit perturbation of `c` is `c` and nothing else, so a carrier that is
perturbed and then corrected is back where it started. -/
theorem perturb_correct_returns {c : Word} (hc : IsCodeword c) (k : Fin 24)
    {d : Word} (hd : IsCodeword d)
    (hmin : hdist (symmDiff c ({k} : Word)) d
      = cosetWt (syn (symmDiff c ({k} : Word)))) : d = c := by
  have h1 : hdist (symmDiff c ({k} : Word)) d ≤ 3 := by
    rw [hmin, cosetWt_perturbed_codeword hc k]; omega
  have h2 : hdist (symmDiff c ({k} : Word)) c ≤ 3 := by
    rw [hdist_eq_wt_symmDiff, symmDiff_comm, symmDiff_symmDiff_self]
    simp [wt]
  exact unique_nearest_of_le_three hd hc h1 h2

/-- The corrected carrier never leaves the code: whatever sequence of
coordinates is flipped, correcting after each flip returns the same codeword,
so the distance to the code after every correction is `0`. -/
theorem corrected_orbit_isCodeword {c : Word} (hc : IsCodeword c)
    (ks : List (Fin 24)) :
    ∀ d : Word, IsCodeword d →
      (∀ k ∈ ks, hdist (symmDiff c ({k} : Word)) d
        = cosetWt (syn (symmDiff c ({k} : Word)))) → ks ≠ [] → d = c := by
  intro d hd hmin hne
  match ks with
  | [] => exact absurd rfl hne
  | k :: _ => exact perturb_correct_returns hc k hd (hmin k (by simp))

/-! ## What replaces the limit, and where it is proved

The perturb-only chain is periodic, so `step^[n] μ` cannot converge; the
correct dynamical statement is Cesàro convergence of the time averages,

  `(1 / N) ∑_{n < N} (step^[n] μ) f  →  1 / 4096`   as `N → ∞`,

for every probability law `μ` and every syndrome `f`.  That statement was left
open when this file was written, on the grounds that it needs a quantitative
mixing argument — a Doeblin minorisation for some power of the kernel, or
Fourier analysis on `(ZMod 2)^12` — which Mathlib does not supply ready-made
for a finite kernel of this shape.  It is now proved, by the second route, in
`RequestProject/GLM/Golay/Cesaro.lean`: `cesaro_converges` gives the explicit
rational bound

  `|cesaro μ N f - 1 / 4096| ≤ 24 / N`   for every `N ≥ 1`,

and `cesaro_tendsto` reads it back as an ordinary limit.  The `24` is the
reciprocal of the spectral gap: the eigenvalue of `step` at a non-trivial
character is at most `11/12`, because the parity-check columns span the
syndrome group (`exists_word_syn`), so `1 - λ ≥ 1/12` and a geometric partial
sum is bounded by `2 / (1/12) = 24` however long it runs.  Nothing in this
file depends on that result; the dependency runs the other way.

What is settled *here*, without it, is the negative half — the part the
self-organised-criticality claim actually needed: the process has no limiting
law at all (`iterate_dirac_ne_unif`), its stationary law does not concentrate
at the critical weight (`prob_unif_subcritical_pos`), and under correction the
carrier stays on the code rather than drifting to the boundary
(`perturb_correct_returns`). -/

end GLM.Golay24
