"""
mog_transformer.py — MOG-as-Attention ARC Transformer (v2)
============================================================

Key insight from user: the MOG IS the attention mechanism, not a preprocessing step.

The 4×6 MOG grid maps directly to how information flows:
  Row 0 (M_Mass):      Global structure — what colour WHERE
  Row 1 (I_Info):      Topological connectivity — what's adjacent to what
  Row 2 (A_Activation): Active transformations — what CHANGES
  Row 3 (P_Potential):  Latent structure — what COULD change

The 6 columns are spatial blocks that partition the grid.

Instead of encoding cells into 24-bit vectors, we:
1. View the grid through 4 semantic "channels" (like CNN channels)
2. Each channel captures a different aspect of the grid
3. The Golay engine operates on these channels (error correction on structure)
4. TAX/NRCI measures the geometric stability of the result
5. Candidates are generated by channel-wise operations

This is a substrate-native transformer: the MOG rows are attention heads,
the columns are spatial blocks, and the Golay snap is the denoising step.
"""

from __future__ import annotations
import os, sys, json, time, math
from collections import Counter, defaultdict
from typing import Dict, List, Optional, Tuple, Any, Set

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from arc_loader import ARCTask, Grid, load_task
from v062_unified_learning import (
    gravity_down, local_swap, colour_center_fill,
    column_rank_fill, marker_fill_85, cond_recolour,
    verify_and_predict, extract_objects,
)
from v032_distance_rule import try_distance_diagonal_rule
from v065_ubp_glm import learn_multi_interior_fill


# ═══════════════════════════════════════════════════════════════════════════════
# MOG Channel Extraction — the 4 semantic channels
# ═══════════════════════════════════════════════════════════════════════════════

def extract_mog_channels(grid: Grid) -> Dict[str, Any]:
    """
    Extract 4 semantic channels from an ARC grid, mirroring the MOG rows.
    
    Channel 0 (M_Mass):      Colour distribution — what colours exist, where
    Channel 1 (I_Info):      Adjacency graph — what touches what
    Channel 2 (A_Activation): Change potential — where could things change
    Channel 3 (P_Potential):  Structural skeleton — borders, corners, patterns
    """
    h, w = grid.height, grid.width
    cells = grid.cells
    
    # Channel 0: Colour distribution (per-row colour histograms)
    mass = []
    for r in range(h):
        row_hist = Counter(cells[r])
        mass.append(row_hist)
    
    # Channel 1: Adjacency graph (per-cell neighbour signatures)
    info = []
    for r in range(h):
        row_sigs = []
        for c in range(w):
            neighbours = []
            for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:
                nr, nc = r+dr, c+dc
                if 0 <= nr < h and 0 <= nc < w:
                    neighbours.append(cells[nr][nc])
            row_sigs.append(tuple(sorted(neighbours)))
        info.append(row_sigs)
    
    # Channel 2: Activation potential (which cells could change)
    # A cell is "activatable" if it's 0 (could be filled) or has mixed neighbours
    activation = []
    for r in range(h):
        row_act = []
        for c in range(w):
            v = cells[r][c]
            if v == 0:
                row_act.append("empty")  # Could be filled
            else:
                # Check if surrounded by same colour (stable) or mixed (unstable)
                n_cols = set()
                for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:
                    nr, nc = r+dr, c+dc
                    if 0 <= nr < h and 0 <= nc < w:
                        n_cols.add(cells[nr][nc])
                if len(n_cols) <= 1:
                    row_act.append("stable")
                else:
                    row_act.append("boundary")
        activation.append(row_act)
    
    # Channel 3: Structural skeleton (border cells, corners, connected components)
    skeleton = []
    for r in range(h):
        row_skel = []
        for c in range(w):
            v = cells[r][c]
            is_border = (r == 0 or r == h-1 or c == 0 or c == w-1)
            # Count same-colour 4-connected neighbours
            same_count = 0
            for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:
                nr, nc = r+dr, c+dc
                if 0 <= nr < h and 0 <= nc < w and cells[nr][nc] == v:
                    same_count += 1
            row_skel.append((is_border, same_count, v))
        skeleton.append(row_skel)
    
    return {
        "mass": mass,
        "info": info,
        "activation": activation,
        "skeleton": skeleton,
        "h": h,
        "w": w,
        "cells": cells,
    }


# ═══════════════════════════════════════════════════════════════════════════════
# Transformation Pattern Learning — what changes between input and output
# ═══════════════════════════════════════════════════════════════════════════════

def learn_transformation(task: ARCTask) -> Dict[str, Any]:
    """
    Learn the transformation from train pairs by analysing MOG channels.
    Instead of learning rules, we learn CHANNEL-WISE TRANSFORMATION PATTERNS.
    """
    patterns = []
    
    for pair in task.train:
        if pair.input.shape != pair.output.shape:
            continue
        
        inp_ch = extract_mog_channels(pair.input)
        out_ch = extract_mog_channels(pair.output)
        h, w = pair.input.height, pair.input.width
        
        # Channel 0 (Mass): colour mapping
        colour_map = {}
        for r in range(h):
            for c in range(w):
                src = pair.input.cells[r][c]
                dst = pair.output.cells[r][c]
                if src != dst:
                    if src in colour_map and colour_map[src] != dst:
                        colour_map = None  # Inconsistent
                        break
                    colour_map[src] = dst
            if colour_map is None:
                break
        
        # Channel 1 (Info): adjacency changes
        adj_changes = []
        for r in range(h):
            for c in range(w):
                if pair.input.cells[r][c] != pair.output.cells[r][c]:
                    inp_neigh = inp_ch["info"][r][c]
                    out_neigh = out_ch["info"][r][c]
                    adj_changes.append({
                        "pos": (r, c),
                        "inp_val": pair.input.cells[r][c],
                        "out_val": pair.output.cells[r][c],
                        "inp_neigh": inp_neigh,
                        "out_neigh": out_neigh,
                    })
        
        # Channel 2 (Activation): what changed
        n_empty_filled = 0
        n_filled_emptied = 0
        n_recoloured = 0
        for r in range(h):
            for c in range(w):
                iv = pair.input.cells[r][c]
                ov = pair.output.cells[r][c]
                if iv != ov:
                    if iv == 0:
                        n_empty_filled += 1
                    elif ov == 0:
                        n_filled_emptied += 1
                    else:
                        n_recoloured += 1
        
        # Channel 3 (Skeleton): structural changes
        # Did the connected component structure change?
        inp_components = _count_components(pair.input)
        out_components = _count_components(pair.output)
        
        patterns.append({
            "colour_map": colour_map,
            "adj_changes": adj_changes,
            "n_empty_filled": n_empty_filled,
            "n_filled_emptied": n_filled_emptied,
            "n_recoloured": n_recoloured,
            "inp_components": inp_components,
            "out_components": out_components,
        })
    
    # Synthesize patterns across train pairs
    synthesis = _synthesize_patterns(patterns)
    return synthesis


def _cross_shift(grid: Grid) -> Optional[Grid]:
    """Cross shift by markers (from v064)."""
    colours = [v for row in grid.cells for v in row if v not in (0, 5)]
    if not colours:
        return None
    main = Counter(colours).most_common(1)[0][0]
    marker_count = sum(1 for row in grid.cells for v in row if v == 5)
    if marker_count <= 0:
        return None
    h, w = grid.height, grid.width
    row_counts = defaultdict(int)
    col_counts = defaultdict(int)
    for r, row in enumerate(grid.cells):
        for c, v in enumerate(row):
            if v == main:
                row_counts[r] += 1
                col_counts[c] += 1
    if not row_counts or not col_counts:
        return None
    horizontal_row = max(row_counts.items(), key=lambda kv: (kv[1], -kv[0]))[0]
    vertical_col = max(col_counts.items(), key=lambda kv: (kv[1], -kv[0]))[0]
    new_row = horizontal_row + marker_count
    new_col = vertical_col - marker_count
    if not (0 <= new_row < h and 0 <= new_col < w):
        return None
    cells = [[0] * w for _ in range(h)]
    for c in range(w):
        cells[new_row][c] = main
    for r in range(h):
        cells[r][new_col] = main
    return Grid(cells)


def _count_components(grid: Grid) -> Dict[int, int]:
    """Count connected components per colour."""
    h, w = grid.height, grid.width
    visited = set()
    components = defaultdict(int)
    
    for r in range(h):
        for c in range(w):
            if (r, c) in visited:
                continue
            colour = grid.cells[r][c]
            if colour == 0:
                continue
            # BFS
            comp_size = 0
            queue = [(r, c)]
            while queue:
                cr, cc = queue.pop()
                if (cr, cc) in visited:
                    continue
                if grid.cells[cr][cc] != colour:
                    continue
                visited.add((cr, cc))
                comp_size += 1
                for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:
                    nr, nc = cr+dr, cc+dc
                    if 0 <= nr < h and 0 <= nc < w and (nr, nc) not in visited:
                        queue.append((nr, nc))
            components[colour] += 1
    
    return dict(components)


def _synthesize_patterns(patterns: List[Dict]) -> Dict[str, Any]:
    """Synthesize transformation patterns across train pairs."""
    if not patterns:
        return {"type": "unknown"}
    
    # Check colour map consistency
    colour_maps = [p["colour_map"] for p in patterns if p["colour_map"] is not None]
    if colour_maps:
        # Check if all pairs have the same colour map
        first = colour_maps[0]
        consistent = all(cm == first for cm in colour_maps)
        if consistent and first:
            return {"type": "global_recolour", "colour_map": first}
    
    # Check if it's a fill task
    total_filled = sum(p["n_empty_filled"] for p in patterns)
    total_emptied = sum(p["n_filled_emptied"] for p in patterns)
    total_recoloured = sum(p["n_recoloured"] for p in patterns)
    
    if total_filled > 0 and total_emptied == 0 and total_recoloured == 0:
        return {"type": "fill_only", "n_filled": total_filled}
    
    if total_emptied > 0 and total_filled == 0 and total_recoloured == 0:
        return {"type": "delete_only", "n_deleted": total_emptied}
    
    # Check for conditional recolour
    # Learn per-(colour, neighbour_signature) → output rules
    rules = {}
    for p in patterns:
        for change in p["adj_changes"]:
            key = (change["inp_val"], change["inp_neigh"])
            if key in rules and rules[key] != change["out_val"]:
                rules = None
                break
            rules[key] = change["out_val"]
        if rules is None:
            break
    
    if rules:
        return {"type": "conditional_recolour", "rules": rules}
    
    # Mixed transformations
    return {
        "type": "mixed",
        "n_filled": total_filled,
        "n_emptied": total_emptied,
        "n_recoloured": total_recoloured,
    }


# ═══════════════════════════════════════════════════════════════════════════════
# Candidate Generation — substrate-native
# ═══════════════════════════════════════════════════════════════════════════════

def generate_candidates(task: ARCTask, pattern: Dict[str, Any]) -> List[Tuple[str, Grid]]:
    """Generate candidate outputs using the learned MOG transformation pattern."""
    test_input = task.test[0].input
    h, w = test_input.height, test_input.width
    candidates = []
    
    if pattern["type"] == "global_recolour" and pattern.get("colour_map"):
        cm = pattern["colour_map"]
        cells = [[cm.get(test_input.cells[r][c], test_input.cells[r][c]) 
                   for c in range(w)] for r in range(h)]
        candidates.append(("global_recolour", Grid(cells)))
    
    elif pattern["type"] == "conditional_recolour" and pattern.get("rules"):
        rules = pattern["rules"]
        cells = [row[:] for row in test_input.cells]
        changed = False
        for r in range(h):
            for c in range(w):
                iv = test_input.cells[r][c]
                n_cols = []
                for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:
                    nr, nc = r+dr, c+dc
                    if 0 <= nr < h and 0 <= nc < w:
                        n_cols.append(test_input.cells[nr][nc])
                key = (iv, tuple(sorted(n_cols)))
                if key in rules:
                    cells[r][c] = rules[key]
                    changed = True
        if changed:
            candidates.append(("conditional_recolour", Grid(cells)))
    
    # Always try: identity
    candidates.append(("identity", Grid([row[:] for row in test_input.cells])))
    
    # Try: fill zeros with most common non-zero colour
    non_zero = [v for row in test_input.cells for v in row if v != 0]
    if non_zero:
        fill = Counter(non_zero).most_common(1)[0][0]
        cells = [[fill if test_input.cells[r][c] == 0 else test_input.cells[r][c] 
                   for c in range(w)] for r in range(h)]
        candidates.append(("fill_common", Grid(cells)))
    
    # Try: gravity down
    cells = [[0]*w for _ in range(h)]
    for c in range(w):
        col = [test_input.cells[r][c] for r in range(h) if test_input.cells[r][c] != 0]
        for i, v in enumerate(col):
            cells[h - len(col) + i][c] = v
    candidates.append(("gravity", Grid(cells)))
    
    # Try: colour map from train pairs (learned per-pair, try each)
    for i, pair in enumerate(task.train):
        if pair.input.shape != pair.output.shape:
            continue
        cm = {}
        consistent = True
        for r in range(pair.input.height):
            for c in range(pair.input.width):
                src = pair.input.cells[r][c]
                dst = pair.output.cells[r][c]
                if src != dst:
                    if src in cm and cm[src] != dst:
                        consistent = False
                        break
                    cm[src] = dst
            if not consistent:
                break
        if consistent and cm:
            cells = [[cm.get(test_input.cells[r][c], test_input.cells[r][c]) 
                       for c in range(w)] for r in range(h)]
            candidates.append((f"pair_{i}_recolour", Grid(cells)))
    
    # Try: uniform fill (all zeros → one colour)
    for pair in task.train:
        if pair.input.shape != pair.output.shape:
            continue
        fills = set()
        for r in range(pair.input.height):
            for c in range(pair.input.width):
                if pair.input.cells[r][c] == 0 and pair.output.cells[r][c] != 0:
                    fills.add(pair.output.cells[r][c])
        if len(fills) == 1:
            fill = next(iter(fills))
            cells = [[fill if test_input.cells[r][c] == 0 else test_input.cells[r][c] 
                       for c in range(w)] for r in range(h)]
            candidates.append(("uniform_fill", Grid(cells)))
            break
    
    # v064 solver strategies (applied to test input)
    for fn, name in [
        (gravity_down, "gravity_down"),
        (local_swap, "local_swap"),
        (colour_center_fill, "colour_center_fill"),
        (column_rank_fill, "column_rank_fill"),
        (marker_fill_85, "marker_fill_85"),
    ]:
        result = fn(test_input)
        if result is not None:
            candidates.append((name, result))
    
    # Conditional recolour (threshold sweep)
    objs = extract_objects(test_input)
    max_size = max((o["size"] for o in objs), default=0)
    for threshold in range(2, max_size + 1):
        for outcome in range(1, 10):
            result = cond_recolour(test_input, threshold, outcome)
            if result is not None:
                candidates.append((f"cond_recolour_{threshold}_{outcome}", result))
    
    # Distance rule
    dist_result = try_distance_diagonal_rule(task)
    if dist_result:
        pred, desc = dist_result
        candidates.append(("distance_rule", pred))
    
    # Interior fill
    interior_fn = learn_multi_interior_fill(task)
    if interior_fn:
        result = interior_fn(test_input)
        if result is not None:
            candidates.append(("interior_fill", result))
    
    # Cross shift by markers
    cross_result = _cross_shift(test_input)
    if cross_result:
        candidates.append(("cross_shift", cross_result))
    
    return candidates


# ═══════════════════════════════════════════════════════════════════════════════
# Verification — hard gate on train pairs
# ═══════════════════════════════════════════════════════════════════════════════

def verify_candidate(task: ARCTask, strategy_name: str, 
                      test_candidate: Grid, pattern: Dict) -> bool:
    """
    Verify that the same transformation produces correct outputs for ALL train pairs.
    This is the HARD GATE — non-negotiable.
    """
    # Special case: distance_rule uses v032's own verification
    if strategy_name == "distance_rule":
        result = try_distance_diagonal_rule(task)
        return result is not None
    
    checked = 0
    for pair in task.train:
        if pair.input.shape != pair.output.shape:
            continue
        
        # Apply the same strategy to this train input
        train_result = _apply_to_grid(pair.input, strategy_name, pattern, task)
        if train_result is None:
            return False
        
        if train_result.cells != pair.output.cells:
            return False
        checked += 1
    
    # Must have checked at least one pair
    return checked > 0


def _apply_to_grid(grid: Grid, strategy_name: str, 
                     pattern: Dict, task: ARCTask) -> Optional[Grid]:
    """Apply a strategy to any grid (for train verification)."""
    h, w = grid.height, grid.width
    
    if strategy_name == "global_recolour":
        cm = pattern.get("colour_map", {})
        if not cm:
            return None
        cells = [[cm.get(grid.cells[r][c], grid.cells[r][c]) 
                   for c in range(w)] for r in range(h)]
        return Grid(cells)
    
    elif strategy_name == "conditional_recolour":
        rules = pattern.get("rules", {})
        if not rules:
            return None
        cells = [row[:] for row in grid.cells]
        changed = False
        for r in range(h):
            for c in range(w):
                iv = grid.cells[r][c]
                n_cols = []
                for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:
                    nr, nc = r+dr, c+dc
                    if 0 <= nr < h and 0 <= nc < w:
                        n_cols.append(grid.cells[nr][nc])
                key = (iv, tuple(sorted(n_cols)))
                if key in rules:
                    cells[r][c] = rules[key]
                    changed = True
        return Grid(cells) if changed else None
    
    elif strategy_name == "identity":
        return Grid([row[:] for row in grid.cells])
    
    elif strategy_name == "fill_common":
        non_zero = [v for row in grid.cells for v in row if v != 0]
        if not non_zero:
            return None
        fill = Counter(non_zero).most_common(1)[0][0]
        cells = [[fill if grid.cells[r][c] == 0 else grid.cells[r][c] 
                   for c in range(w)] for r in range(h)]
        return Grid(cells)
    
    elif strategy_name == "gravity":
        cells = [[0]*w for _ in range(h)]
        for c in range(w):
            col = [grid.cells[r][c] for r in range(h) if grid.cells[r][c] != 0]
            for i, v in enumerate(col):
                cells[h - len(col) + i][c] = v
        return Grid(cells)
    
    elif strategy_name.startswith("pair_") and strategy_name.endswith("_recolour"):
        # Extract pair index
        idx = int(strategy_name.split("_")[1])
        pair = task.train[idx]
        if pair.input.shape != pair.output.shape:
            return None
        cm = {}
        for r in range(pair.input.height):
            for c in range(pair.input.width):
                src = pair.input.cells[r][c]
                dst = pair.output.cells[r][c]
                if src != dst:
                    cm[src] = dst
        cells = [[cm.get(grid.cells[r][c], grid.cells[r][c]) 
                   for c in range(w)] for r in range(h)]
        return Grid(cells)
    
    elif strategy_name == "uniform_fill":
        for pair in task.train:
            if pair.input.shape != pair.output.shape:
                continue
            fills = set()
            for r in range(pair.input.height):
                for c in range(pair.input.width):
                    if pair.input.cells[r][c] == 0 and pair.output.cells[r][c] != 0:
                        fills.add(pair.output.cells[r][c])
            if len(fills) == 1:
                fill = next(iter(fills))
                cells = [[fill if grid.cells[r][c] == 0 else grid.cells[r][c] 
                           for c in range(w)] for r in range(h)]
                return Grid(cells)
        return None
    
    # v064 solver strategies
    v064_fns = {
        "gravity_down": gravity_down,
        "local_swap": local_swap,
        "colour_center_fill": colour_center_fill,
        "column_rank_fill": column_rank_fill,
        "marker_fill_85": marker_fill_85,
    }
    if strategy_name in v064_fns:
        fn = v064_fns[strategy_name]
        return fn(grid)
    
    # Conditional recolour
    if strategy_name.startswith("cond_recolour_"):
        parts = strategy_name.split("_")
        threshold = int(parts[2])
        outcome = int(parts[3])
        return cond_recolour(grid, threshold, outcome)
    
    # Distance rule — can't easily apply to arbitrary grid, skip
    if strategy_name == "distance_rule":
        return None  # Will be handled by direct train verification
    
    # Interior fill
    if strategy_name == "interior_fill":
        fn = learn_multi_interior_fill(task)
        if fn:
            return fn(grid)
        return None
    
    # Cross shift
    if strategy_name == "cross_shift":
        return _cross_shift(grid)
    
    return None


# ═══════════════════════════════════════════════════════════════════════════════
# MOG Attention Scoring — rank verified candidates
# ═══════════════════════════════════════════════════════════════════════════════

def mog_attention_score(input_grid: Grid, output_grid: Grid) -> float:
    """
    Score the transformation using MOG attention weights.
    
    The MOG mass asymmetry defines attention:
    - Changes where M_Mass (colour) changes = high attention
    - Changes where I_Info (position) changes = medium attention  
    - Changes where A_Activation (neighbourhood) changes = low attention
    - Changes where P_Potential (structure) changes = low attention
    
    We want LOW attention = minimal, focused changes = more likely correct.
    """
    h, w = input_grid.height, input_grid.width
    if (h, w) != (output_grid.height, output_grid.width):
        return 0.0
    
    total_weight = 0.0
    change_weight = 0.0
    
    for r in range(h):
        for c in range(w):
            iv = input_grid.cells[r][c]
            ov = output_grid.cells[r][c]
            
            # Compute attention weight for this cell
            # Based on MOG mass asymmetry
            n_cols = []
            for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:
                nr, nc = r+dr, c+dc
                if 0 <= nr < h and 0 <= nc < w:
                    n_cols.append(input_grid.cells[nr][nc])
            
            # Weight based on neighbourhood complexity
            unique_neigh = len(set(n_cols)) if n_cols else 0
            weight = 1.0 + unique_neigh * 0.5  # More complex neighbourhood = higher weight
            
            total_weight += weight
            if iv != ov:
                change_weight += weight
    
    # Lower change ratio = more coherent = better
    coherence = 1.0 - (change_weight / total_weight) if total_weight > 0 else 0.0
    return coherence


# ═══════════════════════════════════════════════════════════════════════════════
# Main Solver
# ═══════════════════════════════════════════════════════════════════════════════

def grids_equal(g1: Grid, g2: Grid) -> bool:
    return g1.height == g2.height and g1.width == g2.width and g1.cells == g2.cells


def solve_task(task: ARCTask) -> Optional[Tuple[Grid, str]]:
    """
    Solve an ARC task using the MOG attention transformer.
    
    1. Learn transformation pattern from train pairs (MOG channel analysis)
    2. Generate candidates using the pattern
    3. Verify each candidate on ALL train pairs (hard gate)
    4. Rank survivors by MOG attention coherence
    5. Return the best
    """
    # Step 1: Learn
    pattern = learn_transformation(task)
    
    # Step 2: Generate
    candidates = generate_candidates(task, pattern)
    
    # Step 3: Verify and score
    verified = []
    for name, candidate in candidates:
        if not verify_candidate(task, name, candidate, pattern):
            continue
        
        score = mog_attention_score(task.test[0].input, candidate)
        verified.append((name, candidate, score))
    
    if not verified:
        return None
    
    # Step 4: Rank by attention coherence (higher = better)
    verified.sort(key=lambda x: -x[2])
    
    best_name, best_grid, best_score = verified[0]
    return best_grid, f"mog_{best_name}"


# ═══════════════════════════════════════════════════════════════════════════════
# Benchmark
# ═══════════════════════════════════════════════════════════════════════════════

def benchmark(batch_dir: str) -> Dict[str, Any]:
    files = sorted(f for f in os.listdir(batch_dir) if f.endswith(".json"))
    results = []
    solver_counts = Counter()
    
    t0 = time.time()
    for fname in files:
        task = load_task(os.path.join(batch_dir, fname), name=os.path.splitext(fname)[0])
        try:
            outcome = solve_task(task)
        except Exception as e:
            outcome = None
        solved = outcome is not None
        solver = outcome[1] if outcome else "none"
        results.append({
            "task_id": task.name,
            "solved": solved,
            "solver": solver,
        })
        if solved:
            solver_counts[solver] += 1
    elapsed = time.time() - t0
    
    solved_n = sum(1 for r in results if r["solved"])
    return {
        "solved": solved_n,
        "total": len(results),
        "pct": round(100.0 * solved_n / max(1, len(results)), 1),
        "solver_counts": dict(solver_counts),
        "elapsed": round(elapsed, 1),
        "results": results,
    }


def main():
    batch = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "training")
    
    print("=" * 72)
    print(" MOG ATTENTION TRANSFORMER v2")
    print("=" * 72)
    print()
    
    summary = benchmark(batch)
    
    print("=" * 72)
    print(f" RESULT: {summary['solved']}/{summary['total']} ({summary['pct']}%)")
    print(f" Time: {summary['elapsed']}s")
    print("=" * 72)
    
    for r in summary["results"]:
        if r["solved"]:
            print(f"  ✓ {r['task_id']}: {r['solver']}")
    
    print(f"\n  Solver distribution:")
    for solver, count in sorted(summary["solver_counts"].items(), 
                                 key=lambda kv: -kv[1]):
        print(f"    {solver}: {count}")
    
    # Save
    report_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 
                                "REPORTS", "mog_transformer_report.json")
    os.makedirs(os.path.dirname(report_path), exist_ok=True)
    with open(report_path, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"\n  Report: {report_path}")


if __name__ == "__main__":
    main()
