#!/usr/bin/env python3
"""Transfer-matrix reflectance of a Sturmian multilayer, against a shuffled control.

Why this script sits *outside* ``overlay/glm_universal``
-------------------------------------------------------
Directive D7 bans floating point inside the package: everything the GLM itself
computes is an integer or a :class:`~fractions.Fraction`.  This script is not
part of the GLM.  It models a *physical measurement* -- light through a
dielectric stack -- and the transfer-matrix method is a complex-valued
floating-point computation.  Keeping it here, in ``studies/scripts/``, is the
honest placement: the exact part of the argument (which layer goes where) is
computed exactly by the package and by Lean, and only the optics is done in
floats.

What it computes
----------------
For each target ``t``:

* the Sturmian bitstream ``b_n = floor((n+1)t) - floor(nt)``, generated by the
  same integer accumulator the GLM uses -- no float anywhere in the sequence;
* a 200-layer quarter-wave stack, bit 0 -> SiO2 (n = 1.46), bit 1 -> TiO2
  (n = 2.40), at a design wavelength of 550 nm;
* the reflectance ``R(lambda)`` at 300 wavelengths across 400-700 nm, by the
  standard 2x2 transfer-matrix method;
* the same stack with its layers **shuffled** by a seeded permutation, which is
  the null model: same bit statistics, no Sturmian order.

The claim being tested is that the spectral structure is carried by the
*order*, not by the bit statistics.  The instrument is the standard deviation
of ``R`` across the sweep: order should give a structured spectrum with a large
spread, the shuffle a flatter one.

Run it with::

    python3 studies/scripts/tmm_null_model.py

It is deterministic: the shuffle is seeded, so two runs agree exactly.
"""

from __future__ import annotations

import cmath
import random
from fractions import Fraction
from statistics import mean, pstdev
from typing import List, Sequence, Tuple

# --- the physical parameters, all stated ------------------------------------
N_A = 1.46          # SiO2
N_B = 2.40          # TiO2
LAMBDA_0 = 550.0    # nm, the design wavelength
D_A = LAMBDA_0 / (4 * N_A)
D_B = LAMBDA_0 / (4 * N_B)
LAYERS = 200
SWEEP = [400.0 + i * (700.0 - 400.0) / 299 for i in range(300)]
SEED = 20260903


def sturmian_bits(target: Fraction, steps: int) -> List[int]:
    """``b_n = floor((n+1)t) - floor(nt)``, by integer accumulator only."""
    a, b = target.numerator, target.denominator
    accumulator, bits = 0, []
    for _ in range(steps):
        accumulator += a
        if accumulator >= b:
            accumulator -= b
            bits.append(1)
        else:
            bits.append(0)
    return bits


def reflectance(bits: Sequence[int], wavelength: float) -> float:
    """``R(lambda)`` of the stack the bits describe, by the transfer matrix."""
    m11 = m22 = complex(1.0, 0.0)
    m12 = m21 = complex(0.0, 0.0)
    for bit in bits:
        n = N_B if bit else N_A
        d = D_B if bit else D_A
        delta = 2 * cmath.pi * n * d / wavelength
        c, s = cmath.cos(delta), cmath.sin(delta)
        a11, a12 = c, -1j * s / n
        a21, a22 = -1j * n * s, c
        m11, m12, m21, m22 = (m11 * a11 + m12 * a21, m11 * a12 + m12 * a22,
                              m21 * a11 + m22 * a21, m21 * a12 + m22 * a22)
    n0 = ns = 1.0  # air on both sides
    numerator = (m11 + m12 * ns) * n0 - (m21 + m22 * ns)
    denominator = (m11 + m12 * ns) * n0 + (m21 + m22 * ns)
    return abs(numerator / denominator) ** 2


def spectrum(bits: Sequence[int]) -> List[float]:
    return [reflectance(bits, wavelength) for wavelength in SWEEP]


def shuffled(bits: Sequence[int], seed: int) -> List[int]:
    out = list(bits)
    random.Random(seed).shuffle(out)
    return out


#: The targets, one per class.  The irrationals are entered as the exact
#: rational the GLM would carry at the stated resolution, so the bitstream is
#: still generated by integer arithmetic.
TARGETS: Tuple[Tuple[str, Fraction, str], ...] = (
    ("1/4", Fraction(1, 4), "dyadic"),
    ("1/3", Fraction(1, 3), "odd prime"),
    ("1/5", Fraction(1, 5), "odd prime"),
    ("1/7", Fraction(1, 7), "odd prime"),
    ("1/11", Fraction(1, 11), "odd prime"),
    ("1/13", Fraction(1, 13), "odd prime"),
    ("sqrt2-1", Fraction(41421356237, 10 ** 11), "irrational"),
    ("phi-1", Fraction(61803398875, 10 ** 11), "irrational"),
    ("pi-3", Fraction(14159265359, 10 ** 11), "irrational"),
)


def main() -> None:
    print(f"# TMM null-model control  ({LAYERS} layers, "
          f"{len(SWEEP)} wavelengths, seed {SEED})")
    print()
    print("| target | class | ordered mean R | shuffled mean R | "
          "ordered std R | shuffled std R | structure lost? |")
    print("|---|---|---|---|---|---|---|")
    lost = 0
    for name, target, kind in TARGETS:
        bits = sturmian_bits(target, LAYERS)
        ordered = spectrum(bits)
        control = spectrum(shuffled(bits, SEED))
        o_mean, o_std = mean(ordered), pstdev(ordered)
        s_mean, s_std = mean(control), pstdev(control)
        verdict = "YES" if s_std < o_std else "no"
        lost += verdict == "YES"
        print(f"| {name} | {kind} | {o_mean:.4f} | {s_mean:.4f} | "
              f"{o_std:.4f} | {s_std:.4f} | **{verdict}** |")
    print()
    print(f"{lost}/{len(TARGETS)} targets lose spectral spread under the "
          f"shuffle.")


if __name__ == "__main__":
    main()
