/-
# The recipe as an object: a domain description, and the path it forces

Every capability in this development was built by hand from one recipe: a
**register** of carriers whose coordinates are derived from something already
held; a **reading** over them; an **audit** of what the reading gains and
whether it gives anything up; a **query** that answers where the register
decides and refuses where it does not.  Comparison classes, harmonics and
prices are all that recipe, applied three times.

This file makes the recipe itself the object.  A `Spec` is a *description* of a
domain: the coordinates it holds, how each one is derived from an object, and
which of them recover the object.  Everything the recipe used to produce by
hand is then a function of the description:

* `Spec.readingOn` — the reading generated by a selection of coordinates, as a
  `Layer` in the sense of `Layers.lean`, so the whole widening machinery
  applies without knowing what the domain is about;
* `readingOn_mono` — widening a selection never gives anything up, and
  `readingOn_append_least` — the widened reading is exactly the cumulative
  layer of its parts, in the sense of `Cumulative.lean`;
* `boundary_readingOn_nonempty_iff` — what a widening *gains* is exactly a pair
  the narrower selection conflates and a new coordinate splits;
* `lossless_full_of_keys` and `rebuild_encode` — the read-back: a description
  whose keys determine the object gives a lossless encoding and an exact
  inverse;
* `answer`, `answer_eq_none_iff` — the query surface and its refusal boundary,
  both read off the description: a coordinate the description does not derive
  is refused, and the refusal is decidable;
* `encode_congr`, `indist_congr`, `answer_congr` — **regeneration**: two
  descriptions that agree on the coordinates agree on the carriers, on the
  reading, and on every answer.  This is the formal content of the claim that
  a domain can be deleted and regenerated from its description with its
  measured figures unchanged: any figure computed from the carriers, or from
  the reading's classes, is a function of the description alone.

`ratioSpec` at the end instantiates the whole of it on the harmonic register's
description — an interval as an exact ratio — where the keys are the numerator
and the denominator, the derived coordinate `product_complexity` is Tenney
height, and `cents` is a coordinate no description derives, so it is refused.
-/
import RequestProject.GLM.Cumulative

namespace GLM.Recipe

open GLM.Info GLM.Info.Layer

universe u v

/-- A **domain description**.  `coords` names the coordinates the domain holds,
`derive` says how each one is computed from an object — nothing is stored
beside the object, everything is derived from it — and `keys` names the
coordinates from which the object is recovered. -/
structure Spec (Obj : Type u) (Val : Type v) where
  /-- The coordinates the description holds, in order. -/
  coords : List String
  /-- How each coordinate is derived from an object. -/
  derive : String → Obj → Val
  /-- The coordinates that recover the object. -/
  keys : List String

namespace Spec

variable {Obj : Type u} {Val : Type v} (s t : Spec Obj Val)

/-- The carrier of an object: one value per coordinate, in the order the
description gives them. -/
def encode (o : Obj) : List Val := s.coords.map (fun c => s.derive c o)

/-- The reading generated by a selection of coordinates: a layer in the sense
of `Layers.lean`, whose view is what those coordinates say. -/
def readingOn (sel : List String) : Layer.{u, v} Obj where
  View := List Val
  perceive o := sel.map (fun c => s.derive c o)

/-- The reading that sees every coordinate the description holds. -/
def full : Layer.{u, v} Obj := s.readingOn s.coords

/-- The reading that sees only the keys. -/
def keyReading : Layer.{u, v} Obj := s.readingOn s.keys

@[simp] theorem readingOn_perceive (sel : List String) (o : Obj) :
    (s.readingOn sel).perceive o = sel.map (fun c => s.derive c o) := rfl

@[simp] theorem full_perceive (o : Obj) : s.full.perceive o = s.encode o := rfl

/-! ## Reading a selection coordinate by coordinate -/

/-- Two objects are the same to a selection exactly when every coordinate of
the selection agrees on them. -/
theorem indist_readingOn_iff {sel : List String} {a b : Obj} :
    (s.readingOn sel).Indist a b ↔ ∀ c ∈ sel, s.derive c a = s.derive c b := by
  constructor
  · intro h c hc
    have := List.map_inj_left.mp h
    exact this c hc
  · intro h
    exact List.map_inj_left.mpr h

/-! ## Widening a selection -/

/-- **Widening gives nothing up.**  A selection that contains another refines
the reading generated by it. -/
theorem readingOn_mono {sel sel' : List String} (h : sel ⊆ sel') :
    Refines (s.readingOn sel') (s.readingOn sel) := by
  intro a b hab
  rw [indist_readingOn_iff] at hab ⊢
  exact fun c hc => hab c (h hc)

/-- Appending two selections reads both. -/
theorem indist_readingOn_append {sel sel' : List String} {a b : Obj} :
    (s.readingOn (sel ++ sel')).Indist a b ↔
      (s.readingOn sel).Indist a b ∧ (s.readingOn sel').Indist a b := by
  simp only [indist_readingOn_iff, List.mem_append]
  constructor
  · intro h
    exact ⟨fun c hc => h c (Or.inl hc), fun c hc => h c (Or.inr hc)⟩
  · rintro ⟨h₁, h₂⟩ c (hc | hc)
    · exact h₁ c hc
    · exact h₂ c hc

/-- **The widened reading is the cumulative layer of its parts.**  Reading two
selections at once is exactly the least reading that keeps both, in the sense
of `Cumulative.lean` — so the generic path produces a widening, never a
replacement. -/
theorem readingOn_append_least {sel sel' : List String}
    {N : Layer.{u, v} Obj}
    (h₁ : Refines N (s.readingOn sel)) (h₂ : Refines N (s.readingOn sel')) :
    Refines N (s.readingOn (sel ++ sel')) := by
  intro a b hab
  exact (indist_readingOn_append s).mpr ⟨h₁ a b hab, h₂ a b hab⟩

/-- The widened reading refines both parts, so appending is a widening. -/
theorem readingOn_append_refines_left (sel sel' : List String) :
    Refines (s.readingOn (sel ++ sel')) (s.readingOn sel) :=
  s.readingOn_mono (List.subset_append_left sel sel')

theorem readingOn_append_refines_right (sel sel' : List String) :
    Refines (s.readingOn (sel ++ sel')) (s.readingOn sel') :=
  s.readingOn_mono (List.subset_append_right sel sel')

/-! ## The audit: what a widening gains -/

/-- **What a widening gains is exactly a pair the coordinates it adds split.**
The boundary between a selection and a wider one is non-empty precisely when
some added coordinate tells apart two objects the narrower selection
conflates. -/
theorem boundary_readingOn_nonempty_iff {sel sel' : List String} :
    (Boundary (s.readingOn sel') (s.readingOn sel)).Nonempty ↔
      ∃ a b : Obj, (∀ c ∈ sel, s.derive c a = s.derive c b) ∧
        ∃ c ∈ sel', s.derive c a ≠ s.derive c b := by
  constructor
  · rintro ⟨⟨a, b⟩, hlow, hhigh⟩
    refine ⟨a, b, (indist_readingOn_iff s).mp hlow, ?_⟩
    by_contra hcon
    push_neg at hcon
    exact hhigh ((indist_readingOn_iff s).mpr hcon)
  · rintro ⟨a, b, hlow, c, hc, hne⟩
    refine ⟨(a, b), (indist_readingOn_iff s).mpr hlow, ?_⟩
    intro hhigh
    exact hne ((indist_readingOn_iff s).mp hhigh c hc)

/-- A selection **determines** the objects when no two distinct objects agree
on all of it: the reading it generates is lossless. -/
def Determines (sel : List String) : Prop :=
  ∀ a b : Obj, (∀ c ∈ sel, s.derive c a = s.derive c b) → a = b

theorem lossless_readingOn_iff (sel : List String) :
    (s.readingOn sel).Lossless ↔ s.Determines sel := by
  constructor
  · intro h a b hab
    exact h ((indist_readingOn_iff s).mpr hab)
  · intro h a b hab
    exact h a b ((indist_readingOn_iff s).mp hab)

/-- **The read-back.**  If the keys determine the objects and are among the
coordinates, the whole carrier is lossless: the encoding can be inverted, and
no derived coordinate can disagree with it. -/
theorem lossless_full_of_keys (hk : s.keys ⊆ s.coords)
    (hdet : s.Determines s.keys) : s.full.Lossless := by
  intro a b hab
  exact hdet a b ((indist_readingOn_iff s).mp (s.readingOn_mono hk a b hab))

/-- The encoding of a description whose keys determine the objects is
injective. -/
theorem encode_injective_of_keys (hk : s.keys ⊆ s.coords)
    (hdet : s.Determines s.keys) : Function.Injective s.encode :=
  s.lossless_full_of_keys hk hdet

/-- **The inverse is a function of the description.**  A `rebuild` that inverts
the key reading inverts it on every object, and any two such agree. -/
theorem rebuild_encode {rebuild : List Val → Obj}
    (h : ∀ o : Obj, rebuild (s.keyReading.perceive o) = o) (o : Obj) :
    rebuild (s.keys.map (fun c => s.derive c o)) = o := h o

/-! ## The query surface, and the refusal boundary -/

/-- The answer the description gives: the value of a coordinate it derives, or
**nothing** — a refusal — for a coordinate it does not hold. -/
def answer (c : String) (o : Obj) : Option Val :=
  if c ∈ s.coords then some (s.derive c o) else none

theorem answer_eq_some_iff {c : String} {o : Obj} {v : Val} :
    s.answer c o = some v ↔ c ∈ s.coords ∧ s.derive c o = v := by
  unfold answer
  by_cases hc : c ∈ s.coords
  · simp [hc, eq_comm]
  · simp [hc]

/-- **The refusal boundary is exactly the unheld coordinates**, and it is
decidable: the description says what it can answer, so nothing has to be
guessed and nothing can be invented. -/
theorem answer_eq_none_iff {c : String} {o : Obj} :
    s.answer c o = none ↔ c ∉ s.coords := by
  unfold answer
  by_cases hc : c ∈ s.coords <;> simp [hc]

theorem answer_of_mem {c : String} (hc : c ∈ s.coords) (o : Obj) :
    s.answer c o = some (s.derive c o) := by
  simp [answer, hc]

/-! ## Regeneration: the description is the domain -/

variable {s t}

/-- Two descriptions that hold the same coordinates and derive them the same
way encode every object identically. -/
theorem encode_congr (hc : s.coords = t.coords)
    (hd : ∀ c ∈ s.coords, ∀ o : Obj, s.derive c o = t.derive c o) (o : Obj) :
    s.encode o = t.encode o := by
  unfold encode
  rw [← hc]
  exact List.map_congr_left (fun c hcm => hd c hcm o)

/-- They also generate the same reading: the classes a domain's layer resolves
are a function of its description, so any figure counted off those classes is
unchanged by regenerating the domain from it. -/
theorem indist_congr {sel : List String}
    (hd : ∀ c ∈ sel, ∀ o : Obj, s.derive c o = t.derive c o) (a b : Obj) :
    (s.readingOn sel).Indist a b ↔ (t.readingOn sel).Indist a b := by
  simp only [indist_readingOn_iff]
  constructor
  · intro h c hc
    rw [← hd c hc a, ← hd c hc b]
    exact h c hc
  · intro h c hc
    rw [hd c hc a, hd c hc b]
    exact h c hc

/-- And they answer identically — including refusing identically. -/
theorem answer_congr (hc : s.coords = t.coords)
    (hd : ∀ c ∈ s.coords, ∀ o : Obj, s.derive c o = t.derive c o)
    (c : String) (o : Obj) : s.answer c o = t.answer c o := by
  unfold answer
  by_cases hcm : c ∈ s.coords
  · rw [if_pos hcm, if_pos (hc ▸ hcm), hd c hcm o]
  · rw [if_neg hcm, if_neg (hc ▸ hcm)]

end Spec

/-! ## The description of one real domain

The harmonic register, as a description: an interval is an exact positive
ratio, its keys are the numerator and the denominator, and every other
coordinate is derived from them.  `product_complexity` is Tenney height before
anyone takes a logarithm.
-/

/-- The harmonic register's description, cut down to three coordinates: the two
keys and one derived quantity. -/
def ratioSpec : Spec ℚ ℤ where
  coords := ["numerator", "denominator", "product_complexity"]
  derive c q :=
    if c = "numerator" then q.num
    else if c = "denominator" then (q.den : ℤ)
    else if c = "product_complexity" then q.num * (q.den : ℤ)
    else 0
  keys := ["numerator", "denominator"]

theorem ratioSpec_keys_subset : ratioSpec.keys ⊆ ratioSpec.coords := by
  intro c hc
  fin_cases hc <;> simp [ratioSpec]

/-- The keys determine an interval: a rational is its numerator and its
denominator. -/
theorem ratioSpec_determines_keys : ratioSpec.Determines ratioSpec.keys := by
  intro a b h
  have hn : a.num = b.num := by
    simpa [ratioSpec] using h "numerator" (by simp [ratioSpec])
  have hd : (a.den : ℤ) = (b.den : ℤ) := by
    simpa [ratioSpec] using h "denominator" (by simp [ratioSpec])
  exact Rat.ext hn (Nat.cast_injective hd)

/-- **The carrier is lossless**: the description's own read-back recovers the
interval, so no derived coordinate can disagree with it. -/
theorem ratioSpec_full_lossless : ratioSpec.full.Lossless :=
  ratioSpec.lossless_full_of_keys ratioSpec_keys_subset ratioSpec_determines_keys

/-- The derived coordinate alone is **not** a reading of the domain: Tenney
height conflates `3/2` with `6`. -/
theorem ratioSpec_product_not_lossless :
    ¬ (ratioSpec.readingOn ["product_complexity"]).Lossless := by
  intro h
  have : (3 : ℚ) / 2 = (6 : ℚ) := by
    refine h ((Spec.indist_readingOn_iff ratioSpec).mpr ?_)
    intro c hc
    have hc' : c = "product_complexity" := by simpa using hc
    subst hc'
    simp only [ratioSpec, String.reduceEq, if_false]
    norm_num
  norm_num at this

/-- Adding the derived coordinate to the keys gains nothing — the keys already
decide — which is the audit answering `no widening here`. -/
theorem ratioSpec_boundary_full_keys_empty :
    Boundary ratioSpec.full ratioSpec.keyReading = ∅ := by
  rw [Set.eq_empty_iff_forall_notMem]
  rintro ⟨a, b⟩ ⟨hlow, hhigh⟩
  exact hhigh (congrArg _ (ratioSpec_determines_keys a b
    ((Spec.indist_readingOn_iff ratioSpec).mp hlow)))

/-- Widening from Tenney height alone to the full description **does** gain: the
pair it conflates is split. -/
theorem ratioSpec_boundary_full_product_nonempty :
    (Boundary ratioSpec.full (ratioSpec.readingOn ["product_complexity"])).Nonempty := by
  refine ⟨((3 : ℚ) / 2, (6 : ℚ)), ?_, ?_⟩
  · refine (Spec.indist_readingOn_iff ratioSpec).mpr ?_
    intro c hc
    have hc' : c = "product_complexity" := by simpa using hc
    subst hc'
    simp only [ratioSpec, String.reduceEq, if_false]
    norm_num
  · intro h
    have := (Spec.indist_readingOn_iff ratioSpec).mp h "numerator" (by simp [ratioSpec])
    simp only [ratioSpec, if_true] at this
    norm_num at this

/-- **A coordinate the description does not derive is refused.**  There is no
`cents` in this register — a cent is a logarithm — so the query surface says
so rather than inventing one. -/
theorem ratioSpec_refuses_cents (q : ℚ) : ratioSpec.answer "cents" q = none := by
  rw [Spec.answer_eq_none_iff]
  simp [ratioSpec]

/-- And a coordinate it does derive is answered exactly. -/
theorem ratioSpec_answers_product :
    ratioSpec.answer "product_complexity" ((3 : ℚ) / 2) = some 6 := by
  rw [Spec.answer_of_mem _ (by simp [ratioSpec])]
  simp only [ratioSpec, String.reduceEq, if_false]
  norm_num

end GLM.Recipe
