"""exp7_invariance_check.py -- reproduce Experiment 3 of exp7_cube_surface.py.

Question: is there ANY Golay code on the 24 cells of the cube's surface that a
given subgroup of the cube group preserves?

The search is the one in `exp7_cube_surface.invariant_golay_codes`: enumerate
the cyclic G-modules generated by weight-8 vectors whose words all have a
Golay-legal weight, close under sums with the same pruning, keep the
12-dimensional results, and test each for being a Golay code (4096 words,
minimum weight 8).  It assumes only that an extended Golay code is spanned by
its octads and that its weights lie in {0, 8, 12, 16, 24}.

Subgroups tested, all inside the signed permutation group B3 of order 48
(`sigma` permutes the axes, `eps` flips their signs):

    O_h  everything                                      48   exhaustive
    T_d  prod(eps) = +1                                  24   exhaustive
    O    the rotations, sign(sigma)*prod(eps) = +1        24   stops at the first hit
    T_h  sigma even                                       24   stops at the first hit

The two negative claims are searched exhaustively; for the two positive ones a
single witness is enough, and the search stops as soon as it has one (the full
closure is combinatorially large once invariant codes exist).

Run:  python3 glm_clean/exp7_invariance_check.py
Writes glm_clean/results/exp7_invariance.json and prints a summary table.

NOTE.  This is a Python search, not a Lean proof -- but it is no longer the
authority for any claim.  All four rows are now theorems of the Lean
development, proved independently of this script and agreeing with it:

    O_h  GolayInv.no_Oh_invariant_golay        (RequestProject/GolayInvolution.lean)
    T_d  GolayInv.no_Td_invariant_golay        (RequestProject/GolayInvolution.lean)
    O    GolayInv.exists_O_invariant_golay     (RequestProject/GolayTh.lean)
    T_h  GolayInv.exists_Th_invariant_golay    (RequestProject/GolayTh.lean)

The two negative rows are proved by a parity count on a single diagonal mirror,
so they hold for every Golay code and every placement, not only for the ones
this search reaches.  The script is kept because it is fast, re-runnable, and a
useful independent check.
"""

from __future__ import annotations

import itertools
import json
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from exp7_cube_surface import (  # noqa: E402
    AXES,
    cell_permutation,
    good_module,
    gspan_fast,
    group_elements,
    is_golay,
    make_apply,
    perm_tables,
    popcount,
    reduce_basis,
)


def perm_sign(sigma) -> int:
    s = 1
    for i in AXES:
        for j in range(i + 1, 3):
            if sigma[i] > sigma[j]:
                s = -s
    return s


def eps_prod(eps) -> int:
    return eps[0] * eps[1] * eps[2]


SUBGROUPS = [
    ("O_h", lambda g: True, True),
    ("T_d", lambda g: eps_prod(g[1]) > 0, True),
    ("O", lambda g: perm_sign(g[0]) * eps_prod(g[1]) > 0, False),
    ("T_h", lambda g: perm_sign(g[0]) > 0, False),
]


def octad_modules(applies):
    """The cyclic G-modules generated by a weight-8 vector, Golay-legal ones only."""
    seen_vec = set()
    mods = set()
    for v in range(1 << 24):
        if popcount(v) != 8 or v in seen_vec:
            continue
        orb = {f(v) for f in applies}
        seen_vec |= orb
        b = gspan_fast(v, applies)
        if good_module(b):
            mods.add(b)
    return sorted(mods, key=len)


def search(perms, exhaustive: bool):
    """Golay codes invariant under `perms`.

    Exhaustive: returns them all.  Otherwise returns as soon as one is found.
    """
    applies = [make_apply(perm_tables(p)) for p in perms]
    mods = octad_modules(applies)
    found = []
    frontier = {m: None for m in mods}
    seen = dict(frontier)
    for m in mods:
        if len(m) == 12 and is_golay(m):
            found.append(m)
            if not exhaustive:
                return found, len(mods)
    while frontier:
        nxt = {}
        for s in frontier:
            if len(s) == 12:
                continue
            for m in mods:
                b = reduce_basis(list(s) + list(m))
                if b in seen or not good_module(b):
                    continue
                seen[b] = None
                if len(b) == 12:
                    if is_golay(b):
                        found.append(b)
                        if not exhaustive:
                            return found, len(mods)
                else:
                    nxt[b] = None
        frontier = nxt
    return found, len(mods)


def main() -> None:
    elements = group_elements()
    report = {}
    for label, pred, exhaustive in SUBGROUPS:
        gs = [g for g in elements if pred(g)]
        perms = [cell_permutation(g) for g in gs]
        t0 = time.time()
        codes, n_mods = search(perms, exhaustive)
        dt = time.time() - t0
        report[label] = {
            "order": len(gs),
            "exhaustive": exhaustive,
            "cyclic_octad_modules": n_mods,
            "invariant_golay_codes": len(codes) if exhaustive else ">= %d" % len(codes),
            "example_basis": list(codes[0]) if codes else None,
            "seconds": round(dt, 1),
        }
        verdict = (
            f"none exist (exhaustive)"
            if exhaustive and not codes
            else f"{len(codes)} found (exhaustive)"
            if exhaustive
            else "at least one exists"
        )
        print(f"{label:4s} order {len(gs):2d}   {verdict:26s} ({dt:.0f}s)", flush=True)
    out = os.path.join(HERE, "results", "exp7_invariance.json")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=1)
    print(f"\nwritten to {out}")


if __name__ == "__main__":
    main()
