"""``glm_universal.substrate.norm_family`` -- the construction ladder as a
complete power-of-two family, indexed by minimum squared norm.

Why the ladder needed re-indexing
---------------------------------
:mod:`glm_universal.substrate.construction_ladder` names eleven rungs, and it
names them after *constructions*: ``Z``, ``D``, ``A``, ``B``, ``C`` and a
handful of scalings of them.  That list is a list of the objects somebody
happened to write down, and its minimum norms come out as

    1, 2, 4, 4, 8, 16, 16, 32, 32, 32, 64

-- three rungs at norm 32, two at 16, two at 4, and nothing at all above 64.
A reading escalates by *tolerance*, and tolerance is the minimum norm: a rung
of minimum norm ``m`` returns the right point for any offset of squared length
below ``m/4``.  So the index a reader wants is the norm, and the family it
wants is one rung at **every** power of two.

That family exists, and this module generates it.  The arithmetic that makes it
work is stated once: **doubling a lattice multiplies every squared norm by
four**, so a single construction scaled by powers of two only ever visits
norms ``m, 4m, 16m, ...`` -- one residue class of the powers of two, never all
of them.  A complete power-of-two family therefore *needs* the constructions
interleaved with the scalings:

======  ==========  ====================================================
norm    rung        why it is there
======  ==========  ====================================================
1       ``Z``       the integer grid
2       ``D``       one parity condition, and the norm doubles
4       ``A/2``     the unscaled Golay lift ``G`` -- the Z-family's ``2Z``
                    is also here, and is the less dense of the two
8       ``2D``      the checkerboard doubled
16      ``A``       Construction ``A`` = ``2G``
32      ``C``       the Leech lattice (``B`` and ``4D`` also sit here)
64      ``2A``      and from here the pattern repeats every two steps,
128     ``2C``      the scalings of ``A``/``B``/``C`` alternating with
256     ``4A``      each other: doubling moves a rung two places up the
512     ``4C``      family, so two interleaved constructions fill it
1024    ``8A``
2048    ``8C``
======  ==========  ====================================================

Nothing above is stored: :func:`family_rungs` generates the keys,
:func:`norm_rows` generates each rung's membership test, theta series,
covolume, kissing number and place in the containment order, and
:func:`completeness` checks that every power of two from 1 to the requested
bound carries at least one rung -- a gap would be reported, not glossed.

Two orders through the family
-----------------------------
:data:`DENSEST_BY_NORM` takes, at each norm, the rung with the largest kissing
number (ties to the smaller covolume): the densest packing available at that
tolerance.  It contains the Leech lattice and it is **not** a containment
chain, because ``C`` and ``A`` are incomparable -- which is the diamond
``GLM.ConstructionLadder.ladder_not_chain`` proves.

:data:`NORM_CHAIN` takes, at each norm, a rung that really does sit inside the
rung below it, so the whole family is a single tower

    ``8B ⊂ 4B ⊂ ... ⊂ 2A ⊂ B ⊂ A ⊂ 2D ⊂ G ⊂ D ⊂ Z``

-- one rung per power of two, with every step derived and every step proved in
``RequestProject/GLM/NormFamily.lean``.  :func:`chain_report` checks the chain
here as well, rung by rung, rather than asserting it.

Exactness
---------
Integers throughout: norms, covolume exponents, kissing numbers and theta
coefficients.  No float is constructed anywhere in this module.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Sequence, Tuple

from . import construction_ladder as CL

__all__ = [
    "FAMILY_BASES", "MAX_LOG2", "family_rungs", "rungs_at_norm",
    "densest_at_norm", "densest_by_norm", "DENSEST_BY_NORM", "chain_rung", "norm_chain", "NORM_CHAIN",
    "norm_rows", "completeness", "chain_report", "containment_order",
    "norm_family_report", "scaling_rule",
]

#: The bases the family is generated from, finest first.  ``A`` appears at
#: exponent ``-1`` as well (the unscaled Golay lift ``G``), which is why the
#: family has a rung at norm 4.
FAMILY_BASES: Tuple[str, ...] = ("Z", "D", "A", "B", "C")

#: How far the family is generated by default: norms ``2^0`` to ``2^MAX_LOG2``.
MAX_LOG2: int = 11


def scaling_rule() -> Dict[str, object]:
    """The arithmetic the family rests on, recomputed rather than asserted.

    Doubling a lattice multiplies every squared norm by four and every
    covolume by ``2^24``, and moves no vector -- so the kissing number is
    unchanged.  Each of the three is checked here against the generated rung
    specifications rather than quoted from the docstring.
    """
    rows: List[Dict[str, object]] = []
    for base in FAMILY_BASES:
        low = CL.rung_spec(base)
        high = CL.rung_spec(CL.scaled_key(base, 1))
        rows.append({
            "base": base,
            "doubled": high.key,
            "norm": (low.minimum_norm, high.minimum_norm),
            "norm_times_four": high.minimum_norm == 4 * low.minimum_norm,
            "covolume_log2": (low.covolume_log2, high.covolume_log2),
            "covolume_plus_24": high.covolume_log2 == low.covolume_log2 + 24,
            "kissing": (low.kissing, high.kissing),
            "kissing_unchanged": high.kissing == low.kissing,
        })
    return {
        "rows": tuple(rows),
        "norm_times_four": all(row["norm_times_four"] for row in rows),
        "covolume_plus_24": all(row["covolume_plus_24"] for row in rows),
        "kissing_unchanged": all(row["kissing_unchanged"] for row in rows),
        "consequence": (
            "a single construction scaled by powers of two visits the norms "
            "m, 4m, 16m, ... -- one residue class of the powers of two -- so "
            "a complete power-of-two family needs the Z/D/A-type rungs "
            "interleaved with the scalings"),
        "lean": "GLM.NormFamily.dbl_normSq, GLM.NormFamily.scaled_normSq",
    }


def family_rungs(max_log2: int = MAX_LOG2) -> Tuple[str, ...]:
    """Every rung of the family with minimum norm at most ``2**max_log2``.

    Generated from the bases and the scaling, coarsest first; a rung is a key
    :func:`glm_universal.substrate.construction_ladder.rung_spec` builds on
    demand, so nothing here is a stored table.
    """
    if max_log2 < 0:
        raise ValueError("norm_family: max_log2 must be non-negative")
    bound = 1 << max_log2
    keys: List[str] = []
    for base in FAMILY_BASES:
        lowest = -1 if base == "A" else 0
        for exponent in range(lowest, CL.MAX_EXPONENT + 1):
            key = CL.scaled_key(base, exponent)
            spec = CL.rung_spec(key)
            if spec.minimum_norm > bound:
                break
            keys.append(key)
    return tuple(sorted(keys, key=lambda key: (-CL.rung_spec(key).minimum_norm,
                                               CL.rung_spec(key).covolume_log2,
                                               key)))


def rungs_at_norm(norm: int, max_log2: int = MAX_LOG2) -> Tuple[str, ...]:
    """Every generated rung whose minimum squared norm is exactly ``norm``.

    Densest first: the largest kissing number, ties to the smaller covolume.
    """
    at = [key for key in family_rungs(max_log2)
          if CL.rung_spec(key).minimum_norm == norm]
    return tuple(sorted(at, key=lambda key: (-CL.rung_spec(key).kissing,
                                             CL.rung_spec(key).covolume_log2,
                                             key)))


def densest_at_norm(norm: int, max_log2: int = MAX_LOG2) -> Optional[str]:
    """The densest rung at this norm, or ``None`` if the family has none."""
    at = rungs_at_norm(norm, max_log2)
    return at[0] if at else None


def densest_by_norm(max_log2: int = MAX_LOG2) -> Tuple[str, ...]:
    """One rung per power-of-two norm, finest first: the densest at each."""
    out: List[str] = []
    for power in range(max_log2 + 1):
        key = densest_at_norm(1 << power, max_log2)
        if key is not None:
            out.append(key)
    return tuple(out)


#: One rung per power-of-two norm, finest first: the densest packing available
#: at each tolerance.  Generated, not declared.
DENSEST_BY_NORM: Tuple[str, ...] = densest_by_norm()


def chain_rung(power: int) -> str:
    """The chain's rung at norm ``2**power``, generated from the scaling rule.

    Below norm 16 the family's only rungs are the grid, the checkerboard and
    the Golay lift; from norm 16 up, doubling moves a rung *two* powers, so two
    interleaved constructions -- ``A`` and ``B`` -- fill every power in turn:
    an even power takes ``2^k A`` and an odd power ``2^k B``.
    """
    if power < 0:
        raise ValueError("norm_family: power must be non-negative")
    if power == 0:
        return "Z"
    if power == 1:
        return "D"
    if power == 3:
        return CL.scaled_key("D", 1)
    if power % 2 == 0:
        return CL.scaled_key("A", (power - 4) // 2)
    return CL.scaled_key("B", (power - 5) // 2)


def norm_chain(max_log2: int = MAX_LOG2) -> Tuple[str, ...]:
    return tuple(chain_rung(power) for power in range(max_log2 + 1))


#: One rung per power-of-two norm, finest first, chosen so that the family is
#: a single containment chain.  :func:`chain_report` checks every step.
NORM_CHAIN: Tuple[str, ...] = norm_chain()


def containment_order(keys: Sequence[str]) -> Tuple[Dict[str, object], ...]:
    """Each rung's place in the containment order of the given family.

    ``inside`` is what the rung sits inside, ``holds`` what sits inside it, and
    ``incomparable`` the rungs neither contains -- each with a witness vector
    available from
    :func:`glm_universal.substrate.construction_ladder.containment_witness`.
    """
    out: List[Dict[str, object]] = []
    for key in keys:
        inside = [other for other in keys
                  if other != key and CL.contains(key, other) is not None]
        holds = [other for other in keys
                 if other != key and CL.contains(other, key) is not None]
        incomparable = [other for other in keys
                        if other != key and other not in inside
                        and other not in holds]
        out.append({
            "rung": key,
            "minimum_norm": CL.rung_spec(key).minimum_norm,
            "inside": tuple(inside),
            "holds": tuple(holds),
            "incomparable": tuple(incomparable),
            "witness": (CL.containment_witness(key, incomparable[0])
                        if incomparable else None),
        })
    return tuple(out)


def norm_rows(max_log2: int = MAX_LOG2,
              order: int = 64) -> Tuple[Dict[str, object], ...]:
    """One row per power-of-two norm, everything on it generated.

    For each rung: its membership conditions, its covolume, its kissing
    number, the head of its theta series -- and the check that the declared
    minimum norm and kissing number agree with the series the module generates
    for it.  Each rung's series is taken to twice its own minimum norm, or to
    ``order``, whichever is further: a scaled rung's series is its base rung's
    with the exponents stretched, so reaching a large norm on a coarse rung
    costs no more than reaching a small one on its base.
    """
    rows: List[Dict[str, object]] = []
    keys = family_rungs(max_log2)
    for power in range(max_log2 + 1):
        norm = 1 << power
        at = rungs_at_norm(norm, max_log2)
        entries: List[Dict[str, object]] = []
        for key in at:
            spec = CL.rung_spec(key)
            reach = max(order, norm * 2, 4)
            series = CL.theta_series(key, reach)
            generated_min = series["minimum_norm"]
            entries.append({
                "rung": key,
                "title": spec.title,
                "conditions": spec.conditions,
                "base": spec.base,
                "exponent": spec.exponent,
                "minimum_norm": spec.minimum_norm,
                "kissing": spec.kissing,
                "covolume_log2": spec.covolume_log2,
                "shells": series["shells"][:4],
                "series_reaches_minimum": generated_min is not None,
                "series_agrees": (generated_min == spec.minimum_norm
                                  and series["kissing"] == spec.kissing),
            })
        rows.append({
            "power": power,
            "norm": norm,
            "rungs": tuple(entries),
            "count": len(entries),
            "densest": densest_at_norm(norm, max_log2),
            "chain": chain_rung(power),
            "chain_is_in_family": chain_rung(power) in keys,
        })
    return tuple(rows)


def completeness(max_log2: int = MAX_LOG2) -> Dict[str, object]:
    """Is the power-of-two family complete, and what fills each norm?

    A norm with no rung is a **gap**, and a gap is reported rather than
    excused: the family is complete exactly when every power of two from 1 to
    ``2**max_log2`` carries at least one generated rung.
    """
    filled: List[Dict[str, object]] = []
    gaps: List[int] = []
    for power in range(max_log2 + 1):
        norm = 1 << power
        at = rungs_at_norm(norm, max_log2)
        if not at:
            gaps.append(norm)
        filled.append({"power": power, "norm": norm, "rungs": at,
                       "count": len(at),
                       "bases": tuple(sorted({CL.scale_of(key)[0]
                                              for key in at}))})
    interleaved = sorted({CL.scale_of(row["chain"])[0]        # type: ignore[arg-type]
                          for row in norm_rows(max_log2, order=4)})
    return {
        "max_log2": max_log2,
        "norms": tuple(1 << power for power in range(max_log2 + 1)),
        "filled": tuple(filled),
        "gaps": tuple(gaps),
        "complete": not gaps,
        "rungs": len(family_rungs(max_log2)),
        "bases_used_by_the_chain": tuple(interleaved),
        "why_interleaving_is_needed": (
            "doubling multiplies squared norms by four, so one construction "
            "scaled by powers of two lands on every other power of two; the "
            "family is complete only because the Z/D/A/B/C-type rungs are "
            "interleaved with the scalings"),
    }


def chain_report(max_log2: int = MAX_LOG2) -> Dict[str, object]:
    """The norm chain, step by step, with every containment checked.

    Each step is *derived* by
    :func:`glm_universal.substrate.construction_ladder.contains` and then
    *tried* on generated points of the coarser rung, so a step that did not
    hold would be reported as a failure rather than believed.
    """
    chain = norm_chain(max_log2)
    steps: List[Dict[str, object]] = []
    for finer, coarser in zip(chain, chain[1:]):
        because = CL.contains(coarser, finer)
        points = CL.sample_points(coarser)
        misses = [point for point in points if not CL.in_rung(point, finer)]
        steps.append({
            "coarser": coarser,
            "finer": finer,
            "norms": (CL.rung_spec(coarser).minimum_norm,
                      CL.rung_spec(finer).minimum_norm),
            "derived": because is not None,
            "because": because,
            "points_checked": len(points),
            "misses": len(misses),
            "holds": because is not None and not misses,
        })
    return {
        "chain": chain,
        "steps": tuple(steps),
        "holds": all(step["holds"] for step in steps),
        "length": len(chain),
        "lean": ("GLM.NormFamily.chain_step_A, GLM.NormFamily.chain_step_B, "
                 "GLM.NormFamily.norm_family_chain, "
                 "GLM.NormFamily.family_tower"),
    }


def norm_family_report(max_log2: int = MAX_LOG2,
                       order: int = 64) -> Dict[str, object]:
    """Everything this module knows, recomputed on call."""
    keys = family_rungs(max_log2)
    rows = norm_rows(max_log2, order)
    return {
        "max_log2": max_log2,
        "rungs": keys,
        "rung_count": len(keys),
        "rows": rows,
        "completeness": completeness(max_log2),
        "scaling_rule": scaling_rule(),
        "densest_by_norm": densest_by_norm(max_log2),
        "chain": chain_report(max_log2),
        "containment_order": containment_order(densest_by_norm(max_log2)),
        "spot_check": CL.family_containment_spot_check(
            densest_by_norm(max_log2)),
        "series_all_agree": all(
            entry["series_agrees"]
            for row in rows for entry in row["rungs"]            # type: ignore[union-attr]
            if entry["series_reaches_minimum"]),
    }
