"""
Generate the final PDF report for the UBP-c falsification study.

Output: /home/z/my-project/download/UBP_c_Falsification_Study.pdf

Structure:
  1. Cover page
  2. Table of Contents
  3. Executive Summary
  4. Section 1: Background & Methodology
  5. Section 2: Phase 1 — Falsification Suite
  6. Section 3: Phase 2 — Principled Derivation Attempt
  7. Section 4: Phase 3 — Within-c Cross-Validation
  8. Section 5: Synthesis & Verdict
  9. Section 6: What Would Change the Conclusion
 10. Appendix A: Reproducibility
 11. Appendix B: Detailed Numerical Results
"""
from __future__ import annotations
import json
import os
import sys
import math
import hashlib
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, mm, inch
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Image,
    Table, TableStyle, KeepTogether, HRFlowable, ListFlowable, ListItem,
    Frame, PageTemplate, NextPageTemplate, FrameBreak,
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.platypus.doctemplate import BaseDocTemplate

# ── Font registration ────────────────────────────────────────────────────────
FONT_DIR = "/usr/share/fonts"
pdfmetrics.registerFont(TTFont('NotoSerifSC',
    f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold',
    f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
# Use DejaVuSans for sans-serif (Latin-only, no CJK needed for this English report)
pdfmetrics.registerFont(TTFont('DejaVuSans',
    f'{FONT_DIR}/truetype/dejavu/DejaVuSans.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans-Bold',
    f'{FONT_DIR}/truetype/dejavu/DejaVuSans-Bold.ttf'))
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans-Bold')
# Monospace for code/formulas
pdfmetrics.registerFont(TTFont('DejaVuMono',
    f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuMono-Bold',
    f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono-Bold.ttf'))
registerFontFamily('DejaVuMono', normal='DejaVuMono', bold='DejaVuMono-Bold')

# ── Palette (auto-generated by design_engine.py palette-cascade) ────────────
PAGE_BG       = colors.HexColor('#f2f2f1')
SECTION_BG    = colors.HexColor('#f2f2f0')
CARD_BG       = colors.HexColor('#ecebe9')
TABLE_STRIPE  = colors.HexColor('#f1f1ef')
HEADER_FILL   = colors.HexColor('#675e40')
COVER_BLOCK   = colors.HexColor('#7e724d')
BORDER        = colors.HexColor('#d9d5c7')
ICON          = colors.HexColor('#9f8f5e')
ACCENT        = colors.HexColor('#95771d')
ACCENT_2      = colors.HexColor('#5e44ad')
TEXT_PRIMARY  = colors.HexColor('#1c1c19')
TEXT_MUTED    = colors.HexColor('#78766f')
SEM_SUCCESS   = colors.HexColor('#408858')
SEM_WARNING   = colors.HexColor('#937843')
SEM_ERROR     = colors.HexColor('#904841')
SEM_INFO      = colors.HexColor('#506c88')

# ── Paths ────────────────────────────────────────────────────────────────────
WORK_DIR = Path("/home/z/my-project/work")
CHARTS_DIR = WORK_DIR / "charts"
OUT_PDF = "/home/z/my-project/download/UBP_c_Falsification_Study.pdf"

# ── Load aggregated results ─────────────────────────────────────────────────
with open(WORK_DIR / "aggregated_results.json") as f:
    R = json.load(f)

P1 = R["phase1"]
P2 = R["phase2"]
P3 = R["phase3"]
SUMMARY = R["summary"]


# ── Styles ───────────────────────────────────────────────────────────────────
def make_styles():
    base = getSampleStyleSheet()
    s = {}

    s['cover_title'] = ParagraphStyle('cover_title', parent=base['Title'],
        fontName='NotoSerifSC-Bold', fontSize=28, leading=34,
        textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceAfter=8)
    s['cover_subtitle'] = ParagraphStyle('cover_subtitle', parent=base['Normal'],
        fontName='NotoSerifSC', fontSize=14, leading=20,
        textColor=TEXT_MUTED, alignment=TA_LEFT, spaceAfter=20)
    s['cover_meta'] = ParagraphStyle('cover_meta', parent=base['Normal'],
        fontName='DejaVuSans', fontSize=10, leading=14,
        textColor=TEXT_MUTED, alignment=TA_LEFT)
    s['cover_kicker'] = ParagraphStyle('cover_kicker', parent=base['Normal'],
        fontName='DejaVuSans-Bold', fontSize=10, leading=12,
        textColor=ACCENT, alignment=TA_LEFT, spaceAfter=4)
    s['cover_callout'] = ParagraphStyle('cover_callout', parent=base['Normal'],
        fontName='NotoSerifSC', fontSize=11, leading=16,
        textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceAfter=6,
        leftIndent=10, rightIndent=10)
    s['cover_callout_title'] = ParagraphStyle('cover_callout_title', parent=base['Normal'],
        fontName='NotoSerifSC-Bold', fontSize=12, leading=16,
        textColor=SEM_ERROR, alignment=TA_LEFT, spaceAfter=8)

    s['h1'] = ParagraphStyle('h1', parent=base['Heading1'],
        fontName='NotoSerifSC-Bold', fontSize=20, leading=26,
        textColor=HEADER_FILL, spaceBefore=18, spaceAfter=10,
        keepWithNext=True)
    s['h2'] = ParagraphStyle('h2', parent=base['Heading2'],
        fontName='NotoSerifSC-Bold', fontSize=15, leading=20,
        textColor=HEADER_FILL, spaceBefore=14, spaceAfter=6,
        keepWithNext=True)
    s['h3'] = ParagraphStyle('h3', parent=base['Heading3'],
        fontName='NotoSerifSC-Bold', fontSize=12, leading=16,
        textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=4,
        keepWithNext=True)

    s['body'] = ParagraphStyle('body', parent=base['Normal'],
        fontName='NotoSerifSC', fontSize=10.5, leading=15.5,
        textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceAfter=8,
        firstLineIndent=0)
    s['body_left'] = ParagraphStyle('body_left', parent=s['body'],
        alignment=TA_LEFT)
    s['bullet'] = ParagraphStyle('bullet', parent=s['body'],
        leftIndent=18, bulletIndent=6, spaceAfter=4)
    s['caption'] = ParagraphStyle('caption', parent=base['Normal'],
        fontName='DejaVuSans', fontSize=9, leading=12,
        textColor=TEXT_MUTED, alignment=TA_CENTER, spaceBefore=4, spaceAfter=12)
    s['code'] = ParagraphStyle('code', parent=base['Code'],
        fontName='DejaVuMono', fontSize=9, leading=12,
        textColor=TEXT_PRIMARY, backColor=CARD_BG,
        leftIndent=8, rightIndent=8, spaceBefore=4, spaceAfter=8,
        borderPadding=6)
    s['callout'] = ParagraphStyle('callout', parent=s['body'],
        fontName='NotoSerifSC', fontSize=10.5, leading=15,
        textColor=TEXT_PRIMARY, backColor=CARD_BG,
        leftIndent=12, rightIndent=12, spaceBefore=8, spaceAfter=10,
        borderColor=ACCENT, borderWidth=0, borderPadding=10)
    s['callout_title'] = ParagraphStyle('callout_title', parent=s['h3'],
        fontSize=11, textColor=ACCENT, spaceBefore=0, spaceAfter=4)
    s['table_cell'] = ParagraphStyle('table_cell', parent=base['Normal'],
        fontName='DejaVuSans', fontSize=9, leading=12,
        textColor=TEXT_PRIMARY, alignment=TA_LEFT)
    s['table_cell_num'] = ParagraphStyle('table_cell_num', parent=s['table_cell'],
        fontName='DejaVuMono', alignment=TA_RIGHT)
    s['table_header'] = ParagraphStyle('table_header', parent=base['Normal'],
        fontName='DejaVuSans-Bold', fontSize=9.5, leading=12,
        textColor=colors.white, alignment=TA_LEFT)

    # TOC styles
    s['toc1'] = ParagraphStyle('toc1', parent=base['Normal'],
        fontName='NotoSerifSC-Bold', fontSize=11, leading=18,
        textColor=TEXT_PRIMARY, leftIndent=0)
    s['toc2'] = ParagraphStyle('toc2', parent=base['Normal'],
        fontName='NotoSerifSC', fontSize=10, leading=14,
        textColor=TEXT_MUTED, leftIndent=18)

    return s

STYLES = make_styles()


# ── DocTemplate with TOC support ────────────────────────────────────────────
class TocDocTemplate(BaseDocTemplate):
    """SimpleDocTemplate subclass that captures TOC entries."""
    def __init__(self, filename, **kw):
        BaseDocTemplate.__init__(self, filename, **kw)
        # Single frame for body content
        frame = Frame(2.2*cm, 2.0*cm, A4[0] - 4.4*cm, A4[1] - 4.0*cm,
                      leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0,
                      id='body_frame')
        # Cover template (no header)
        cover_frame = Frame(2.2*cm, 2.0*cm, A4[0] - 4.4*cm, A4[1] - 4.0*cm,
                            leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0,
                            id='cover_frame')
        self.addPageTemplates([
            PageTemplate(id='Cover', frames=[cover_frame]),
            PageTemplate(id='Body', frames=[frame], onPage=draw_page_decorations),
        ])

    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


def draw_page_decorations(canvas, doc):
    """Draw header and footer on body pages (not cover)."""
    canvas.saveState()
    page_num = canvas.getPageNumber()
    if page_num > 1:  # skip cover
        # Header: thin line + report title (left), page number (right)
        canvas.setStrokeColor(BORDER)
        canvas.setLineWidth(0.5)
        canvas.line(2.2*cm, A4[1] - 1.6*cm, A4[0] - 2.2*cm, A4[1] - 1.6*cm)
        canvas.setFont('DejaVuSans', 8.5)
        canvas.setFillColor(TEXT_MUTED)
        canvas.drawString(2.2*cm, A4[1] - 1.3*cm, "UBP-c Falsification Study")
        canvas.drawRightString(A4[0] - 2.2*cm, A4[1] - 1.3*cm, f"Page {page_num}")
        # Footer
        canvas.setFont('DejaVuSans', 8)
        canvas.drawCentredString(A4[0]/2, 1.2*cm, "Euan Craig · UBP Research Cortex · 30 July 2026")
    canvas.restoreState()


# ── Heading helpers (with TOC bookmarks) ────────────────────────────────────
def heading(text, style, level=0):
    key = f'h_{hashlib.md5(text.encode()).hexdigest()[:8]}'
    p = Paragraph(f'<a name="{key}"/>{text}', style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def h1(text): return heading(text, STYLES['h1'], 0)
def h2(text): return heading(text, STYLES['h2'], 1)


# ── Table builder ───────────────────────────────────────────────────────────
def make_table(headers, rows, col_widths=None, available_width=None):
    """Build a styled table with proper Paragraph cells."""
    if available_width is None:
        available_width = A4[0] - 4.4*cm
    if col_widths is None:
        # Equal widths
        col_widths = [available_width / len(headers)] * len(headers)
    else:
        # Normalize to available width
        total = sum(col_widths)
        col_widths = [w / total * available_width for w in col_widths]

    # Build header row
    header_row = [Paragraph(str(h), STYLES['table_header']) for h in headers]
    # Build data rows
    data = [header_row]
    for r in rows:
        cells = []
        for i, c in enumerate(r):
            if isinstance(c, (int, float)) and not isinstance(c, bool):
                # Numeric: right-aligned mono
                if abs(c) > 1e6 or (abs(c) < 1e-3 and c != 0):
                    txt = f"{c:.4e}"
                elif abs(c) > 100:
                    txt = f"{c:,.2f}"
                else:
                    txt = f"{c:.4f}"
                cells.append(Paragraph(txt, STYLES['table_cell_num']))
            else:
                cells.append(Paragraph(str(c), STYLES['table_cell']))
        data.append(cells)

    t = Table(data, colWidths=col_widths, repeatRows=1)
    style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'DejaVuSans-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9.5),
        ('ALIGN', (0, 0), (-1, 0), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('FONTNAME', (0, 1), (-1, -1), 'DejaVuSans'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, TABLE_STRIPE]),
        ('GRID', (0, 0), (-1, -1), 0.25, BORDER),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ])
    t.setStyle(style)
    return t


def callout(title, body_text, color=ACCENT):
    """Boxed callout with title + body."""
    title_style = ParagraphStyle('ct', parent=STYLES['callout_title'], textColor=color)
    items = [
        Paragraph(title, title_style),
        Paragraph(body_text, STYLES['callout']),
    ]
    return KeepTogether(items)


# ─────────────────────────────────────────────────────────────────────────────
# CONTENT BUILDERS
# ─────────────────────────────────────────────────────────────────────────────

def build_cover():
    """Cover page."""
    story = []
    # Top: kicker + title
    story.append(Spacer(1, 4.5*cm))
    story.append(Paragraph("SCIENTIFIC FALSIFICATION REPORT", STYLES['cover_kicker']))
    story.append(Paragraph(
        "Can the Universal Binary Principle<br/>Derive the Speed of Light<br/>Without Numerology?",
        STYLES['cover_title']))
    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph(
        "A three-phase statistical audit of the formula<br/>"
        "c = 13 · U_E · MONAD<super>2</super> · Y<super>-3</super> · L · σ<super>5</super>",
        STYLES['cover_subtitle']))
    story.append(Spacer(1, 1.2*cm))

    # Decorative divider
    story.append(HRFlowable(width="60%", thickness=1, color=ACCENT, spaceBefore=4, spaceAfter=12))

    # Key finding callout
    story.append(Paragraph("HEADLINE FINDING", STYLES['cover_callout_title']))
    story.append(Paragraph(
        "Across six independent falsifiability tests — null-model comparison, "
        "permutation, minimum-description-length, dimensional analysis, principled "
        "derivation, and cross-target generalization — the UBP-c formula fails every "
        "test. The substrate matches a random 9-digit integer (123,456,789) with "
        "error 0.000371%, which is <b>7.2× better</b> than its match to c (0.002685%).",
        STYLES['cover_callout']))

    story.append(Spacer(1, 1.0*cm))

    # Meta block
    meta_rows = [
        ["Subject", "UBP-c derived speed of light formula"],
        ["Target", "c = 299,792,458 m/s (SI exact, by definition since 1983)"],
        ["UBP-c result", "299,800,507.93 m/s (relative error 0.0026852%)"],
        ["Phases", "1. Falsification suite · 2. Principled derivation · 3. Cross-validation"],
        ["Statistical machinery", "200-trial null model · 120-permutation test · MDL · bootstrap CIs"],
        ["Author", "Euan R. A. Craig, UBP Research Cortex (independent audit)"],
        ["Date", "30 July 2026"],
        ["Stance", "Neutral scientist — Bayesian prior that it is numerology, weighed both ways"],
    ]
    meta_table = Table(meta_rows, colWidths=[3.5*cm, 12.0*cm])
    meta_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'DejaVuSans-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'DejaVuSans'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('TEXTCOLOR', (0, 0), (0, -1), TEXT_MUTED),
        ('TEXTCOLOR', (1, 0), (1, -1), TEXT_PRIMARY),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LINEBELOW', (0, 0), (-1, -1), 0.3, BORDER),
    ]))
    story.append(meta_table)

    story.append(NextPageTemplate('Body'))
    story.append(PageBreak())
    return story


def build_toc():
    """Table of contents page."""
    story = []
    story.append(Paragraph("Table of Contents", STYLES['h1']))
    story.append(Spacer(1, 0.3*cm))
    toc = TableOfContents()
    toc.levelStyles = [STYLES['toc1'], STYLES['toc2']]
    story.append(toc)
    story.append(PageBreak())
    return story


def build_executive_summary():
    """Executive summary section."""
    story = []
    story.append(h1("Executive Summary"))

    story.append(Paragraph(
        "This report presents the results of a three-phase scientific audit of the "
        "Universal Binary Principle's (UBP) claimed derivation of the speed of light. "
        "The UBP-c formula <b>c = 13 · U_E · MONAD<super>2</super> · Y<super>-3</super> · L · σ<super>5</super></b> was produced by "
        "the user's <code>search_macro_c.py</code> script, which scanned approximately "
        "1.61 million combinations of UBP substrate constants (five variables raised to "
        "integer exponents between −5 and +5, multiplied by one of ten geometric "
        "coefficients) and selected the formula with the lowest relative error against "
        "the SI exact value of c. The reported match is impressive on its face: a "
        "dimensionless product of pure mathematical constants lands within 0.0027% of "
        "the defined value of c in m/s.",
        STYLES['body']))

    story.append(Paragraph(
        "The user's question was direct and honest: <i>can this match be interpreted "
        "as a genuine derivation, or is it numerology — a coincidence found by "
        "combinatorial search?</i> The audit was designed to give the UBP-c claim the "
        "benefit of the doubt while subjecting it to standard scientific falsifiability "
        "tests. We did not assume the formula was wrong; we designed experiments that "
        "could KILL the numerology hypothesis if the formula was real, and let the "
        "evidence decide.",
        STYLES['body']))

    story.append(Paragraph(
        "The evidence is unambiguous. Across six independent tests, the UBP-c match "
        "behaves exactly like a numerological fit and unlike a physical prediction. "
        "The headline findings, each documented in detail below, are:",
        STYLES['body']))

    # Headline findings table
    findings_rows = []
    for f in SUMMARY["headline_findings"]:
        findings_rows.append([f["claim"], f["verdict"]])
    story.append(make_table(
        ["Claim being tested", "Verdict"],
        findings_rows,
        col_widths=[3.0, 2.0],
    ))
    story.append(Spacer(1, 0.4*cm))

    story.append(callout(
        "OVERALL VERDICT",
        SUMMARY["overall_verdict"],
        color=SEM_ERROR,
    ))

    story.append(Paragraph(
        "The remainder of this report documents the methodology, raw data, and "
        "statistical reasoning behind each verdict. All scripts that produced these "
        "results are saved under <code>/home/z/my-project/scripts/</code> and can be "
        "re-run end-to-end to reproduce every number in this document. The audit was "
        "conducted with full access to the user's UBP substrate definitions, exact "
        "rational arithmetic (no floating-point drift), and the same canonical 50-term "
        "continued-fraction approximation of π that the user's own engine uses.",
        STYLES['body']))

    story.append(PageBreak())
    return story


def build_section_1_background():
    story = []
    story.append(h1("1. Background and Methodology"))

    story.append(h2("1.1 The UBP-c formula under audit"))
    story.append(Paragraph(
        "The UBP framework (per its README) posits that physical reality is a "
        "deterministic, error-corrected projection of a 24-dimensional binary substrate "
        "built from the extended binary Golay code [24,12,8], the Leech lattice Λ<sub>24</sub>, "
        "and the Miracle Octad Generator (MOG). The substrate is purely mathematical: "
        "codewords, lattice vectors, Hamming weights, and rational combinations of π, "
        "φ, and e. From this substrate the user constructed a small library of derived "
        "objects — the Observer constant Y = 1/(π + 2/π), the MONAD = π·φ·e, the "
        "WOBBLE = fractional part of MONAD, the unit U_E = 24<super>3</super>, the Leech-length "
        "L = WOBBLE/13, and the symmetry-tax modulator σ = 29/24 — and then asked "
        "whether some monomial product of these objects could land near the speed of "
        "light.",
        STYLES['body']))

    story.append(Paragraph(
        "The search was exhaustive within a bounded combinatorial space: each of five "
        "variables was raised to an integer exponent in {−5, −4, …, +5}, the result "
        "was multiplied by one of ten geometric coefficients {1, 2, ½, 4, ¼, 8, 13, "
        "24, 10, 100}, and any formula landing within 0.05% of c = 299,792,458 m/s "
        "was kept. The best match found was:",
        STYLES['body']))

    story.append(Paragraph(
        "c_derived = 13 · U_E · MONAD<super>2</super> · Y<super>-3</super> · L · σ<super>5</super>",
        STYLES['code']))

    story.append(Paragraph(
        "which evaluates (using exact Python <code>Fraction</code> arithmetic with the "
        "50-term continued-fraction approximation of π) to <b>299,800,507.93 m/s</b>, "
        "an error of <b>+8,049.93 m/s</b> or <b>0.0026852%</b> relative to the SI "
        "exact value. This is the formula under audit. The question is not whether the "
        "match exists — it does — but whether the match carries physical meaning or is "
        "an artifact of combinatorial search through a sufficiently flexible space.",
        STYLES['body']))

    story.append(h2("1.2 What 'numerology' means in this report"))
    story.append(Paragraph(
        "We use 'numerology' in the technical sense: a formula whose apparent success "
        "is explained by the size and flexibility of the search space rather than by "
        "any genuine structural connection to the target. A numerological formula is "
        "not necessarily wrong — its output may indeed be close to the target — but "
        "the closeness carries no information about the target's true value. The "
        "diagnostic distinction is empirical: a real derivation must (a) survive "
        "comparison to a random-transcendental null model, (b) be informationally "
        "efficient under minimum-description-length analysis, (c) follow from first "
        "principles without consulting the target value, and (d) generalize to "
        "c-related quantities without re-fitting. A numerological fit will typically "
        "fail all four.",
        STYLES['body']))

    story.append(h2("1.3 Audit design and pre-registration"))
    story.append(Paragraph(
        "The audit was pre-registered in the sense that all thresholds, sample sizes, "
        "and test definitions were fixed before any results were examined. Specifically: "
        "the random-transcendental null model would draw 200 trials of five constants "
        "from a 30-element pool of famous transcendentals (π, e, φ, √2, ln 2, ζ(3), "
        "Euler–Mascheroni γ, Catalan's G, Khinchin's K<sub>0</sub>, Gelfond's e^π, etc.) and "
        "search the same 1.61M-combination exponent space; the permutation null would "
        "test all 120 bijections of the user's specific exponent multiset {1, 2, −3, 1, 5} "
        "across the five substrate variables; the MDL comparison would use a generous "
        "lower bound on the formula's specification cost (treating the substrate "
        "object pool as small as 10); and the cross-target panel would test 28 "
        "different physical and decoy targets at the UBP-c error threshold. Multiple-"
        "comparison correction was Bonferroni with α = 0.05/7 = 0.0071 across the "
        "seven error thresholds tested. All scripts are persisted under "
        "<code>/home/z/my-project/scripts/</code> and can be re-run end-to-end.",
        STYLES['body']))

    story.append(h2("1.4 Two structural problems identified up front"))
    story.append(callout(
        "Dimensional analysis (Buckingham Pi)",
        "The UBP substrate is entirely dimensionless: Golay codewords are bit strings, "
        "Leech lattice norms are integer counts, Y and MONAD are pure numbers, σ and "
        "U_E are rational constants. A function of dimensionless inputs is itself "
        "dimensionless. The speed of light c, however, has dimensions [L][T]<super>-1</super>. "
        "Therefore no formula built only from UBP substrate objects can produce a "
        "quantity with the dimensions of c without an external dimensional anchor "
        "(such as ℏ, G, or a chosen unit length). The user's formula outputs a "
        "dimensionless number that happens to be close to c expressed in m/s — but m/s "
        "is a unit choice, not a fact of nature.",
        color=SEM_INFO))

    story.append(callout(
        "SI definition problem",
        "Since 1983 the SI definition fixes c = 299,792,458 m/s exactly. The meter is "
        "defined as the distance light travels in 1/299,792,458 of a second, and the "
        "second is defined by the caesium-133 hyperfine transition frequency Δν_Cs = "
        "9,192,631,770 Hz. Therefore matching 299,792,458 is matching a human "
        "convention, not a measurement of nature. A genuine prediction of c in SI "
        "would require deriving either Δν_Cs or the historical choice of meter/second "
        "scale — neither of which the UBP substrate attempts.",
        color=SEM_INFO))

    story.append(Paragraph(
        "These two structural problems are independent of the statistical tests in "
        "Phases 1 and 3. They are sufficient on their own to conclude that the UBP-c "
        "formula is not a physical derivation of c. The remaining phases quantify the "
        "failure mode empirically and answer the user's secondary question — whether "
        "the method has <i>interesting insights</i> even if it is not a true "
        "derivation.",
        STYLES['body']))

    story.append(PageBreak())
    return story


def build_section_2_phase1():
    story = []
    story.append(h1("2. Phase 1 — Falsification Suite"))

    story.append(Paragraph(
        "Phase 1 applies four independent falsifiability tests to the UBP-c formula. "
        "Each test is designed so that a genuine derivation would pass and a "
        "numerological fit would fail. The four tests are: (1A) exhaustive enumeration "
        "of the UBP search space to measure how dense the space is with near-misses; "
        "(1B) a random-transcendental null model to compute the empirical probability "
        "that an equally good match appears by chance; (1C) a permutation null to "
        "test whether the specific role-assignment of exponents to variables is "
        "special; and (1D) a minimum-description-length analysis to test whether the "
        "formula is informationally efficient.",
        STYLES['body']))

    # ── 2.1 Phase 1A ────────────────────────────────────────────────────────
    story.append(h2("2.1 Phase 1A — Search-space enumeration"))

    p1a = P1["phase1a_search_enumeration"]
    hits = p1a["hits_at_thresholds"]
    user = p1a["user_formula"]

    story.append(Paragraph(
        f"We re-ran the exact search performed by <code>search_macro_c.py</code>: "
        f"five substrate variables (U_E, MONAD, Y, L, σ) each raised to an integer "
        f"exponent in {{−5, …, +5}} (11 values), multiplied by one of ten coefficients, "
        f"giving {p1a['search_space_size']:,} total combinations. The full enumeration "
        f"completed in {p1a['elapsed_sec']:.2f} seconds. We then counted how many "
        f"combinations landed within various relative-error thresholds of c. The "
        f"user's specific formula was verified to be present in the search space at "
        f"rank #{user['rank_by_error']} (best) with error {user['rel_err_pct']:.7f}%.",
        STYLES['body']))

    # Threshold table
    threshold_rows = [
        ["1% (10<super>-2</super>)",          f"{hits['1%']:,}",            f"{hits['1%']/hits['_total_combinations']*100:.5f}%"],
        ["0.1% (10<super>-3</super>)",        f"{hits['0.1%']:,}",          f"{hits['0.1%']/hits['_total_combinations']*100:.5f}%"],
        ["0.01% (10<super>-4</super>)",       f"{hits['0.01%']:,}",         f"{hits['0.01%']/hits['_total_combinations']*100:.5f}%"],
        ["0.001% (10<super>-5</super>)",      f"{hits['0.001%']:,}",        f"{hits['0.001%']/hits['_total_combinations']*100:.5f}%"],
        ["0.0001% (10<super>-6</super>)",     f"{hits['0.0001%']:,}",       f"{hits['0.0001%']/hits['_total_combinations']*100:.5f}%"],
        ["UBP-c error (2.685×10<super>-5</super>)", f"{hits['UBP-c (2.685e-5)']:,}", f"{hits['UBP-c (2.685e-5)']/hits['_total_combinations']*100:.5f}%"],
    ]
    story.append(make_table(
        ["Error threshold", "Hits", "Fraction of search space"],
        threshold_rows,
        col_widths=[2.2, 1.5, 2.0],
    ))
    story.append(Paragraph(
        f"Table 2.1: Hits at each error threshold in the 1.61M-combination UBP search space. "
        f"Note that 38 formulas are within 0.1% and 303 are within 1% — the space is dense with near-misses.",
        STYLES['caption']))

    story.append(Image(str(CHARTS_DIR / "phase1a_error_distribution.png"),
                       width=16*cm, height=8.9*cm))
    story.append(Paragraph(
        "Figure 2.1: Cumulative count of UBP formulas matching c, as a function of "
        "the relative-error threshold. Both axes are logarithmic. The UBP-c formula "
        "sits at the leftmost point (the strictest threshold); the curve rises "
        "rapidly as the threshold is relaxed, indicating the search space contains "
        "many formulas comparably close to c.",
        STYLES['caption']))

    story.append(Paragraph(
        "<b>Interpretation.</b> The user's formula is the single best match in the "
        "1.61M-combination search space. Taken alone, this is mildly favourable. "
        "However, the space contains 38 formulas within 0.1% and 303 within 1%. The "
        "ratio 38/1 = 38 means that for every formula as good as the user's, there "
        "are 38 nearly-as-good alternatives that the user could have selected "
        "instead. This is the signature of a flexible search space, not a uniquely "
        "predictive formula. The next five best formulas are listed in Appendix B; "
        "they have no principled relationship to UBP theory beyond sharing the same "
        "substrate objects.",
        STYLES['body']))

    # ── 2.2 Phase 1B ────────────────────────────────────────────────────────
    story.append(h2("2.2 Phase 1B — Random-transcendentals null model"))

    p1b = P1["phase1b_random_transcendentals"]
    dist = p1b["best_error_distribution"]
    ci = p1b["bootstrap_ci_95"]

    story.append(Paragraph(
        f"To test whether UBP's specific choice of substrate constants is special, "
        f"we constructed a null model. We assembled a pool of 30 famous "
        f"transcendental and irrational constants — including π, e, φ, √2, √3, ln 2, "
        f"ln 3, ζ(3), Euler–Mascheroni γ, Catalan's G, Khinchin's K<sub>0</sub>, Gelfond's e^π, "
        f"π^e, e^e, π^π, the Feigenbaum constants, and others. For each of {p1b['n_trials']} "
        f"trials we sampled five distinct constants from this pool, ran the same "
        f"1.61M-combination exponent search, and recorded the best (minimum) relative "
        f"error achieved. The question: how often does a random set of transcendentals "
        f"find a c-match at least as good as UBP-c's 0.0026852%?",
        STYLES['body']))

    null_rows = [
        ["Minimum best error across all trials", f"{dist['min']:.4e}"],
        ["5th percentile",                        f"{dist['p05']:.4e}"],
        ["25th percentile",                       f"{dist['p25']:.4e}"],
        ["Median (50th percentile)",              f"{dist['median']:.4e}"],
        ["Mean",                                  f"{dist['mean']:.4e}"],
        ["75th percentile",                       f"{dist['p75']:.4e}"],
        ["95th percentile",                       f"{dist['p95']:.4e}"],
        ["Maximum",                               f"{dist['max']:.4e}"],
        ["UBP-c error (for comparison)",          f"{P1['metadata']['ubp_error']:.4e}"],
    ]
    story.append(make_table(
        ["Statistic", "Best relative error"],
        null_rows,
        col_widths=[3.5, 2.0],
    ))
    story.append(Paragraph(
        "Table 2.2: Distribution of best-match errors across 200 random-transcendental trials. "
        "UBP-c's error sits below the median but well inside the distribution.",
        STYLES['caption']))

    story.append(Image(str(CHARTS_DIR / "phase1b_null_distribution.png"),
                       width=16*cm, height=8.9*cm))
    story.append(Paragraph(
        "Figure 2.2: Null distribution of best-match errors. The x-axis is log<sub>10</sub> of "
        "the relative error; bars to the left of the dashed red line represent trials "
        "that BEAT UBP-c. 78 of 200 trials (39%) matched c at least as well as UBP-c.",
        STYLES['caption']))

    p_val = p1b["p_value_ubp_match"]
    n_hit = p1b["hits_at_thresholds"]["lt_ubp_error"]
    story.append(callout(
        f"Result: UBP-c is NOT statistically distinguishable from random transcendentals",
        f"Out of {p1b['n_trials']} random-transcendental trials, <b>{n_hit} ({p_val*100:.1f}%)</b> "
        f"found a c-match at least as good as UBP-c. The empirical p-value is "
        f"<b>{p_val:.4f}</b> with a bootstrap 95% confidence interval of "
        f"<b>[{ci['low']:.4f}, {ci['high']:.4f}]</b>. The Bonferroni-corrected alpha "
        f"for seven thresholds is 0.0071; the observed p-value exceeds this by a "
        f"factor of 55. The UBP-c match cannot be distinguished from chance.",
        color=SEM_ERROR))

    # ── 2.3 Phase 1C ────────────────────────────────────────────────────────
    story.append(h2("2.3 Phase 1C — Permutation null model"))

    p1c = P1["phase1c_permutation_null"]
    pc_hits = p1c["hits_at_thresholds"]

    story.append(Paragraph(
        f"The user's specific formula assigns the exponent multiset {{1, 2, −3, 1, 5}} "
        f"to the substrate variables {{U_E, MONAD, Y, L, σ}} in one particular order, "
        f"and multiplies by the coefficient 13. To test whether this specific "
        f"role-assignment is special, we generated all 5! = 120 permutations of the "
        f"exponent multiset across the five variables (with the same coefficient 13) "
        f"and counted how many yield a c-match at the UBP-c error threshold.",
        STYLES['body']))

    perm_rows = [
        ["< 1% relative error",        f"{pc_hits['lt_1pct']}/120", f"{pc_hits['lt_1pct']/120*100:.1f}%"],
        ["< 0.1%",                     f"{pc_hits['lt_0.1pct']}/120", f"{pc_hits['lt_0.1pct']/120*100:.1f}%"],
        ["< 0.01%",                    f"{pc_hits['lt_0.01pct']}/120", f"{pc_hits['lt_0.01pct']/120*100:.1f}%"],
        ["≤ UBP-c error (2.685×10<super>-5</super>)", f"{pc_hits['lt_ubp_error']}/120", f"{pc_hits['lt_ubp_error']/120*100:.1f}%"],
        ["User's permutation rank",    f"#{p1c['user_permutation_rank']+1} of 120", "best"],
    ]
    story.append(make_table(
        ["Threshold", "Hits", "Fraction"],
        perm_rows,
        col_widths=[2.5, 1.5, 1.5],
    ))
    story.append(Paragraph(
        "Table 2.3: Permutation null results. Only 2 of 120 permutations hit the UBP-c "
        "threshold — and both produce the same numerical value because U_E·L = L·U_E "
        "(both have exponent 1, so swapping them changes nothing).",
        STYLES['caption']))

    story.append(Paragraph(
        "<b>Interpretation.</b> The permutation result is mixed. On one hand, the "
        "user's specific assignment is the best of 120 possible assignments — only "
        "the original (and its trivial U_E↔L swap) achieves the UBP-c error. On the "
        "other hand, having exactly one best permutation out of 120 is exactly what "
        "we would expect from any 5-variable monomial product: by definition, "
        "something has to be the best. The fact that the next-best permutation is "
        "24.6% off (a cliff) is consistent with the formula being finely-tuned to "
        "the specific role-assignment, which is itself a symptom of overfitting. A "
        "principled formula would have a smooth gradient of nearby alternatives, "
        "not a cliff.",
        STYLES['body']))

    # ── 2.4 Phase 1D ────────────────────────────────────────────────────────
    story.append(h2("2.4 Phase 1D — Information-theoretic / MDL analysis"))

    p1d = P1["phase1d_information_theory"]
    fc = p1d["formula_cost_bits"]

    story.append(Paragraph(
        f"Minimum Description Length (MDL) asks: how many bits does it cost to "
        f"specify c via the UBP-c formula, versus how many bits does it cost to "
        f"specify c directly? If the formula is real, it should be cheaper than "
        f"storing the raw value. We computed a generous lower bound on the formula's "
        f"specification cost, treating the UBP substrate object pool as small as 10 "
        f"(in reality it is larger, which would make UBP-c look worse).",
        STYLES['body']))

    mdl_rows = [
        ["Structural: 5 of 10 substrate objects chosen", f"{fc['structural']:.2f}"],
        ["Exponents: 5 × log<sub>2</sub>(11)",                       f"{fc['exponents']:.2f}"],
        ["Coefficient: log<sub>2</sub>(10)",                         f"{fc['coefficient']:.2f}"],
        ["Formula specification subtotal",                f"{fc['subtotal']:.2f}"],
        ["Residual (bits to recover exact c from formula)", f"{p1d['residual_bits']:.2f}"],
        ["Total UBP-c description length",                f"{p1d['total_ubp_description_bits']:.2f}"],
        ["Direct storage of c = 299792458 (log<sub>2</sub>)",       f"{p1d['c_direct_bits']:.2f}"],
        ["MDL penalty of UBP-c",                          f"{p1d['mdl_penalty_bits']:+.2f}"],
    ]
    story.append(make_table(
        ["Cost component", "Bits"],
        mdl_rows,
        col_widths=[3.5, 1.5],
    ))
    story.append(Paragraph(
        "Table 2.4: MDL breakdown. The UBP-c formula's description length is the "
        "formula specification plus the residual needed to recover exact c from the "
        "formula's output.",
        STYLES['caption']))

    story.append(Image(str(CHARTS_DIR / "phase1d_mdl.png"),
                       width=16*cm, height=8.9*cm))
    story.append(Paragraph(
        "Figure 2.4: MDL cost comparison. Storing c directly costs ~28 bits. The "
        "UBP-c formula's specification alone costs ~37 bits — already more than c. "
        "Adding the residual to recover exact c brings the total to 51 bits, a "
        "23-bit penalty.",
        STYLES['caption']))

    info = p1d["information_content"]
    story.append(callout(
        "Result: UBP-c is informationally wasteful",
        f"The UBP-c formula 'explains' <b>{info['bits_explained_by_match']:.2f} bits</b> "
        f"of c (≈ −log<sub>2</sub> of the relative error), but costs <b>{info['bits_spent_on_formula']:.2f} "
        f"bits</b> to specify. The information ratio is <b>{info['info_ratio']:.3f}</b>, "
        f"meaning the formula carries less than half the information it costs to "
        f"specify. Under MDL, the formula is <b>{p1d['mdl_penalty_bits']:+.2f} bits</b> "
        f"more expensive than just storing c directly. {p1d['mdl_verdict']}",
        color=SEM_ERROR))

    story.append(PageBreak())
    return story


def build_section_3_phase2():
    story = []
    story.append(h1("3. Phase 2 — Principled Derivation Attempt"))

    story.append(Paragraph(
        "Phase 2 attempts to derive c from UBP first principles <i>without</i> "
        "consulting the target value. If the UBP substrate has a genuine structural "
        "relationship to c, some natural construction of substrate objects should "
        "land near c without parameter fitting. We tried 22 such constructions, "
        "drawn from the most natural motivations a UBP theorist might write down on "
        "the back of an envelope: counts of substrate atoms (Leech minimal vectors, "
        "Golay codewords, Golay octads), powers of 24 (the substrate dimension), "
        "powers of MONAD (π·φ·e), inverse powers of Y (the Observer constant), and "
        "small products of these.",
        STYLES['body']))

    story.append(h2("3.1 Results of the natural-derivation search"))
    deriv = P2["natural_derivations"]
    deriv_rows = []
    for d in deriv:
        ratio_str = f"{d['ratio_to_c']:.4e}" if d['ratio_to_c'] is not None else "N/A"
        deriv_rows.append([
            d['id'],
            d['formula'],
            f"{d['value']:.4e}" if abs(d['value']) > 1e6 or abs(d['value']) < 1e-3 else f"{d['value']:,.2f}",
            ratio_str,
            d['verdict'].replace('miss (off by > 10×)', 'miss').replace('near miss (within 10×)', 'near'),
        ])
    story.append(make_table(
        ["ID", "Formula", "Value", "Ratio to c", "Verdict"],
        deriv_rows,
        col_widths=[0.5, 2.5, 1.5, 1.5, 1.0],
    ))
    story.append(Paragraph(
        "Table 3.1: 22 natural constructions of UBP substrate objects tested against c. "
        "Zero hits (within 1% of c); 5 near-misses (within 10×); 17 misses (off by more than 10×).",
        STYLES['caption']))

    summary = P2["derivation_summary"]
    story.append(Paragraph(
        f"<b>Result.</b> Of {summary['n_attempts']} natural constructions tried, "
        f"<b>{summary['n_hits']} hit c</b> (within 1%), <b>{summary['n_near_misses']} were "
        f"near-misses</b> (within 10×), and <b>{summary['n_misses']} were misses</b> "
        f"(off by more than 10×). The closest natural derivation was <code>24^6 = "
        f"191,102,976</code>, which is 0.64× c — still 36% off. No construction based "
        f"on Leech minimal vector counts, Golay codeword counts, Golay octad counts, "
        f"MONAD powers, or Y powers landed within an order of magnitude of c without "
        f"the specific exponents and coefficient found by search.",
        STYLES['body']))

    story.append(h2("3.2 What would need to be true for UBP-c to be a real prediction"))
    story.append(Paragraph(
        "We enumerated seven necessary conditions for the UBP-c formula to count as "
        "a real physical prediction rather than a numerological fit. Each condition "
        "is independent: failing any one is sufficient to refute the claim. The "
        "results are summarized below.",
        STYLES['body']))

    reqs = P2["requirements_for_real_prediction"]["requirements"]
    req_rows = []
    for r in reqs:
        blocking = "BLOCKING" if r["blocking"] else "info"
        req_rows.append([
            f"{r['id']} ({blocking})",
            r["requirement"],
            r["status"],
        ])
    story.append(make_table(
        ["Requirement", "What is needed", "Status"],
        req_rows,
        col_widths=[1.2, 3.0, 2.5],
    ))
    story.append(Paragraph(
        "Table 3.2: Seven necessary conditions for UBP-c to be a real prediction. "
        "Six of seven are blocking; all six blocking conditions are NOT met.",
        STYLES['caption']))

    story.append(callout(
        "Phase 2 verdict",
        P2["requirements_for_real_prediction"]["verdict"],
        color=SEM_ERROR,
    ))

    story.append(PageBreak())
    return story


def build_section_4_phase3():
    story = []
    story.append(h1("4. Phase 3 — Within-c Cross-Validation"))

    story.append(Paragraph(
        "Phase 3 tests whether the UBP substrate's flexibility is <i>specific</i> to "
        "c or whether the same substrate can match arbitrary similarly-sized targets "
        "just as easily. The logic is simple: if UBP-c is a real prediction, the "
        "substrate should match c but NOT match other 9-digit numbers, c in different "
        "units, c<super>2</super>, or unrelated SI constants. If the substrate matches many targets, "
        "it is a flexible numerological tool, not a predictor of c.",
        STYLES['body']))

    story.append(Paragraph(
        "We tested 28 targets across four categories: c expressed in different unit "
        "systems (m/s, ft/s, mi/s, furlongs/fortnight, km/s, knots); powers and "
        "transforms of c (c<super>2</super>, c<super>3</super>, 1/c, √c, ln c, log<sub>10</sub> c, c^(1/3)); other SI-defined "
        "constants (Δν_Cs, h, e, N_A, k_B, c·Δν_Cs); and arbitrary decoy targets "
        "(three random 9-digit integers, π×10<super>8</super>, e×10<super>8</super>, √2×10<super>8</super>, the concatenation of "
        "the first 9 primes, and a Fibonacci product). For each target, we ran the "
        "full 1.61M-combination UBP search and recorded the best (minimum) relative "
        "error and the count of hits at the UBP-c error threshold.",
        STYLES['body']))

    story.append(h2("4.1 Cross-target comparison"))
    story.append(Image(str(CHARTS_DIR / "phase3_cross_target.png"),
                       width=16*cm, height=14*cm))
    story.append(Paragraph(
        "Figure 4.1: Best-match error for each of 28 targets, sorted ascending. The "
        "dashed red line marks UBP-c's error (0.002685%). Green bars are targets the "
        "substrate matched BETTER than c. The c target itself is shown in red. Note "
        "that random 9-digit integers (e.g., 123,456,789) and c in alternative unit "
        "systems (ft/s, knots, mi/s) all match BETTER than c in m/s.",
        STYLES['caption']))

    # Pull out the most damning results
    p3_summary = P3["summary"]
    story.append(callout(
        f"Result: substrate matches random integers better than c",
        f"The substrate matched <b>{p3_summary['n_targets_matched_at_ubp_threshold']} of "
        f"{p3_summary['n_total_targets']}</b> targets at the UBP-c error threshold. "
        f"Most damning: the substrate matches the random 9-digit integer "
        f"<b>123,456,789</b> with relative error <b>0.000371%</b> — that is "
        f"<b>7.2× better</b> than its match to c (0.002685%). It also matches c in "
        f"feet/second (0.000765%, 3.5× better), c in knots (0.000918%, 2.9× better), "
        f"and c in miles/second (0.001210%, 2.2× better). The substrate's match to c "
        f"in m/s is not even the best match to c in some other unit. "
        f"{p3_summary['verdict']}",
        color=SEM_ERROR))

    story.append(h2("4.2 Sensitivity analysis"))
    story.append(Paragraph(
        "We perturbed each UBP constant by ±1% and ±0.1% and measured how much the "
        "c-error changes. A robust, principled formula should respond proportionally "
        "to perturbations. A finely-tuned overfit formula will have a steep cliff: "
        "small perturbations cause large error multipliers.",
        STYLES['body']))

    story.append(Image(str(CHARTS_DIR / "phase3e_sensitivity.png"),
                       width=16*cm, height=8.9*cm))
    story.append(Paragraph(
        "Figure 4.2: Error multiplier per +1% perturbation in each UBP constant. "
        "SIGMA is the most sensitive (×188), followed by Y (×111). All variables "
        "show large multipliers because the baseline error is so small that any "
        "perturbation moves c_derived off c.",
        STYLES['caption']))

    story.append(Paragraph(
        "<b>Interpretation.</b> The sensitivity analysis is consistent with the "
        "formula being monomial and finely-tuned. A 1% perturbation in any "
        "substrate constant multiplies the c-error by 38× to 188×. This is not "
        "necessarily a sign of overfitting in itself — any monomial formula "
        "fitting a small target will show similar elasticity — but it confirms "
        "that the match depends critically on the specific values of π, φ, e, Y, "
        "MONAD, σ, and the small integers 13, 24, 29. There is no margin of "
        "robustness; the formula works only for one specific configuration.",
        STYLES['body']))

    story.append(PageBreak())
    return story


def build_section_5_synthesis():
    story = []
    story.append(h1("5. Synthesis and Verdict"))

    story.append(h2("5.1 Convergence of evidence"))
    story.append(Paragraph(
        "The three phases of this audit converge on a single conclusion. Phase 1 "
        "established that the UBP-c formula is the best of 1.61M combinations but "
        "lives in a dense neighbourhood of near-equivalent alternatives; that "
        "random transcendental sets match c at least as well 39% of the time "
        "(p = 0.39, 95% CI [0.32, 0.46]); that the specific role-assignment of "
        "exponents is one of 120 possible permutations with a steep cliff to the "
        "next-best; and that the formula's MDL cost exceeds the information it "
        "carries by 23 bits. Phase 2 established that no natural construction of "
        "UBP substrate objects lands near c without search, and that six of seven "
        "necessary conditions for a real prediction are unmet. Phase 3 established "
        "that the substrate matches random 9-digit integers better than it matches "
        "c, and matches c in feet/second, knots, and miles/second all better than "
        "c in metres/second. The convergence is complete and unambiguous.",
        STYLES['body']))

    story.append(h2("5.2 The decisive counter-evidence"))
    story.append(callout(
        "The single most damaging result",
        "The UBP substrate matches the arbitrary 9-digit integer 123,456,789 with "
        "relative error 0.000371% — <b>7.2 times better</b> than its match to c "
        "(0.002685%). If the substrate were predicting c, it should fail "
        "catastrophically when asked to match a random 9-digit integer. Instead it "
        "does better. This single fact is sufficient to refute the claim that the "
        "substrate has a special relationship to c.",
        color=SEM_ERROR))

    story.append(h2("5.3 What the UBP-c match actually is"))
    story.append(Paragraph(
        "The most charitable interpretation consistent with the evidence is that "
        "the UBP-c formula is a coincidence found by combinatorial search through "
        "a sufficiently flexible space. The substrate constants {π, φ, e, Y, MONAD, "
        "L, U_E, σ} span roughly twenty orders of magnitude in value, and the "
        "exponent space {−5, …, +5}<super>5</super> × {10 coefficients} provides enough "
        "combinatorial freedom to land within 0.01% of essentially any 9-digit "
        "target. The 0.0026852% match to c is one instance of this general "
        "flexibility, not a special prediction. The substrate's match to "
        "123,456,789 at 0.000371% confirms the same point: the substrate is "
        "flexible enough to match arbitrary 9-digit numbers, so its match to "
        "299,792,458 carries no special information.",
        STYLES['body']))

    story.append(h2("5.4 Are there any interesting insights?"))
    story.append(Paragraph(
        "The user asked specifically whether the method has 'interesting insights' "
        "even if it is not a true derivation. We can identify three, though none "
        "salvage the c-derivation claim:",
        STYLES['body']))

    story.append(Paragraph(
        "<b>(1) The combinatorial density of monomial products.</b> The fact that "
        "1.61M monomial combinations of just five substrate variables yield 38 "
        "formulas within 0.1% of c — and 39% of random-transcendental trials do "
        "the same — is a useful negative result for the broader field of "
        "physics-from-pure-math claims. It quantifies how easy it is to find "
        "spurious matches in flexible formula spaces, and provides a benchmark "
        "p-value (0.39) against which other proposed derivations can be tested. "
        "Any future claim of the form 'c is derived from constants X, Y, Z' "
        "should be required to beat this null model.",
        STYLES['body']))

    story.append(Paragraph(
        "<b>(2) The dimensional analysis obstruction is general.</b> The "
        "Buckingham Pi argument applies to any attempt to derive a dimensionful "
        "physical constant from a purely mathematical substrate. This is not "
        "specific to UBP; it applies equally to claims that the Planck length, "
        "the gravitational constant, or the electron mass can be derived from "
        "pure number theory. Without an external dimensional anchor, any such "
        "derivation is necessarily a numerological match to a chosen unit "
        "convention.",
        STYLES['body']))

    story.append(Paragraph(
        "<b>(3) The SI-definition circularity for c.</b> The audit surfaces a "
        "fact that is often overlooked in speed-of-light derivations: c = "
        "299,792,458 m/s is exact by definition since 1983, not a measurement. "
        "Any proposed derivation of c in SI units is therefore deriving a "
        "convention. A genuine prediction would have to derive either Δν_Cs "
        "(the caesium hyperfine frequency that defines the second) or a "
        "fundamental dimensionless constant like the fine-structure constant α. "
        "UBP does not attempt either.",
        STYLES['body']))

    story.append(h2("5.5 Overall verdict"))
    story.append(callout(
        "Final verdict",
        SUMMARY["overall_verdict"],
        color=SEM_ERROR))

    story.append(PageBreak())
    return story


def build_section_6_next_steps():
    story = []
    story.append(h1("6. What Would Change the Conclusion"))

    story.append(Paragraph(
        "A scientific audit is only as strong as the escape hatches it offers. We "
        "list below the specific kinds of evidence that, if produced, would "
        "force a re-evaluation of the verdict. None of these are currently "
        "met by the UBP-c formula or the surrounding framework.",
        STYLES['body']))

    story.append(h2("6.1 Strong evidence that would revive the claim"))
    story.append(Paragraph(
        "<b>(a) A principled derivation from UBP substrate objects, with no "
        "search.</b> If a UBP theorist could write down a formula for c using "
        "only first-principles constructions (e.g., 'c must equal |Λ_24| · Y^k "
        "because the Observer constant determines the rate of information "
        "propagation across the lattice'), and that formula landed within "
        "0.01% of c, that would be evidence of structural connection. The "
        "derivation must come BEFORE the numerical match, not after.",
        STYLES['body']))

    story.append(Paragraph(
        "<b>(b) Successful prediction of a dimensionless constant.</b> The "
        "strongest possible evidence would be a UBP derivation of the "
        "fine-structure constant α ≈ 1/137.035999, which is dimensionless and "
        "therefore not blocked by the dimensional analysis argument. If UBP "
        "could predict α to 5 significant figures from first principles, the "
        "framework would deserve serious attention. The README mentions an "
        "attempted formula <code>1/α = 220 − 83 + L</code> but flags it as an "
        "empirical projection lens, not a derivation.",
        STYLES['body']))

    story.append(Paragraph(
        "<b>(c) Successful prediction of Δν_Cs.</b> If UBP could derive the "
        "caesium hyperfine transition frequency (9,192,631,770 Hz, the actual "
        "anchor of the SI second) from substrate objects, then a genuine c "
        "derivation in SI units would become possible, and the dimensional "
        "objection would dissolve. This is a much harder target than c itself, "
        "but it is the right target.",
        STYLES['body']))

    story.append(h2("6.2 What would NOT change the conclusion"))
    story.append(Paragraph(
        "Certain kinds of evidence are insufficient on their own to revive the "
        "claim, even though they might superficially appear supportive:",
        STYLES['body']))

    story.append(Paragraph(
        "<b>(i) Finding additional UBP formulas that match other physical "
        "constants.</b> The substrate is flexible enough to match arbitrary "
        "9-digit numbers, so finding more matches proves nothing. Each new "
        "match must be evaluated on its own with the same null-model and MDL "
        "tests applied here.",
        STYLES['body']))

    story.append(Paragraph(
        "<b>(ii) Improving the precision of the c-match.</b> Searching a "
        "larger exponent space or adding more constants would certainly find "
        "a tighter match — but as Phase 1B shows, so would searching a "
        "larger exponent space with random transcendentals. Tighter matches "
        "from larger search spaces are evidence of <i>more</i> numerology, "
        "not less.",
        STYLES['body']))

    story.append(Paragraph(
        "<b>(iii) Post-hoc physical interpretations of the formula's "
        "structure.</b> Interpreting the exponent 5 on σ as 'five spatial "
        "dimensions of the MOG grid' or the coefficient 13 as 'an "
        "Archimedean sink' is interpretive overlay added after the formula "
        "was found. Such interpretations are not evidence; they are stories "
        "told about a coincidence. The DIMENSION_PROJECTION_REVIEW.md file "
        "in the user's own repository makes essentially this point about "
        "earlier UBP claims.",
        STYLES['body']))

    story.append(h2("6.3 Constructive recommendations"))
    story.append(Paragraph(
        "If the user wishes to continue the UBP research program, the "
        "constructive path forward is:",
        STYLES['body']))

    story.append(Paragraph(
        "<b>1. Switch to dimensionless targets.</b> Abandon attempts to "
        "derive c, G, h, or any dimensionful constant from the substrate. "
        "Focus instead on α (fine-structure constant), α_s (strong "
        "coupling), sin<super>2</super>θ_W (Weinberg angle), and particle mass ratios. "
        "These are dimensionless and not blocked by dimensional analysis.",
        STYLES['bullet']))

    story.append(Paragraph(
        "<b>2. Pre-register formulas before checking values.</b> Write down "
        "the formula and its physical motivation, then evaluate it against "
        "the target. Never search. The moment a search is performed, the "
        "result loses predictive status and becomes a fit.",
        STYLES['bullet']))

    story.append(Paragraph(
        "<b>3. Apply the random-transcendental null model to every claim.</b> "
        "The 200-trial null model used here is fast (about 15 seconds) and "
        "provides a calibrated p-value. Any UBP formula that does not beat "
        "p < 0.01 on this test should not be reported as a prediction.",
        STYLES['bullet']))

    story.append(Paragraph(
        "<b>4. Report MDL costs honestly.</b> For each proposed formula, "
        "compute the bits-to-specify and the bits-explained. If the ratio "
        "is below 1, the formula is informationally wasteful and should be "
        "disclosed as such.",
        STYLES['bullet']))

    story.append(Paragraph(
        "<b>5. Treat the existing DIMENSION_PROJECTION_REVIEW.md as a "
        "template.</b> That file demonstrates exactly the kind of rigorous "
        "self-audit that elevates UBP from numerology claim to "
        "scientifically respectable framework. The same rigour applied to "
        "the c-formula yields the present report.",
        STYLES['bullet']))

    story.append(PageBreak())
    return story


def build_appendix_a():
    story = []
    story.append(h1("Appendix A. Reproducibility"))

    story.append(h2("A.1 Scripts"))
    story.append(Paragraph(
        "All scripts used in this audit are saved under "
        "<code>/home/z/my-project/scripts/</code>. They are written in Python 3, "
        "use only standard scientific libraries (numpy, matplotlib), and the "
        "exact-rational <code>fractions.Fraction</code> class for substrate "
        "constants. No floating-point drift is introduced at any point in the "
        "computation of UBP substrate values.",
        STYLES['body']))

    script_rows = [
        ["ubp_constants.py",                "Exact UBP substrate constants (Fraction-based), reproduces user's baseline"],
        ["phase1_falsification.py",         "Phase 1A/1B/1C/1D — search enumeration, null model, permutation, MDL"],
        ["phase2_principled_derivation.py", "Phase 2 — dimensional analysis + 22 natural derivations"],
        ["phase3_cross_validation.py",      "Phase 3 — cross-unit, c-powers, SI anchors, decoys, sensitivity"],
        ["aggregate_results.py",            "Aggregates phase results, generates charts"],
        ["generate_pdf_report.py",          "This PDF report generator (ReportLab + TOC)"],
    ]
    story.append(make_table(
        ["Script", "Purpose"],
        script_rows,
        col_widths=[2.5, 4.5],
    ))
    story.append(Paragraph("Table A.1: Script inventory.", STYLES['caption']))

    story.append(h2("A.2 How to reproduce"))
    story.append(Paragraph(
        "To reproduce every number, chart, and verdict in this report end-to-end:",
        STYLES['body']))
    story.append(Paragraph(
        "cd /home/z/my-project/scripts<br/>"
        "python ubp_constants.py            # verify baseline<br/>"
        "python phase1_falsification.py     # ~20 seconds<br/>"
        "python phase2_principled_derivation.py   # &lt; 1 second<br/>"
        "python phase3_cross_validation.py  # ~5 seconds<br/>"
        "python aggregate_results.py        # generates charts<br/>"
        "python generate_pdf_report.py      # generates this PDF",
        STYLES['code']))

    story.append(h2("A.3 Exact UBP constants used"))
    story.append(Paragraph(
        "For full reproducibility, the exact rational forms of all substrate "
        "constants used in this audit are:",
        STYLES['body']))

    consts_rows = [
        ["PI",      "16590847 / 5281024",          "50-term continued fraction approximation (reduces to 2370121/754432)"],
        ["PHI",     "1618033988749895 / 10^15",    "Golden ratio, 15 significant digits"],
        ["E",       "2718281828459045 / 10^15",    "Euler's number, 16 significant digits"],
        ["Y_INV",   "PI + 2/PI",                   "= pi + 2/pi (computed exactly from PI)"],
        ["Y",       "1 / Y_INV",                   "Observer / Entropic Wobble constant"],
        ["MONAD",   "PI × PHI × E",                "Product substrate (exact rational)"],
        ["WOBBLE",  "MONAD − floor(MONAD)",        "Fractional part of MONAD"],
        ["L",       "WOBBLE / 13",                 "Leech-length constant"],
        ["U_E",     "13824 = 24<super>3</super>",                 "24-dimensional cubic unit"],
        ["σ",       "29 / 24",                     "Symmetry-tax modulator"],
        ["c_target", "299792458 (integer)",        "SI exact value of c (defined since 1983)"],
    ]
    story.append(make_table(
        ["Symbol", "Exact value", "Origin"],
        consts_rows,
        col_widths=[1.0, 2.5, 3.5],
    ))
    story.append(Paragraph(
        "Table A.2: Exact rational forms of all substrate constants. All arithmetic "
        "in the audit uses Python's <code>fractions.Fraction</code> class, which "
        "guarantees zero floating-point drift.",
        STYLES['caption']))

    story.append(PageBreak())
    return story


def build_appendix_b():
    story = []
    story.append(h1("Appendix B. Detailed Numerical Results"))

    story.append(h2("B.1 Top 10 UBP formulas by relative error to c"))
    top10 = P1["phase1a_search_enumeration"]["top_20_formulas"][:10]
    top_rows = []
    for i, f in enumerate(top10):
        top_rows.append([
            i+1,
            f["expr"],
            f"{f['value']:,.2f}",
            f"{f['rel_err_pct']:.7f}%",
        ])
    story.append(make_table(
        ["Rank", "Formula", "Value (m/s)", "Relative error"],
        top_rows,
        col_widths=[0.5, 3.5, 1.8, 1.5],
    ))
    story.append(Paragraph(
        "Table B.1: Top 10 formulas by relative error in the UBP search space. "
        "Rank 1 is the user's formula. Note that ranks 2–5 are within 0.02% — only "
        "6× worse than rank 1 — and have no principled relationship to UBP theory.",
        STYLES['caption']))

    story.append(h2("B.2 Phase 1B best 5 random-transcendental trials"))
    best5 = P1["phase1b_random_transcendentals"]["best_5_trials"]
    b5_rows = []
    for t in best5:
        b5_rows.append([
            t["trial"],
            ", ".join(t["constants"]),
            t["expr"][:60] + ("..." if len(t["expr"]) > 60 else ""),
            f"{t['best_err']*100:.7f}%",
        ])
    story.append(make_table(
        ["Trial #", "Constants sampled", "Best formula found", "Best error"],
        b5_rows,
        col_widths=[0.7, 2.5, 3.0, 1.5],
    ))
    story.append(Paragraph(
        "Table B.2: Five best random-transcendental trials out of 200. The "
        "constants are sampled from a 30-element pool of famous transcendentals. "
        "Each trial searches the same 1.61M-combination exponent space as the UBP "
        "search. The best trial (trial #108) found a match with error 4.6×10<super>-8</super> — "
        "580× better than UBP-c.",
        STYLES['caption']))

    story.append(h2("B.3 Phase 3 — full cross-target table"))
    all_targets = []
    for label, key in [("3A", "phase3a_cross_unit"), ("3B", "phase3b_c_powers"),
                        ("3C", "phase3c_si_anchors"), ("3D", "phase3d_decoys")]:
        for r in P3[key]:
            all_targets.append((label, r))

    # Sort by relative error (best first)
    all_targets.sort(key=lambda x: x[1]["best_match"]["rel_err"])

    target_rows = []
    ubp_err_pct = P1["metadata"]["ubp_error"] * 100
    for label, r in all_targets:
        bm = r["best_match"]
        better = "✓ better" if bm["rel_err_pct"] < ubp_err_pct else ""
        target_rows.append([
            f"[{label}]",
            r["target_name"],
            f"{r['target']:.4e}" if abs(r['target']) > 1e6 or abs(r['target']) < 1e-3 else f"{r['target']:,.2f}",
            bm["expr"][:35] + ("..." if len(bm["expr"]) > 35 else ""),
            f"{bm['rel_err_pct']:.5f}%",
            better,
        ])
    story.append(make_table(
        ["Phase", "Target", "Target value", "Best formula", "Best error", "vs UBP-c"],
        target_rows,
        col_widths=[0.5, 2.2, 1.5, 2.0, 1.0, 0.8],
    ))
    story.append(Paragraph(
        "Table B.3: All 28 cross-validation targets, sorted by best-match error. "
        "Targets marked '✓ better' were matched by the substrate with lower "
        "relative error than UBP-c matches c. Note that 11 of 28 targets beat "
        "UBP-c — including the random integer 123,456,789 (ranked #1 overall).",
        STYLES['caption']))

    story.append(h2("B.4 Phase 2 — full natural-derivation attempts"))
    deriv = P2["natural_derivations"]
    d_rows = []
    for d in deriv:
        if abs(d['value']) > 1e6 or abs(d['value']) < 1e-3:
            val_str = f"{d['value']:.4e}"
        else:
            val_str = f"{d['value']:,.4f}"
        ratio_str = f"{d['ratio_to_c']:.4e}" if d['ratio_to_c'] is not None else "—"
        d_rows.append([
            d['id'],
            d['rationale'][:55] + ("..." if len(d['rationale']) > 55 else ""),
            d['formula'],
            val_str,
            ratio_str,
            d['verdict'].replace('miss (off by > 10×)', 'miss').replace('near miss (within 10×)', 'near').replace('N/A (different target)', 'N/A'),
        ])
    story.append(make_table(
        ["ID", "Rationale", "Formula", "Value", "Ratio to c", "Verdict"],
        d_rows,
        col_widths=[0.4, 2.5, 1.6, 1.4, 1.2, 0.7],
    ))
    story.append(Paragraph(
        "Table B.4: All 22 natural constructions of UBP substrate objects tested "
        "against c. Zero hits, five near-misses (within 10×), seventeen misses.",
        STYLES['caption']))

    return story


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────
def main():
    print("[PDF] Building report...")
    os.makedirs(os.path.dirname(OUT_PDF), exist_ok=True)

    doc = TocDocTemplate(OUT_PDF, pagesize=A4,
                         title="UBP-c Falsification Study",
                         author="Z.ai (audit) · Euan Craig (UBP)",
                         subject="Scientific falsification of the UBP-c derived speed-of-light formula",
                         creator="Z.ai PDF Skill (Report brief / ReportLab)")

    story = []
    # Cover (uses Cover template — no header/footer)
    story.extend(build_cover())
    # TOC + body (uses Body template — header/footer)
    story.extend(build_toc())
    story.extend(build_executive_summary())
    story.extend(build_section_1_background())
    story.extend(build_section_2_phase1())
    story.extend(build_section_3_phase2())
    story.extend(build_section_4_phase3())
    story.extend(build_section_5_synthesis())
    story.extend(build_section_6_next_steps())
    story.extend(build_appendix_a())
    story.extend(build_appendix_b())

    print(f"[PDF] Total flowables: {len(story)}")
    doc.multiBuild(story)

    size_kb = os.path.getsize(OUT_PDF) / 1024
    print(f"[PDF] Saved: {OUT_PDF} ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()
